-- 25_updates.sql
--
-- Two weeks of daily puzzles (current_date+1 .. +13) arranged so each week ramps
-- Mon->Sun: Easy -> Medium -> Challenging -> Hard -> Brutal -> Evil.
-- Today (current_date, Mon) is left untouched. All boards obey the
-- no-disguised-type rule; base clues + hints carry hidden target positions.
-- Supersedes the dated rows from 22/23/24_updates.sql via upsert.
--
-- Schedule (difficulty from clue-category spread):
--   + 1  gen1 Medium       | mixed Medium
--   + 2  gen1 Challenging  | mixed Challenging
--   + 3  gen1 Challenging  | mixed Challenging
--   + 4  gen1 Hard         | mixed Hard
--   + 5  gen1 Brutal       | mixed Brutal
--   + 6  gen1 Evil         | mixed Evil
--   + 7  gen1 Easy         | mixed Easy
--   + 8  gen1 Medium       | mixed Medium
--   + 9  gen1 Challenging  | mixed Challenging
--   +10  gen1 Hard         | mixed Hard
--   +11  gen1 Hard         | mixed Hard
--   +12  gen1 Brutal       | mixed Hard
--   +13  gen1 Evil         | mixed Evil

insert into public.daily_puzzles (puzzle_date, pool, clues, hints, tiles) values
(
  current_date + 1, 'gen1',
  '[{"word": "FIRE", "number": 2, "cat": 1, "t": [0, 2]}, {"word": "WATER", "number": 2, "cat": 1, "t": [4, 6]}, {"word": "HORN", "number": 2, "cat": 2, "t": [8, 10]}, {"word": "ORPHAN", "number": 1, "cat": 4, "t": [12]}, {"word": "NIPPERS", "number": 2, "cat": 2, "t": [14, 16]}]'::jsonb,
  '[{"word": "PUPPY", "number": 1, "cat": 2, "t": [0]}, {"word": "MANE", "number": 1, "cat": 2, "t": [2]}, {"word": "SWIRL", "number": 1, "cat": 2, "t": [4]}, {"word": "SEAL", "number": 1, "cat": 2, "t": [6]}, {"word": "DRILL", "number": 1, "cat": 2, "t": [8]}, {"word": "BARBS", "number": 1, "cat": 2, "t": [10]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [12]}, {"word": "CLAW", "number": 1, "cat": 2, "t": [14]}, {"word": "STAG", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Growlithe','blue'),(1,'Pikachu','neutral'),(2,'Ponyta','blue'),(3,'Raichu','neutral'),(4,'Poliwag','blue'),(5,'Gastly','neutral'),(6,'Seel','blue'),(7,'Golbat','neutral'),(8,'Rhydon','blue'),(9,'Gengar','neutral'),(10,'Nidoking','blue'),(11,'Koffing','neutral'),(12,'Cubone','blue'),(13,'Grimer','neutral'),(14,'Krabby','blue'),(15,'Meowth','neutral'),(16,'Pinsir','blue'),(17,'Rattata','neutral'),(18,'Abra','neutral'),(19,'Kadabra','neutral'),(20,'Machop','neutral'),(21,'Onix','neutral'),(22,'Zubat','neutral'),(23,'Ekans','neutral'),(24,'Sandshrew','neutral')) v(position,name,colour))
),
(
  current_date + 1, 'mixed',
  '[{"word": "FIRE", "number": 2, "cat": 1, "t": [0, 2]}, {"word": "WATER", "number": 2, "cat": 1, "t": [4, 6]}, {"word": "AURA", "number": 1, "cat": 4, "t": [8]}, {"word": "THREE", "number": 2, "cat": 2, "t": [10, 12]}, {"word": "SWORDS", "number": 2, "cat": 2, "t": [14, 16]}]'::jsonb,
  '[{"word": "EMBER", "number": 1, "cat": 2, "t": [0]}, {"word": "PUPPY", "number": 1, "cat": 2, "t": [2]}, {"word": "SHELL", "number": 1, "cat": 2, "t": [4]}, {"word": "FINS", "number": 1, "cat": 2, "t": [6]}, {"word": "JACKAL", "number": 1, "cat": 2, "t": [8]}, {"word": "BEAKS", "number": 1, "cat": 2, "t": [10]}, {"word": "MOLES", "number": 1, "cat": 2, "t": [12]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [14]}, {"word": "ELBOWS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Charizard','blue'),(1,'Pikachu','neutral'),(2,'Arcanine','blue'),(3,'Raichu','neutral'),(4,'Blastoise','blue'),(5,'Snorlax','neutral'),(6,'Vaporeon','blue'),(7,'Gengar','neutral'),(8,'Lucario','blue'),(9,'Umbreon','neutral'),(10,'Dodrio','blue'),(11,'Espeon','neutral'),(12,'Dugtrio','blue'),(13,'Sylveon','neutral'),(14,'Scizor','blue'),(15,'Togekiss','neutral'),(16,'Gallade','blue'),(17,'Metagross','neutral'),(18,'Garchomp','neutral'),(19,'Tyranitar','neutral'),(20,'Dragonite','neutral'),(21,'Salamence','neutral'),(22,'Gardevoir','neutral'),(23,'Rhyperior','neutral'),(24,'Luxray','neutral')) v(position,name,colour))
),
(
  current_date + 2, 'gen1',
  '[{"word": "YELLOW", "number": 3, "cat": 1, "t": [0, 2, 4]}, {"word": "HORN", "number": 2, "cat": 2, "t": [6, 8]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [10]}, {"word": "POUCH", "number": 1, "cat": 4, "t": [12]}, {"word": "NIPPERS", "number": 2, "cat": 2, "t": [14, 16]}]'::jsonb,
  '[{"word": "CHEEKS", "number": 1, "cat": 2, "t": [0]}, {"word": "PLUG", "number": 1, "cat": 2, "t": [2]}, {"word": "SPOON", "number": 1, "cat": 2, "t": [4]}, {"word": "DRILL", "number": 1, "cat": 2, "t": [6]}, {"word": "BARBS", "number": 1, "cat": 2, "t": [8]}, {"word": "HELMET", "number": 1, "cat": 2, "t": [10]}, {"word": "BABY", "number": 1, "cat": 4, "t": [12]}, {"word": "STAG", "number": 1, "cat": 2, "t": [14]}, {"word": "CLAW", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Pikachu','blue'),(1,'Gengar','neutral'),(2,'Electabuzz','blue'),(3,'Haunter','neutral'),(4,'Kadabra','blue'),(5,'Gastly','neutral'),(6,'Rhydon','blue'),(7,'Koffing','neutral'),(8,'Nidoking','blue'),(9,'Weezing','neutral'),(10,'Cubone','blue'),(11,'Grimer','neutral'),(12,'Kangaskhan','blue'),(13,'Muk','neutral'),(14,'Pinsir','blue'),(15,'Snorlax','neutral'),(16,'Kingler','blue'),(17,'Lapras','neutral'),(18,'Dewgong','neutral'),(19,'Cloyster','neutral'),(20,'Seel','neutral'),(21,'Golem','neutral'),(22,'Zubat','neutral'),(23,'Machamp','neutral'),(24,'Onix','neutral')) v(position,name,colour))
),
(
  current_date + 2, 'mixed',
  '[{"word": "GHOST", "number": 3, "cat": 1, "t": [0, 2, 4]}, {"word": "SWORDS", "number": 2, "cat": 2, "t": [6, 8]}, {"word": "AURA", "number": 1, "cat": 4, "t": [10]}, {"word": "HEADS", "number": 1, "cat": 2, "t": [12]}, {"word": "PSEUDO", "number": 2, "cat": 5, "t": [14, 16]}]'::jsonb,
  '[{"word": "GRIN", "number": 1, "cat": 3, "t": [0]}, {"word": "WITCH", "number": 1, "cat": 2, "t": [2]}, {"word": "LAMP", "number": 1, "cat": 2, "t": [4]}, {"word": "PINCERS", "number": 1, "cat": 2, "t": [6]}, {"word": "SWORD", "number": 1, "cat": 2, "t": [8]}, {"word": "JACKAL", "number": 1, "cat": 2, "t": [10]}, {"word": "VIOLENT", "number": 1, "cat": 4, "t": [12]}, {"word": "FINS", "number": 1, "cat": 2, "t": [14]}, {"word": "RAMPAGE", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Gengar','blue'),(1,'Pikachu','neutral'),(2,'Mismagius','blue'),(3,'Raichu','neutral'),(4,'Chandelure','blue'),(5,'Snorlax','neutral'),(6,'Scizor','blue'),(7,'Blissey','neutral'),(8,'Aegislash','blue'),(9,'Togekiss','neutral'),(10,'Lucario','blue'),(11,'Sylveon','neutral'),(12,'Hydreigon','blue'),(13,'Umbreon','neutral'),(14,'Garchomp','blue'),(15,'Espeon','neutral'),(16,'Tyranitar','blue'),(17,'Arcanine','neutral'),(18,'Ninetales','neutral'),(19,'Luxray','neutral'),(20,'Rillaboom','neutral'),(21,'Charizard','neutral'),(22,'Alomomola','neutral'),(23,'Audino','neutral'),(24,'Chansey','neutral')) v(position,name,colour))
),
(
  current_date + 3, 'gen1',
  '[{"word": "FIRE", "number": 2, "cat": 1, "t": [0, 2]}, {"word": "SLEEP", "number": 2, "cat": 3, "t": [4, 6]}, {"word": "BALL", "number": 2, "cat": 3, "t": [8, 10]}, {"word": "SPOONS", "number": 2, "cat": 2, "t": [12, 14]}, {"word": "TONGUE", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  '[{"word": "PUPPY", "number": 1, "cat": 2, "t": [0]}, {"word": "MANE", "number": 1, "cat": 2, "t": [2]}, {"word": "NAP", "number": 1, "cat": 3, "t": [4]}, {"word": "PENDULUM", "number": 1, "cat": 4, "t": [6]}, {"word": "SPHERE", "number": 1, "cat": 2, "t": [8]}, {"word": "DYNAMITE", "number": 1, "cat": 4, "t": [10]}, {"word": "SMART", "number": 1, "cat": 4, "t": [12]}, {"word": "PSYCHIC", "number": 1, "cat": 1, "t": [14]}, {"word": "SLURP", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Growlithe','blue'),(1,'Pikachu','neutral'),(2,'Ponyta','blue'),(3,'Raichu','neutral'),(4,'Drowzee','blue'),(5,'Meowth','neutral'),(6,'Hypno','blue'),(7,'Persian','neutral'),(8,'Voltorb','blue'),(9,'Gengar','neutral'),(10,'Electrode','blue'),(11,'Haunter','neutral'),(12,'Alakazam','blue'),(13,'Gastly','neutral'),(14,'Kadabra','blue'),(15,'Grimer','neutral'),(16,'Lickitung','blue'),(17,'Muk','neutral'),(18,'Machop','neutral'),(19,'Machamp','neutral'),(20,'Onix','neutral'),(21,'Geodude','neutral'),(22,'Golem','neutral'),(23,'Rhydon','neutral'),(24,'Nidoking','neutral')) v(position,name,colour))
),
(
  current_date + 3, 'mixed',
  '[{"word": "GHOST", "number": 3, "cat": 1, "t": [0, 2, 4]}, {"word": "BLADES", "number": 2, "cat": 2, "t": [6, 8]}, {"word": "AURA", "number": 1, "cat": 4, "t": [10]}, {"word": "HEADS", "number": 1, "cat": 2, "t": [12]}, {"word": "PSEUDO", "number": 2, "cat": 5, "t": [14, 16]}]'::jsonb,
  '[{"word": "GRIN", "number": 1, "cat": 3, "t": [0]}, {"word": "WITCH", "number": 1, "cat": 2, "t": [2]}, {"word": "LAMP", "number": 1, "cat": 2, "t": [4]}, {"word": "PINCERS", "number": 1, "cat": 2, "t": [6]}, {"word": "SWORD", "number": 1, "cat": 2, "t": [8]}, {"word": "JACKAL", "number": 1, "cat": 2, "t": [10]}, {"word": "VIOLENT", "number": 1, "cat": 4, "t": [12]}, {"word": "FINS", "number": 1, "cat": 2, "t": [14]}, {"word": "RAMPAGE", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Gengar','blue'),(1,'Pikachu','neutral'),(2,'Mismagius','blue'),(3,'Raichu','neutral'),(4,'Chandelure','blue'),(5,'Snorlax','neutral'),(6,'Scizor','blue'),(7,'Blissey','neutral'),(8,'Aegislash','blue'),(9,'Togekiss','neutral'),(10,'Lucario','blue'),(11,'Sylveon','neutral'),(12,'Hydreigon','blue'),(13,'Umbreon','neutral'),(14,'Garchomp','blue'),(15,'Espeon','neutral'),(16,'Tyranitar','blue'),(17,'Arcanine','neutral'),(18,'Ninetales','neutral'),(19,'Luxray','neutral'),(20,'Rillaboom','neutral'),(21,'Charizard','neutral'),(22,'Alomomola','neutral'),(23,'Audino','neutral'),(24,'Chansey','neutral')) v(position,name,colour))
),
(
  current_date + 4, 'gen1',
  '[{"word": "THREE", "number": 3, "cat": 2, "t": [0, 2, 4]}, {"word": "SIX", "number": 1, "cat": 2, "t": [6]}, {"word": "BALL", "number": 2, "cat": 3, "t": [8, 10]}, {"word": "SIBLINGS", "number": 2, "cat": 4, "t": [12, 14]}, {"word": "BARRIER", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  '[{"word": "DIG", "number": 1, "cat": 2, "t": [0]}, {"word": "BEAKS", "number": 1, "cat": 2, "t": [2]}, {"word": "SCREWS", "number": 1, "cat": 2, "t": [4]}, {"word": "SEEDS", "number": 1, "cat": 2, "t": [6]}, {"word": "SPHERE", "number": 1, "cat": 2, "t": [8]}, {"word": "DYNAMITE", "number": 1, "cat": 4, "t": [10]}, {"word": "KICK", "number": 1, "cat": 3, "t": [12]}, {"word": "GLOVES", "number": 1, "cat": 2, "t": [14]}, {"word": "INVISIBLE", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Dugtrio','blue'),(1,'Gengar','neutral'),(2,'Dodrio','blue'),(3,'Haunter','neutral'),(4,'Magneton','blue'),(5,'Gastly','neutral'),(6,'Exeggcute','blue'),(7,'Grimer','neutral'),(8,'Voltorb','blue'),(9,'Muk','neutral'),(10,'Electrode','blue'),(11,'Ekans','neutral'),(12,'Hitmonlee','blue'),(13,'Arbok','neutral'),(14,'Hitmonchan','blue'),(15,'Machoke','neutral'),(16,'Mr. Mime','blue'),(17,'Onix','neutral'),(18,'Golem','neutral'),(19,'Graveler','neutral'),(20,'Cubone','neutral'),(21,'Marowak','neutral'),(22,'Lapras','neutral'),(23,'Persian','neutral'),(24,'Meowth','neutral')) v(position,name,colour))
),
(
  current_date + 4, 'mixed',
  '[{"word": "SWORDS", "number": 3, "cat": 2, "t": [0, 2, 4]}, {"word": "AURA", "number": 1, "cat": 4, "t": [6]}, {"word": "GOWN", "number": 1, "cat": 2, "t": [8]}, {"word": "PSEUDO", "number": 3, "cat": 5, "t": [10, 12, 14]}, {"word": "FROG", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  '[{"word": "CLAWS", "number": 1, "cat": 2, "t": [0]}, {"word": "SWORD", "number": 1, "cat": 2, "t": [2]}, {"word": "ELBOWS", "number": 1, "cat": 2, "t": [4]}, {"word": "JACKAL", "number": 1, "cat": 2, "t": [6]}, {"word": "DRESS", "number": 1, "cat": 2, "t": [8]}, {"word": "RAMPAGE", "number": 1, "cat": 4, "t": [10]}, {"word": "FINS", "number": 1, "cat": 2, "t": [12]}, {"word": "CRESCENT", "number": 1, "cat": 2, "t": [14]}, {"word": "TONGUE", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Scizor','blue'),(1,'Pikachu','neutral'),(2,'Aegislash','blue'),(3,'Raichu','neutral'),(4,'Gallade','blue'),(5,'Snorlax','neutral'),(6,'Lucario','blue'),(7,'Blissey','neutral'),(8,'Gardevoir','blue'),(9,'Chansey','neutral'),(10,'Tyranitar','blue'),(11,'Audino','neutral'),(12,'Garchomp','blue'),(13,'Togekiss','neutral'),(14,'Salamence','blue'),(15,'Sylveon','neutral'),(16,'Greninja','blue'),(17,'Umbreon','neutral'),(18,'Espeon','neutral'),(19,'Arcanine','neutral'),(20,'Ninetales','neutral'),(21,'Gengar','neutral'),(22,'Charizard','neutral'),(23,'Luxray','neutral'),(24,'Rillaboom','neutral')) v(position,name,colour))
),
(
  current_date + 5, 'gen1',
  '[{"word": "FOSSIL", "number": 3, "cat": 4, "t": [0, 2, 4]}, {"word": "MORPH", "number": 1, "cat": 5, "t": [6]}, {"word": "PIXEL", "number": 1, "cat": 4, "t": [8]}, {"word": "HORN", "number": 2, "cat": 2, "t": [10, 12]}, {"word": "SPOONS", "number": 2, "cat": 2, "t": [14, 16]}]'::jsonb,
  '[{"word": "SICKLE", "number": 1, "cat": 2, "t": [0]}, {"word": "SPIRAL", "number": 1, "cat": 2, "t": [2]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [4]}, {"word": "COPY", "number": 1, "cat": 4, "t": [6]}, {"word": "DIGITAL", "number": 1, "cat": 4, "t": [8]}, {"word": "DRILL", "number": 1, "cat": 2, "t": [10]}, {"word": "BARBS", "number": 1, "cat": 2, "t": [12]}, {"word": "SMART", "number": 1, "cat": 4, "t": [14]}, {"word": "PSYCHIC", "number": 1, "cat": 1, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Kabutops','blue'),(1,'Gengar','neutral'),(2,'Omastar','blue'),(3,'Haunter','neutral'),(4,'Aerodactyl','blue'),(5,'Gastly','neutral'),(6,'Ditto','blue'),(7,'Koffing','neutral'),(8,'Porygon','blue'),(9,'Weezing','neutral'),(10,'Rhydon','blue'),(11,'Grimer','neutral'),(12,'Nidoking','blue'),(13,'Muk','neutral'),(14,'Alakazam','blue'),(15,'Machamp','neutral'),(16,'Kadabra','blue'),(17,'Machoke','neutral'),(18,'Snorlax','neutral'),(19,'Lapras','neutral'),(20,'Dewgong','neutral'),(21,'Cloyster','neutral'),(22,'Seel','neutral'),(23,'Persian','neutral'),(24,'Meowth','neutral')) v(position,name,colour))
),
(
  current_date + 5, 'mixed',
  '[{"word": "BOND", "number": 3, "cat": 5, "t": [0, 2, 4]}, {"word": "GRACE", "number": 2, "cat": 3, "t": [6, 8]}, {"word": "TAILS", "number": 1, "cat": 4, "t": [10]}, {"word": "MOONLIGHT", "number": 1, "cat": 4, "t": [12]}, {"word": "BLADES", "number": 2, "cat": 2, "t": [14, 16]}]'::jsonb,
  '[{"word": "RINGS", "number": 1, "cat": 2, "t": [0]}, {"word": "SUN", "number": 1, "cat": 4, "t": [2]}, {"word": "RIBBON", "number": 1, "cat": 2, "t": [4]}, {"word": "ANGEL", "number": 1, "cat": 2, "t": [6]}, {"word": "GOWN", "number": 1, "cat": 2, "t": [8]}, {"word": "FOX", "number": 1, "cat": 2, "t": [10]}, {"word": "FAIRY", "number": 1, "cat": 1, "t": [12]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [14]}, {"word": "SWORD", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Umbreon','blue'),(1,'Snorlax','neutral'),(2,'Espeon','blue'),(3,'Blissey','neutral'),(4,'Sylveon','blue'),(5,'Chansey','neutral'),(6,'Togekiss','blue'),(7,'Audino','neutral'),(8,'Gardevoir','blue'),(9,'Alomomola','neutral'),(10,'Ninetales','blue'),(11,'Pikachu','neutral'),(12,'Clefable','blue'),(13,'Raichu','neutral'),(14,'Scizor','blue'),(15,'Luxray','neutral'),(16,'Aegislash','blue'),(17,'Arcanine','neutral'),(18,'Incineroar','neutral'),(19,'Lucario','neutral'),(20,'Rhyperior','neutral'),(21,'Dragonite','neutral'),(22,'Salamence','neutral'),(23,'Garchomp','neutral'),(24,'Tyranitar','neutral')) v(position,name,colour))
),
(
  current_date + 6, 'gen1',
  '[{"word": "PINK", "number": 3, "cat": 1, "t": [0, 2, 4]}, {"word": "RIVALS", "number": 2, "cat": 4, "t": [6, 8]}, {"word": "WIELD", "number": 2, "cat": 4, "t": [10, 12]}, {"word": "POUCH", "number": 1, "cat": 4, "t": [14]}, {"word": "BARRIER", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  '[{"word": "EGG", "number": 1, "cat": 2, "t": [0]}, {"word": "BALLOON", "number": 1, "cat": 2, "t": [2]}, {"word": "SLURP", "number": 1, "cat": 2, "t": [4]}, {"word": "PLUG", "number": 1, "cat": 2, "t": [6]}, {"word": "FLAME", "number": 1, "cat": 2, "t": [8]}, {"word": "SPOON", "number": 1, "cat": 2, "t": [10]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [12]}, {"word": "BABY", "number": 1, "cat": 4, "t": [14]}, {"word": "CLOWN", "number": 1, "cat": 3, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Chansey','blue'),(1,'Gengar','neutral'),(2,'Jigglypuff','blue'),(3,'Haunter','neutral'),(4,'Lickitung','blue'),(5,'Gastly','neutral'),(6,'Electabuzz','blue'),(7,'Grimer','neutral'),(8,'Magmar','blue'),(9,'Muk','neutral'),(10,'Alakazam','blue'),(11,'Ekans','neutral'),(12,'Cubone','blue'),(13,'Arbok','neutral'),(14,'Kangaskhan','blue'),(15,'Machoke','neutral'),(16,'Mr. Mime','blue'),(17,'Onix','neutral'),(18,'Golem','neutral'),(19,'Graveler','neutral'),(20,'Voltorb','neutral'),(21,'Electrode','neutral'),(22,'Magnemite','neutral'),(23,'Magneton','neutral'),(24,'Zubat','neutral')) v(position,name,colour))
),
(
  current_date + 6, 'mixed',
  '[{"word": "BOND", "number": 3, "cat": 5, "t": [0, 2, 4]}, {"word": "TRICKSTER", "number": 3, "cat": 5, "t": [6, 8, 10]}, {"word": "NIGHTMARE", "number": 1, "cat": 4, "t": [12]}, {"word": "SWIFT", "number": 1, "cat": 5, "t": [14]}, {"word": "THIEF", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  '[{"word": "RINGS", "number": 1, "cat": 2, "t": [0]}, {"word": "SUN", "number": 1, "cat": 4, "t": [2]}, {"word": "RIBBON", "number": 1, "cat": 2, "t": [4]}, {"word": "COPY", "number": 1, "cat": 4, "t": [6]}, {"word": "FOX", "number": 1, "cat": 2, "t": [8]}, {"word": "CLOTH", "number": 1, "cat": 3, "t": [10]}, {"word": "GRIN", "number": 1, "cat": 3, "t": [12]}, {"word": "ROCKET", "number": 1, "cat": 4, "t": [14]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Umbreon','blue'),(1,'Snorlax','neutral'),(2,'Espeon','blue'),(3,'Blissey','neutral'),(4,'Sylveon','blue'),(5,'Chansey','neutral'),(6,'Ditto','blue'),(7,'Audino','neutral'),(8,'Zoroark','blue'),(9,'Togekiss','neutral'),(10,'Mimikyu','blue'),(11,'Clefable','neutral'),(12,'Gengar','blue'),(13,'Gardevoir','neutral'),(14,'Dragapult','blue'),(15,'Lucario','neutral'),(16,'Weavile','blue'),(17,'Garchomp','neutral'),(18,'Tyranitar','neutral'),(19,'Metagross','neutral'),(20,'Dragonite','neutral'),(21,'Salamence','neutral'),(22,'Pikachu','neutral'),(23,'Raichu','neutral'),(24,'Rillaboom','neutral')) v(position,name,colour))
),
(
  current_date + 7, 'gen1',
  '[{"word": "FIRE", "number": 2, "cat": 1, "t": [0, 2]}, {"word": "WATER", "number": 2, "cat": 1, "t": [4, 6]}, {"word": "PINK", "number": 2, "cat": 1, "t": [8, 10]}, {"word": "BUG", "number": 2, "cat": 1, "t": [12, 14]}, {"word": "CHEEKS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  '[{"word": "PUPPY", "number": 1, "cat": 2, "t": [0]}, {"word": "FOX", "number": 1, "cat": 2, "t": [2]}, {"word": "SHELL", "number": 1, "cat": 2, "t": [4]}, {"word": "SWIRL", "number": 1, "cat": 2, "t": [6]}, {"word": "BALLOON", "number": 1, "cat": 2, "t": [8]}, {"word": "EGG", "number": 1, "cat": 2, "t": [10]}, {"word": "CRAB", "number": 1, "cat": 2, "t": [12]}, {"word": "BARB", "number": 1, "cat": 2, "t": [14]}, {"word": "MOUSE", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Growlithe','blue'),(1,'Rattata','neutral'),(2,'Vulpix','blue'),(3,'Ekans','neutral'),(4,'Squirtle','blue'),(5,'Sandshrew','neutral'),(6,'Poliwag','blue'),(7,'Zubat','neutral'),(8,'Jigglypuff','blue'),(9,'Diglett','neutral'),(10,'Chansey','blue'),(11,'Meowth','neutral'),(12,'Paras','blue'),(13,'Mankey','neutral'),(14,'Weedle','blue'),(15,'Machop','neutral'),(16,'Pikachu','blue'),(17,'Geodude','neutral'),(18,'Gastly','neutral'),(19,'Onix','neutral'),(20,'Drowzee','neutral'),(21,'Abra','neutral'),(22,'Cubone','neutral'),(23,'Koffing','neutral'),(24,'Grimer','neutral')) v(position,name,colour))
),
(
  current_date + 7, 'mixed',
  '[{"word": "FIRE", "number": 2, "cat": 1, "t": [0, 2]}, {"word": "WATER", "number": 2, "cat": 1, "t": [4, 6]}, {"word": "PINK", "number": 2, "cat": 1, "t": [8, 10]}, {"word": "ELECTRIC", "number": 2, "cat": 1, "t": [12, 14]}, {"word": "GRIN", "number": 1, "cat": 3, "t": [16]}]'::jsonb,
  '[{"word": "EMBER", "number": 1, "cat": 2, "t": [0]}, {"word": "PUPPY", "number": 1, "cat": 2, "t": [2]}, {"word": "SHELL", "number": 1, "cat": 2, "t": [4]}, {"word": "TONGUE", "number": 1, "cat": 2, "t": [6]}, {"word": "RIBBON", "number": 1, "cat": 2, "t": [8]}, {"word": "FAIRY", "number": 1, "cat": 1, "t": [10]}, {"word": "CHEEKS", "number": 1, "cat": 2, "t": [12]}, {"word": "MANE", "number": 1, "cat": 2, "t": [14]}, {"word": "PURPLE", "number": 1, "cat": 1, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Charizard','blue'),(1,'Snorlax','neutral'),(2,'Arcanine','blue'),(3,'Aggron','neutral'),(4,'Blastoise','blue'),(5,'Togekiss','neutral'),(6,'Greninja','blue'),(7,'Umbreon','neutral'),(8,'Sylveon','blue'),(9,'Espeon','neutral'),(10,'Clefable','blue'),(11,'Lucario','neutral'),(12,'Pikachu','blue'),(13,'Garchomp','neutral'),(14,'Luxray','blue'),(15,'Tyranitar','neutral'),(16,'Gengar','blue'),(17,'Metagross','neutral'),(18,'Dragonite','neutral'),(19,'Salamence','neutral'),(20,'Gardevoir','neutral'),(21,'Rhyperior','neutral'),(22,'Machamp','neutral'),(23,'Onix','neutral'),(24,'Golem','neutral')) v(position,name,colour))
),
(
  current_date + 8, 'gen1',
  '[{"word": "FIRE", "number": 2, "cat": 1, "t": [0, 2]}, {"word": "WATER", "number": 2, "cat": 1, "t": [4, 6]}, {"word": "SPOONS", "number": 2, "cat": 2, "t": [8, 10]}, {"word": "HORN", "number": 2, "cat": 2, "t": [12, 14]}, {"word": "ORPHAN", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  '[{"word": "PUPPY", "number": 1, "cat": 2, "t": [0]}, {"word": "FOX", "number": 1, "cat": 2, "t": [2]}, {"word": "SHELL", "number": 1, "cat": 2, "t": [4]}, {"word": "SEAL", "number": 1, "cat": 2, "t": [6]}, {"word": "SMART", "number": 1, "cat": 4, "t": [8]}, {"word": "PSYCHIC", "number": 1, "cat": 1, "t": [10]}, {"word": "DRILL", "number": 1, "cat": 2, "t": [12]}, {"word": "BARBS", "number": 1, "cat": 2, "t": [14]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Growlithe','blue'),(1,'Pikachu','neutral'),(2,'Vulpix','blue'),(3,'Raichu','neutral'),(4,'Squirtle','blue'),(5,'Gengar','neutral'),(6,'Seel','blue'),(7,'Golduck','neutral'),(8,'Alakazam','blue'),(9,'Gastly','neutral'),(10,'Kadabra','blue'),(11,'Koffing','neutral'),(12,'Rhydon','blue'),(13,'Grimer','neutral'),(14,'Nidoking','blue'),(15,'Muk','neutral'),(16,'Cubone','blue'),(17,'Meowth','neutral'),(18,'Persian','neutral'),(19,'Machop','neutral'),(20,'Machamp','neutral'),(21,'Onix','neutral'),(22,'Geodude','neutral'),(23,'Zubat','neutral'),(24,'Golbat','neutral')) v(position,name,colour))
),
(
  current_date + 8, 'mixed',
  '[{"word": "FIRE", "number": 2, "cat": 1, "t": [0, 2]}, {"word": "WATER", "number": 2, "cat": 1, "t": [4, 6]}, {"word": "AURA", "number": 1, "cat": 4, "t": [8]}, {"word": "THREE", "number": 2, "cat": 2, "t": [10, 12]}, {"word": "SWORDS", "number": 2, "cat": 2, "t": [14, 16]}]'::jsonb,
  '[{"word": "EMBER", "number": 1, "cat": 2, "t": [0]}, {"word": "KICK", "number": 1, "cat": 3, "t": [2]}, {"word": "CANNON", "number": 1, "cat": 2, "t": [4]}, {"word": "TRIDENT", "number": 1, "cat": 2, "t": [6]}, {"word": "JACKAL", "number": 1, "cat": 2, "t": [8]}, {"word": "BEAKS", "number": 1, "cat": 2, "t": [10]}, {"word": "BOLTS", "number": 1, "cat": 2, "t": [12]}, {"word": "SWORD", "number": 1, "cat": 2, "t": [14]}, {"word": "ELBOWS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Charizard','blue'),(1,'Pikachu','neutral'),(2,'Blaziken','blue'),(3,'Raichu','neutral'),(4,'Blastoise','blue'),(5,'Snorlax','neutral'),(6,'Empoleon','blue'),(7,'Gengar','neutral'),(8,'Lucario','blue'),(9,'Umbreon','neutral'),(10,'Dodrio','blue'),(11,'Espeon','neutral'),(12,'Magneton','blue'),(13,'Sylveon','neutral'),(14,'Aegislash','blue'),(15,'Togekiss','neutral'),(16,'Gallade','blue'),(17,'Garchomp','neutral'),(18,'Tyranitar','neutral'),(19,'Dragonite','neutral'),(20,'Salamence','neutral'),(21,'Gardevoir','neutral'),(22,'Rhyperior','neutral'),(23,'Luxray','neutral'),(24,'Rillaboom','neutral')) v(position,name,colour))
),
(
  current_date + 9, 'gen1',
  '[{"word": "WATER", "number": 3, "cat": 1, "t": [0, 2, 4]}, {"word": "SLEEP", "number": 2, "cat": 3, "t": [6, 8]}, {"word": "SPOONS", "number": 2, "cat": 2, "t": [10, 12]}, {"word": "ORPHAN", "number": 1, "cat": 4, "t": [14]}, {"word": "TONGUE", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  '[{"word": "SWIRL", "number": 1, "cat": 2, "t": [0]}, {"word": "INK", "number": 1, "cat": 2, "t": [2]}, {"word": "CLAW", "number": 1, "cat": 2, "t": [4]}, {"word": "NAP", "number": 1, "cat": 3, "t": [6]}, {"word": "PENDULUM", "number": 1, "cat": 4, "t": [8]}, {"word": "SMART", "number": 1, "cat": 4, "t": [10]}, {"word": "PSYCHIC", "number": 1, "cat": 1, "t": [12]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [14]}, {"word": "SLURP", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Poliwag','blue'),(1,'Pikachu','neutral'),(2,'Horsea','blue'),(3,'Raichu','neutral'),(4,'Krabby','blue'),(5,'Gengar','neutral'),(6,'Drowzee','blue'),(7,'Golbat','neutral'),(8,'Hypno','blue'),(9,'Gastly','neutral'),(10,'Alakazam','blue'),(11,'Grimer','neutral'),(12,'Kadabra','blue'),(13,'Muk','neutral'),(14,'Cubone','blue'),(15,'Meowth','neutral'),(16,'Lickitung','blue'),(17,'Persian','neutral'),(18,'Machop','neutral'),(19,'Machamp','neutral'),(20,'Onix','neutral'),(21,'Geodude','neutral'),(22,'Golem','neutral'),(23,'Rhydon','neutral'),(24,'Nidoking','neutral')) v(position,name,colour))
),
(
  current_date + 9, 'mixed',
  '[{"word": "WATER", "number": 3, "cat": 1, "t": [0, 2, 4]}, {"word": "AURA", "number": 1, "cat": 4, "t": [6]}, {"word": "GOWN", "number": 1, "cat": 2, "t": [8]}, {"word": "PSEUDO", "number": 3, "cat": 5, "t": [10, 12, 14]}, {"word": "GRIN", "number": 1, "cat": 3, "t": [16]}]'::jsonb,
  '[{"word": "TONGUE", "number": 1, "cat": 2, "t": [0]}, {"word": "TRIDENT", "number": 1, "cat": 2, "t": [2]}, {"word": "MUD", "number": 1, "cat": 2, "t": [4]}, {"word": "JACKAL", "number": 1, "cat": 2, "t": [6]}, {"word": "ELEGANT", "number": 1, "cat": 3, "t": [8]}, {"word": "FINS", "number": 1, "cat": 2, "t": [10]}, {"word": "CRESCENT", "number": 1, "cat": 2, "t": [12]}, {"word": "SAVAGE", "number": 1, "cat": 4, "t": [14]}, {"word": "PURPLE", "number": 1, "cat": 1, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Greninja','blue'),(1,'Pikachu','neutral'),(2,'Empoleon','blue'),(3,'Raichu','neutral'),(4,'Swampert','blue'),(5,'Snorlax','neutral'),(6,'Lucario','blue'),(7,'Blissey','neutral'),(8,'Gardevoir','blue'),(9,'Togekiss','neutral'),(10,'Garchomp','blue'),(11,'Sylveon','neutral'),(12,'Salamence','blue'),(13,'Umbreon','neutral'),(14,'Hydreigon','blue'),(15,'Espeon','neutral'),(16,'Gengar','blue'),(17,'Arcanine','neutral'),(18,'Ninetales','neutral'),(19,'Luxray','neutral'),(20,'Rillaboom','neutral'),(21,'Charizard','neutral'),(22,'Alomomola','neutral'),(23,'Audino','neutral'),(24,'Chansey','neutral')) v(position,name,colour))
),
(
  current_date + 10, 'gen1',
  '[{"word": "WIELD", "number": 4, "cat": 4, "t": [0, 2, 4, 6]}, {"word": "ARMS", "number": 1, "cat": 2, "t": [8]}, {"word": "POUCH", "number": 1, "cat": 4, "t": [10]}, {"word": "HORN", "number": 2, "cat": 2, "t": [12, 14]}, {"word": "BLADES", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  '[{"word": "SPOON", "number": 1, "cat": 2, "t": [0]}, {"word": "GLOVES", "number": 1, "cat": 2, "t": [2]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [4]}, {"word": "LEEK", "number": 1, "cat": 4, "t": [6]}, {"word": "MUSCLE", "number": 1, "cat": 3, "t": [8]}, {"word": "BABY", "number": 1, "cat": 4, "t": [10]}, {"word": "DRILL", "number": 1, "cat": 2, "t": [12]}, {"word": "SPIKES", "number": 1, "cat": 2, "t": [14]}, {"word": "MANTIS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Alakazam','blue'),(1,'Gengar','neutral'),(2,'Hitmonchan','blue'),(3,'Haunter','neutral'),(4,'Cubone','blue'),(5,'Gastly','neutral'),(6,'Farfetch''d','blue'),(7,'Koffing','neutral'),(8,'Machamp','blue'),(9,'Weezing','neutral'),(10,'Kangaskhan','blue'),(11,'Magneton','neutral'),(12,'Rhydon','blue'),(13,'Electrode','neutral'),(14,'Nidoking','blue'),(15,'Jolteon','neutral'),(16,'Scyther','blue'),(17,'Vaporeon','neutral'),(18,'Flareon','neutral'),(19,'Lapras','neutral'),(20,'Dewgong','neutral'),(21,'Cloyster','neutral'),(22,'Seel','neutral'),(23,'Persian','neutral'),(24,'Meowth','neutral')) v(position,name,colour))
),
(
  current_date + 10, 'mixed',
  '[{"word": "THREE", "number": 4, "cat": 2, "t": [0, 2, 4, 6]}, {"word": "AURA", "number": 1, "cat": 4, "t": [8]}, {"word": "GOWN", "number": 1, "cat": 2, "t": [10]}, {"word": "BLADES", "number": 2, "cat": 2, "t": [12, 14]}, {"word": "FROG", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  '[{"word": "BEAKS", "number": 1, "cat": 2, "t": [0]}, {"word": "BOLTS", "number": 1, "cat": 2, "t": [2]}, {"word": "DIG", "number": 1, "cat": 2, "t": [4]}, {"word": "VIOLENT", "number": 1, "cat": 4, "t": [6]}, {"word": "JACKAL", "number": 1, "cat": 2, "t": [8]}, {"word": "PSYCHIC", "number": 1, "cat": 1, "t": [10]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [12]}, {"word": "SWORD", "number": 1, "cat": 2, "t": [14]}, {"word": "WATER", "number": 1, "cat": 1, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Dodrio','blue'),(1,'Pikachu','neutral'),(2,'Magneton','blue'),(3,'Raichu','neutral'),(4,'Dugtrio','blue'),(5,'Snorlax','neutral'),(6,'Hydreigon','blue'),(7,'Blissey','neutral'),(8,'Lucario','blue'),(9,'Togekiss','neutral'),(10,'Gardevoir','blue'),(11,'Sylveon','neutral'),(12,'Scizor','blue'),(13,'Umbreon','neutral'),(14,'Aegislash','blue'),(15,'Arcanine','neutral'),(16,'Greninja','blue'),(17,'Ninetales','neutral'),(18,'Gengar','neutral'),(19,'Dragonite','neutral'),(20,'Salamence','neutral'),(21,'Tyranitar','neutral'),(22,'Garchomp','neutral'),(23,'Rhyperior','neutral'),(24,'Luxray','neutral')) v(position,name,colour))
),
(
  current_date + 11, 'gen1',
  '[{"word": "FOSSIL", "number": 3, "cat": 4, "t": [0, 2, 4]}, {"word": "SHELL", "number": 2, "cat": 2, "t": [6, 8]}, {"word": "HORN", "number": 2, "cat": 2, "t": [10, 12]}, {"word": "ORPHAN", "number": 1, "cat": 4, "t": [14]}, {"word": "ARMS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  '[{"word": "SICKLE", "number": 1, "cat": 2, "t": [0]}, {"word": "SPIRAL", "number": 1, "cat": 2, "t": [2]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [4]}, {"word": "TURTLE", "number": 1, "cat": 2, "t": [6]}, {"word": "PEARL", "number": 1, "cat": 4, "t": [8]}, {"word": "DRILL", "number": 1, "cat": 2, "t": [10]}, {"word": "BARBS", "number": 1, "cat": 2, "t": [12]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [14]}, {"word": "MUSCLE", "number": 1, "cat": 3, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Kabutops','blue'),(1,'Pikachu','neutral'),(2,'Omastar','blue'),(3,'Raichu','neutral'),(4,'Aerodactyl','blue'),(5,'Meowth','neutral'),(6,'Blastoise','blue'),(7,'Persian','neutral'),(8,'Cloyster','blue'),(9,'Gengar','neutral'),(10,'Rhydon','blue'),(11,'Haunter','neutral'),(12,'Nidoking','blue'),(13,'Koffing','neutral'),(14,'Cubone','blue'),(15,'Weezing','neutral'),(16,'Machamp','blue'),(17,'Vulpix','neutral'),(18,'Ninetales','neutral'),(19,'Growlithe','neutral'),(20,'Arcanine','neutral'),(21,'Jolteon','neutral'),(22,'Vaporeon','neutral'),(23,'Snorlax','neutral'),(24,'Electabuzz','neutral')) v(position,name,colour))
),
(
  current_date + 11, 'mixed',
  '[{"word": "PSEUDO", "number": 3, "cat": 5, "t": [0, 2, 4]}, {"word": "HEADS", "number": 1, "cat": 2, "t": [6]}, {"word": "AURA", "number": 1, "cat": 4, "t": [8]}, {"word": "GOWN", "number": 1, "cat": 2, "t": [10]}, {"word": "SWORDS", "number": 3, "cat": 2, "t": [12, 14, 16]}]'::jsonb,
  '[{"word": "FINS", "number": 1, "cat": 2, "t": [0]}, {"word": "ROBOT", "number": 1, "cat": 3, "t": [2]}, {"word": "RAMPAGE", "number": 1, "cat": 4, "t": [4]}, {"word": "VIOLENT", "number": 1, "cat": 4, "t": [6]}, {"word": "JACKAL", "number": 1, "cat": 2, "t": [8]}, {"word": "DANCER", "number": 1, "cat": 3, "t": [10]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [12]}, {"word": "SWORD", "number": 1, "cat": 2, "t": [14]}, {"word": "ELBOWS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Garchomp','blue'),(1,'Pikachu','neutral'),(2,'Metagross','blue'),(3,'Raichu','neutral'),(4,'Tyranitar','blue'),(5,'Snorlax','neutral'),(6,'Hydreigon','blue'),(7,'Blissey','neutral'),(8,'Lucario','blue'),(9,'Chansey','neutral'),(10,'Gardevoir','blue'),(11,'Audino','neutral'),(12,'Scizor','blue'),(13,'Togekiss','neutral'),(14,'Aegislash','blue'),(15,'Sylveon','neutral'),(16,'Gallade','blue'),(17,'Umbreon','neutral'),(18,'Espeon','neutral'),(19,'Arcanine','neutral'),(20,'Ninetales','neutral'),(21,'Gengar','neutral'),(22,'Lapras','neutral'),(23,'Charizard','neutral'),(24,'Rillaboom','neutral')) v(position,name,colour))
),
(
  current_date + 12, 'gen1',
  '[{"word": "FOSSIL", "number": 3, "cat": 4, "t": [0, 2, 4]}, {"word": "MORPH", "number": 1, "cat": 5, "t": [6]}, {"word": "HORN", "number": 2, "cat": 2, "t": [8, 10]}, {"word": "SPOONS", "number": 2, "cat": 2, "t": [12, 14]}, {"word": "ORPHAN", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  '[{"word": "SICKLE", "number": 1, "cat": 2, "t": [0]}, {"word": "SPIRAL", "number": 1, "cat": 2, "t": [2]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [4]}, {"word": "COPY", "number": 1, "cat": 4, "t": [6]}, {"word": "DRILL", "number": 1, "cat": 2, "t": [8]}, {"word": "BARBS", "number": 1, "cat": 2, "t": [10]}, {"word": "SMART", "number": 1, "cat": 4, "t": [12]}, {"word": "PSYCHIC", "number": 1, "cat": 1, "t": [14]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Kabutops','blue'),(1,'Pikachu','neutral'),(2,'Omastar','blue'),(3,'Raichu','neutral'),(4,'Aerodactyl','blue'),(5,'Gengar','neutral'),(6,'Ditto','blue'),(7,'Haunter','neutral'),(8,'Rhydon','blue'),(9,'Gastly','neutral'),(10,'Nidoking','blue'),(11,'Koffing','neutral'),(12,'Alakazam','blue'),(13,'Weezing','neutral'),(14,'Kadabra','blue'),(15,'Grimer','neutral'),(16,'Cubone','blue'),(17,'Muk','neutral'),(18,'Machamp','neutral'),(19,'Machoke','neutral'),(20,'Snorlax','neutral'),(21,'Lapras','neutral'),(22,'Dewgong','neutral'),(23,'Persian','neutral'),(24,'Meowth','neutral')) v(position,name,colour))
),
(
  current_date + 12, 'mixed',
  '[{"word": "STARTER", "number": 3, "cat": 5, "t": [0, 2, 4]}, {"word": "SLEEP", "number": 2, "cat": 3, "t": [6, 8]}, {"word": "GRIN", "number": 1, "cat": 3, "t": [10]}, {"word": "MASCOT", "number": 1, "cat": 4, "t": [12]}, {"word": "SERPENT", "number": 2, "cat": 3, "t": [14, 16]}]'::jsonb,
  '[{"word": "FLOWER", "number": 1, "cat": 2, "t": [0]}, {"word": "CANNON", "number": 1, "cat": 2, "t": [2]}, {"word": "FLAME", "number": 1, "cat": 2, "t": [4]}, {"word": "BELLY", "number": 1, "cat": 3, "t": [6]}, {"word": "PENDULUM", "number": 1, "cat": 4, "t": [8]}, {"word": "PURPLE", "number": 1, "cat": 1, "t": [10]}, {"word": "CHEEKS", "number": 1, "cat": 2, "t": [12]}, {"word": "FURY", "number": 1, "cat": 4, "t": [14]}, {"word": "ROCKS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Venusaur','blue'),(1,'Raichu','neutral'),(2,'Blastoise','blue'),(3,'Meowth','neutral'),(4,'Charizard','blue'),(5,'Persian','neutral'),(6,'Snorlax','blue'),(7,'Weezing','neutral'),(8,'Hypno','blue'),(9,'Kingler','neutral'),(10,'Gengar','blue'),(11,'Electabuzz','neutral'),(12,'Pikachu','blue'),(13,'Dewgong','neutral'),(14,'Gyarados','blue'),(15,'Seaking','neutral'),(16,'Onix','blue'),(17,'Vaporeon','neutral'),(18,'Jolteon','neutral'),(19,'Golduck','neutral'),(20,'Ampharos','neutral'),(21,'Dragonite','neutral'),(22,'Metagross','neutral'),(23,'Blissey','neutral'),(24,'Chansey','neutral')) v(position,name,colour))
),
(
  current_date + 13, 'gen1',
  '[{"word": "FOSSIL", "number": 3, "cat": 4, "t": [0, 2, 4]}, {"word": "MORPH", "number": 1, "cat": 5, "t": [6]}, {"word": "PIXEL", "number": 1, "cat": 4, "t": [8]}, {"word": "WIELD", "number": 2, "cat": 4, "t": [10, 12]}, {"word": "RIVALS", "number": 2, "cat": 4, "t": [14, 16]}]'::jsonb,
  '[{"word": "SICKLE", "number": 1, "cat": 2, "t": [0]}, {"word": "SPIRAL", "number": 1, "cat": 2, "t": [2]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [4]}, {"word": "COPY", "number": 1, "cat": 4, "t": [6]}, {"word": "DIGITAL", "number": 1, "cat": 4, "t": [8]}, {"word": "PSYCHIC", "number": 1, "cat": 1, "t": [10]}, {"word": "SKULL", "number": 1, "cat": 2, "t": [12]}, {"word": "PLUG", "number": 1, "cat": 2, "t": [14]}, {"word": "FLAME", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Kabutops','blue'),(1,'Pikachu','neutral'),(2,'Omastar','blue'),(3,'Raichu','neutral'),(4,'Aerodactyl','blue'),(5,'Gengar','neutral'),(6,'Ditto','blue'),(7,'Haunter','neutral'),(8,'Porygon','blue'),(9,'Gastly','neutral'),(10,'Alakazam','blue'),(11,'Koffing','neutral'),(12,'Cubone','blue'),(13,'Weezing','neutral'),(14,'Electabuzz','blue'),(15,'Grimer','neutral'),(16,'Magmar','blue'),(17,'Muk','neutral'),(18,'Machamp','neutral'),(19,'Snorlax','neutral'),(20,'Lapras','neutral'),(21,'Dewgong','neutral'),(22,'Cloyster','neutral'),(23,'Persian','neutral'),(24,'Meowth','neutral')) v(position,name,colour))
),
(
  current_date + 13, 'mixed',
  '[{"word": "PSEUDO", "number": 3, "cat": 5, "t": [0, 2, 4]}, {"word": "FOSSIL", "number": 2, "cat": 4, "t": [6, 8]}, {"word": "TRICKSTER", "number": 2, "cat": 5, "t": [10, 12]}, {"word": "NIGHTMARE", "number": 1, "cat": 4, "t": [14]}, {"word": "THIEF", "number": 1, "cat": 4, "t": [16]}]'::jsonb,
  '[{"word": "FINS", "number": 1, "cat": 2, "t": [0]}, {"word": "CRESCENT", "number": 1, "cat": 2, "t": [2]}, {"word": "VIOLENT", "number": 1, "cat": 4, "t": [4]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [6]}, {"word": "JAWS", "number": 1, "cat": 2, "t": [8]}, {"word": "FOX", "number": 1, "cat": 2, "t": [10]}, {"word": "CLOTH", "number": 1, "cat": 3, "t": [12]}, {"word": "GRIN", "number": 1, "cat": 3, "t": [14]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
  (select jsonb_agg(jsonb_build_object('position',v.position,'name',v.name,'colour',v.colour) order by v.position)
   from (values (0,'Garchomp','blue'),(1,'Pikachu','neutral'),(2,'Salamence','blue'),(3,'Raichu','neutral'),(4,'Hydreigon','blue'),(5,'Snorlax','neutral'),(6,'Aerodactyl','blue'),(7,'Blissey','neutral'),(8,'Tyrantrum','blue'),(9,'Chansey','neutral'),(10,'Zoroark','blue'),(11,'Audino','neutral'),(12,'Mimikyu','blue'),(13,'Togekiss','neutral'),(14,'Gengar','blue'),(15,'Sylveon','neutral'),(16,'Weavile','blue'),(17,'Umbreon','neutral'),(18,'Espeon','neutral'),(19,'Lucario','neutral'),(20,'Gardevoir','neutral'),(21,'Arcanine','neutral'),(22,'Ninetales','neutral'),(23,'Rillaboom','neutral'),(24,'Luxray','neutral')) v(position,name,colour))
)
on conflict (puzzle_date, pool) do update
  set clues = excluded.clues, hints = excluded.hints, tiles = excluded.tiles;
