-- 29_updates.sql
--
-- Daily puzzles for 2026-08-22 .. 2026-08-30 (blues-first method, per new spec):
--   weekday ramp Sat/Sun weekend Brutal/Evil, Mon..Fri Easy/Medium/Challenging/Hard/Hard.
--   9 blue + 16 neutral, 5 base clues (cat-tagged, overlaps on Brutal/Evil to meet the
--   sum>=11 gate), one conditional hint per blue, tile positions + clue order shuffled.
--   All boards pass: strict 3-letter rule, full coverage, mix table, Brutal/Evil gate,
--   and anti-repetition (14-day word->group, 7-day word) vs every puzzle Aug 2..Aug 21.
-- PLUS a core-rule fix to the existing 2026-08-17 mixed board: its WATER clue also
--   matched the neutral Alomomola (a Water-type), an unavoidable strike. Swapped that
--   one neutral tile for Ampharos (electric); nothing else on that board changes.

insert into public.daily_puzzles (puzzle_date, pool, clues, hints, tiles) values
  ('2026-08-22', 'gen1',
   '[{"word": "PINCER", "number": 2, "cat": 4, "t": [20, 24]}, {"word": "CLUB", "number": 1, "cat": 2, "t": [3]}, {"word": "PRIMATE", "number": 3, "cat": 4, "t": [12, 21, 23]}, {"word": "JAB", "number": 2, "cat": 3, "t": [1, 23]}, {"word": "EARTHQUAKE", "number": 3, "cat": 4, "t": [3, 11, 15]}]'::jsonb,
   '[{"word": "BIG-CLAW", "number": 1, "cat": 2, "t": [20]}, {"word": "PINCERS", "number": 1, "cat": 2, "t": [24]}, {"word": "BELT", "number": 1, "cat": 2, "t": [21]}, {"word": "BOULDER", "number": 1, "cat": 2, "t": [15]}, {"word": "DRILL-HORN", "number": 1, "cat": 2, "t": [11]}, {"word": "GLOVES", "number": 1, "cat": 2, "t": [1]}, {"word": "BONE-CLUB", "number": 1, "cat": 2, "t": [3]}, {"word": "ANGRY", "number": 1, "cat": 3, "t": [12]}, {"word": "FOUR-ARMS", "number": 1, "cat": 2, "t": [23]}]'::jsonb,
   '[{"name": "Magneton", "colour": "neutral", "position": 0}, {"name": "Hitmonchan", "colour": "blue", "position": 1}, {"name": "Electrode", "colour": "neutral", "position": 2}, {"name": "Marowak", "colour": "blue", "position": 3}, {"name": "Scyther", "colour": "neutral", "position": 4}, {"name": "Metapod", "colour": "neutral", "position": 5}, {"name": "Growlithe", "colour": "neutral", "position": 6}, {"name": "Abra", "colour": "neutral", "position": 7}, {"name": "Cloyster", "colour": "neutral", "position": 8}, {"name": "Venusaur", "colour": "neutral", "position": 9}, {"name": "Voltorb", "colour": "neutral", "position": 10}, {"name": "Rhydon", "colour": "blue", "position": 11}, {"name": "Mankey", "colour": "blue", "position": 12}, {"name": "Vileplume", "colour": "neutral", "position": 13}, {"name": "Alakazam", "colour": "neutral", "position": 14}, {"name": "Golem", "colour": "blue", "position": 15}, {"name": "Dragonair", "colour": "neutral", "position": 16}, {"name": "Lickitung", "colour": "neutral", "position": 17}, {"name": "Jigglypuff", "colour": "neutral", "position": 18}, {"name": "Tentacool", "colour": "neutral", "position": 19}, {"name": "Kingler", "colour": "blue", "position": 20}, {"name": "Machoke", "colour": "blue", "position": 21}, {"name": "Staryu", "colour": "neutral", "position": 22}, {"name": "Machamp", "colour": "blue", "position": 23}, {"name": "Krabby", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-08-22', 'mixed',
   '[{"word": "MUSTELID", "number": 2, "cat": 4, "t": [11, 22]}, {"word": "INTIMIDATE", "number": 3, "cat": 5, "t": [2, 5, 12]}, {"word": "REVIVED", "number": 2, "cat": 4, "t": [3, 20]}, {"word": "BLADE", "number": 2, "cat": 2, "t": [1, 7]}, {"word": "HOUND", "number": 2, "cat": 3, "t": [2, 11]}]'::jsonb,
   '[{"word": "KING-JAW", "number": 1, "cat": 2, "t": [20]}, {"word": "MANE", "number": 1, "cat": 2, "t": [5]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [22]}, {"word": "PONYTAIL", "number": 1, "cat": 2, "t": [11]}, {"word": "RED-CLAWS", "number": 1, "cat": 2, "t": [7]}, {"word": "CRESCENT", "number": 1, "cat": 2, "t": [12]}, {"word": "STRIPED", "number": 1, "cat": 2, "t": [2]}, {"word": "BLADES", "number": 1, "cat": 2, "t": [1]}, {"word": "ROCK-WINGS", "number": 1, "cat": 2, "t": [3]}]'::jsonb,
   '[{"name": "Kakuna", "colour": "neutral", "position": 0}, {"name": "Bisharp", "colour": "blue", "position": 1}, {"name": "Arcanine", "colour": "blue", "position": 2}, {"name": "Aerodactyl", "colour": "blue", "position": 3}, {"name": "Sandslash", "colour": "neutral", "position": 4}, {"name": "Luxray", "colour": "blue", "position": 5}, {"name": "Grimer", "colour": "neutral", "position": 6}, {"name": "Scizor", "colour": "blue", "position": 7}, {"name": "Frosmoth", "colour": "neutral", "position": 8}, {"name": "Sandshrew", "colour": "neutral", "position": 9}, {"name": "Parasect", "colour": "neutral", "position": 10}, {"name": "Zoroark", "colour": "blue", "position": 11}, {"name": "Salamence", "colour": "blue", "position": 12}, {"name": "Charizard", "colour": "neutral", "position": 13}, {"name": "Jynx", "colour": "neutral", "position": 14}, {"name": "Haxorus", "colour": "neutral", "position": 15}, {"name": "Empoleon", "colour": "neutral", "position": 16}, {"name": "Dodrio", "colour": "neutral", "position": 17}, {"name": "Scyther", "colour": "neutral", "position": 18}, {"name": "Lickitung", "colour": "neutral", "position": 19}, {"name": "Tyrantrum", "colour": "blue", "position": 20}, {"name": "Metagross", "colour": "neutral", "position": 21}, {"name": "Weavile", "colour": "blue", "position": 22}, {"name": "Leafeon", "colour": "neutral", "position": 23}, {"name": "Electabuzz", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-23', 'gen1',
   '[{"word": "MARSUPIAL", "number": 1, "cat": 4, "t": [17]}, {"word": "BRUISER", "number": 2, "cat": 5, "t": [2, 10]}, {"word": "BOXER", "number": 2, "cat": 3, "t": [2, 20]}, {"word": "EXTINCT", "number": 4, "cat": 4, "t": [3, 14, 19, 22]}, {"word": "MOLLUSC", "number": 2, "cat": 4, "t": [4, 14]}]'::jsonb,
   '[{"word": "FOUR-ARMS", "number": 1, "cat": 2, "t": [2]}, {"word": "SPIRAL", "number": 1, "cat": 2, "t": [14]}, {"word": "DOME", "number": 1, "cat": 2, "t": [3]}, {"word": "POUCH", "number": 1, "cat": 2, "t": [17]}, {"word": "BELT", "number": 1, "cat": 2, "t": [10]}, {"word": "GLOVES", "number": 1, "cat": 2, "t": [20]}, {"word": "SCYTHE-ARMS", "number": 1, "cat": 2, "t": [22]}, {"word": "ROCK-WINGS", "number": 1, "cat": 2, "t": [19]}, {"word": "PEARL", "number": 1, "cat": 2, "t": [4]}]'::jsonb,
   '[{"name": "Mankey", "colour": "neutral", "position": 0}, {"name": "Weedle", "colour": "neutral", "position": 1}, {"name": "Machamp", "colour": "blue", "position": 2}, {"name": "Kabuto", "colour": "blue", "position": 3}, {"name": "Cloyster", "colour": "blue", "position": 4}, {"name": "Tauros", "colour": "neutral", "position": 5}, {"name": "Wigglytuff", "colour": "neutral", "position": 6}, {"name": "Ponyta", "colour": "neutral", "position": 7}, {"name": "Vileplume", "colour": "neutral", "position": 8}, {"name": "Kadabra", "colour": "neutral", "position": 9}, {"name": "Machoke", "colour": "blue", "position": 10}, {"name": "Gengar", "colour": "neutral", "position": 11}, {"name": "Lapras", "colour": "neutral", "position": 12}, {"name": "Clefable", "colour": "neutral", "position": 13}, {"name": "Omastar", "colour": "blue", "position": 14}, {"name": "Onix", "colour": "neutral", "position": 15}, {"name": "Zubat", "colour": "neutral", "position": 16}, {"name": "Kangaskhan", "colour": "blue", "position": 17}, {"name": "Drowzee", "colour": "neutral", "position": 18}, {"name": "Aerodactyl", "colour": "blue", "position": 19}, {"name": "Hitmonchan", "colour": "blue", "position": 20}, {"name": "Cubone", "colour": "neutral", "position": 21}, {"name": "Kabutops", "colour": "blue", "position": 22}, {"name": "Golbat", "colour": "neutral", "position": 23}, {"name": "Gastly", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-23', 'mixed',
   '[{"word": "WRAITH", "number": 2, "cat": 3, "t": [18, 20]}, {"word": "OMEN", "number": 2, "cat": 5, "t": [11, 20]}, {"word": "KIMONO", "number": 2, "cat": 4, "t": [15, 23]}, {"word": "SQUID", "number": 3, "cat": 4, "t": [1, 8, 10]}, {"word": "LEVITATE", "number": 2, "cat": 5, "t": [0, 18]}]'::jsonb,
   '[{"word": "GEMSTONE", "number": 1, "cat": 2, "t": [11]}, {"word": "SUCKERS", "number": 1, "cat": 2, "t": [1]}, {"word": "KIMONO", "number": 1, "cat": 2, "t": [15]}, {"word": "SQUID", "number": 1, "cat": 3, "t": [10]}, {"word": "SUCKERS", "number": 1, "cat": 2, "t": [8]}, {"word": "HAT", "number": 1, "cat": 2, "t": [18]}, {"word": "LANTERN", "number": 1, "cat": 2, "t": [0]}, {"word": "KEYSTONE", "number": 1, "cat": 2, "t": [20]}, {"word": "RAG", "number": 1, "cat": 2, "t": [23]}]'::jsonb,
   '[{"name": "Chandelure", "colour": "blue", "position": 0}, {"name": "Octillery", "colour": "blue", "position": 1}, {"name": "Pidgeotto", "colour": "neutral", "position": 2}, {"name": "Staraptor", "colour": "neutral", "position": 3}, {"name": "Lapras", "colour": "neutral", "position": 4}, {"name": "Wigglytuff", "colour": "neutral", "position": 5}, {"name": "Ursaring", "colour": "neutral", "position": 6}, {"name": "Parasect", "colour": "neutral", "position": 7}, {"name": "Grapploct", "colour": "blue", "position": 8}, {"name": "Weedle", "colour": "neutral", "position": 9}, {"name": "Malamar", "colour": "blue", "position": 10}, {"name": "Sableye", "colour": "blue", "position": 11}, {"name": "Arcanine", "colour": "neutral", "position": 12}, {"name": "Mudsdale", "colour": "neutral", "position": 13}, {"name": "Kangaskhan", "colour": "neutral", "position": 14}, {"name": "Froslass", "colour": "blue", "position": 15}, {"name": "Exeggcute", "colour": "neutral", "position": 16}, {"name": "Ponyta", "colour": "neutral", "position": 17}, {"name": "Mismagius", "colour": "blue", "position": 18}, {"name": "Victreebel", "colour": "neutral", "position": 19}, {"name": "Spiritomb", "colour": "blue", "position": 20}, {"name": "Snorlax", "colour": "neutral", "position": 21}, {"name": "Porygon", "colour": "neutral", "position": 22}, {"name": "Mimikyu", "colour": "blue", "position": 23}, {"name": "Dodrio", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-24', 'gen1',
   '[{"word": "BALLOON", "number": 1, "cat": 2, "t": [3]}, {"word": "SLURP", "number": 1, "cat": 2, "t": [7]}, {"word": "ROCK", "number": 2, "cat": 1, "t": [6, 8]}, {"word": "POISON", "number": 3, "cat": 1, "t": [2, 14, 20]}, {"word": "GHOST", "number": 2, "cat": 1, "t": [15, 24]}]'::jsonb,
   '[{"word": "SLUDGE", "number": 1, "cat": 2, "t": [20]}, {"word": "OOZE", "number": 1, "cat": 2, "t": [14]}, {"word": "ROUND", "number": 1, "cat": 2, "t": [3]}, {"word": "TONGUE", "number": 1, "cat": 2, "t": [7]}, {"word": "HANDS", "number": 1, "cat": 2, "t": [15]}, {"word": "FISTS", "number": 1, "cat": 2, "t": [8]}, {"word": "ROCK-SNAKE", "number": 1, "cat": 3, "t": [6]}, {"word": "VAPOUR", "number": 1, "cat": 2, "t": [24]}, {"word": "FUMES", "number": 1, "cat": 2, "t": [2]}]'::jsonb,
   '[{"name": "Scyther", "colour": "neutral", "position": 0}, {"name": "Aerodactyl", "colour": "neutral", "position": 1}, {"name": "Koffing", "colour": "blue", "position": 2}, {"name": "Jigglypuff", "colour": "blue", "position": 3}, {"name": "Tauros", "colour": "neutral", "position": 4}, {"name": "Flareon", "colour": "neutral", "position": 5}, {"name": "Onix", "colour": "blue", "position": 6}, {"name": "Lickitung", "colour": "blue", "position": 7}, {"name": "Geodude", "colour": "blue", "position": 8}, {"name": "Diglett", "colour": "neutral", "position": 9}, {"name": "Mr. Mime", "colour": "neutral", "position": 10}, {"name": "Vulpix", "colour": "neutral", "position": 11}, {"name": "Rattata", "colour": "neutral", "position": 12}, {"name": "Kadabra", "colour": "neutral", "position": 13}, {"name": "Grimer", "colour": "blue", "position": 14}, {"name": "Haunter", "colour": "blue", "position": 15}, {"name": "Pinsir", "colour": "neutral", "position": 16}, {"name": "Shellder", "colour": "neutral", "position": 17}, {"name": "Exeggutor", "colour": "neutral", "position": 18}, {"name": "Golduck", "colour": "neutral", "position": 19}, {"name": "Muk", "colour": "blue", "position": 20}, {"name": "Dugtrio", "colour": "neutral", "position": 21}, {"name": "Weedle", "colour": "neutral", "position": 22}, {"name": "Clefable", "colour": "neutral", "position": 23}, {"name": "Gastly", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-08-24', 'mixed',
   '[{"word": "STEEL", "number": 2, "cat": 1, "t": [1, 8]}, {"word": "SLIME", "number": 1, "cat": 2, "t": [0]}, {"word": "WHALE", "number": 1, "cat": 2, "t": [23]}, {"word": "ICE", "number": 2, "cat": 1, "t": [17, 20]}, {"word": "GRASS", "number": 3, "cat": 1, "t": [6, 12, 16]}]'::jsonb,
   '[{"word": "SLIME", "number": 1, "cat": 2, "t": [0]}, {"word": "SPROUT", "number": 1, "cat": 2, "t": [12]}, {"word": "ICE-WINGS", "number": 1, "cat": 2, "t": [17]}, {"word": "WHALE", "number": 1, "cat": 3, "t": [23]}, {"word": "POLAR", "number": 1, "cat": 2, "t": [20]}, {"word": "GECKO", "number": 1, "cat": 2, "t": [16]}, {"word": "HILT", "number": 1, "cat": 2, "t": [1]}, {"word": "BOUQUET", "number": 1, "cat": 2, "t": [6]}, {"word": "RED-CLAWS", "number": 1, "cat": 2, "t": [8]}]'::jsonb,
   '[{"name": "Goodra", "colour": "blue", "position": 0}, {"name": "Aegislash", "colour": "blue", "position": 1}, {"name": "Hypno", "colour": "neutral", "position": 2}, {"name": "Farfetch''d", "colour": "neutral", "position": 3}, {"name": "Lucario", "colour": "neutral", "position": 4}, {"name": "Hydreigon", "colour": "neutral", "position": 5}, {"name": "Roserade", "colour": "blue", "position": 6}, {"name": "Articuno", "colour": "neutral", "position": 7}, {"name": "Scizor", "colour": "blue", "position": 8}, {"name": "Mismagius", "colour": "neutral", "position": 9}, {"name": "Tentacool", "colour": "neutral", "position": 10}, {"name": "Togekiss", "colour": "neutral", "position": 11}, {"name": "Leafeon", "colour": "blue", "position": 12}, {"name": "Swampert", "colour": "neutral", "position": 13}, {"name": "Machamp", "colour": "neutral", "position": 14}, {"name": "Audino", "colour": "neutral", "position": 15}, {"name": "Sceptile", "colour": "blue", "position": 16}, {"name": "Frosmoth", "colour": "blue", "position": 17}, {"name": "Umbreon", "colour": "neutral", "position": 18}, {"name": "Chansey", "colour": "neutral", "position": 19}, {"name": "Beartic", "colour": "blue", "position": 20}, {"name": "Fearow", "colour": "neutral", "position": 21}, {"name": "Tauros", "colour": "neutral", "position": 22}, {"name": "Wailord", "colour": "blue", "position": 23}, {"name": "Clefable", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-25', 'gen1',
   '[{"word": "DIGGER", "number": 2, "cat": 3, "t": [0, 8]}, {"word": "SPOON", "number": 2, "cat": 2, "t": [6, 13]}, {"word": "FIRE", "number": 2, "cat": 1, "t": [11, 19]}, {"word": "WATER", "number": 2, "cat": 1, "t": [3, 17]}, {"word": "BARRIER", "number": 1, "cat": 4, "t": [22]}]'::jsonb,
   '[{"word": "SPOON", "number": 1, "cat": 2, "t": [13]}, {"word": "SNOUT", "number": 1, "cat": 2, "t": [17]}, {"word": "CURLED", "number": 1, "cat": 2, "t": [8]}, {"word": "SWIRL", "number": 1, "cat": 2, "t": [3]}, {"word": "SPOON", "number": 1, "cat": 2, "t": [6]}, {"word": "PANES", "number": 1, "cat": 2, "t": [22]}, {"word": "PUP", "number": 1, "cat": 2, "t": [11]}, {"word": "MOLES", "number": 1, "cat": 2, "t": [0]}, {"word": "CURLS", "number": 1, "cat": 2, "t": [19]}]'::jsonb,
   '[{"name": "Dugtrio", "colour": "blue", "position": 0}, {"name": "Chansey", "colour": "neutral", "position": 1}, {"name": "Grimer", "colour": "neutral", "position": 2}, {"name": "Poliwag", "colour": "blue", "position": 3}, {"name": "Ekans", "colour": "neutral", "position": 4}, {"name": "Exeggutor", "colour": "neutral", "position": 5}, {"name": "Kadabra", "colour": "blue", "position": 6}, {"name": "Persian", "colour": "neutral", "position": 7}, {"name": "Sandshrew", "colour": "blue", "position": 8}, {"name": "Metapod", "colour": "neutral", "position": 9}, {"name": "Victreebel", "colour": "neutral", "position": 10}, {"name": "Growlithe", "colour": "blue", "position": 11}, {"name": "Fearow", "colour": "neutral", "position": 12}, {"name": "Alakazam", "colour": "blue", "position": 13}, {"name": "Weedle", "colour": "neutral", "position": 14}, {"name": "Lickitung", "colour": "neutral", "position": 15}, {"name": "Hitmonlee", "colour": "neutral", "position": 16}, {"name": "Horsea", "colour": "blue", "position": 17}, {"name": "Zubat", "colour": "neutral", "position": 18}, {"name": "Vulpix", "colour": "blue", "position": 19}, {"name": "Dewgong", "colour": "neutral", "position": 20}, {"name": "Beedrill", "colour": "neutral", "position": 21}, {"name": "Mr. Mime", "colour": "blue", "position": 22}, {"name": "Kakuna", "colour": "neutral", "position": 23}, {"name": "Omanyte", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-25', 'mixed',
   '[{"word": "EEVEE", "number": 3, "cat": 3, "t": [1, 4, 14]}, {"word": "DRAGON", "number": 3, "cat": 1, "t": [0, 18, 21]}, {"word": "GEMS", "number": 1, "cat": 2, "t": [15]}, {"word": "BOWS", "number": 1, "cat": 2, "t": [14]}, {"word": "PSYCHIC", "number": 2, "cat": 1, "t": [3, 17]}]'::jsonb,
   '[{"word": "GOWN", "number": 1, "cat": 2, "t": [3]}, {"word": "GEMSTONE", "number": 1, "cat": 2, "t": [15]}, {"word": "AXE-JAW", "number": 1, "cat": 2, "t": [21]}, {"word": "FOREHEAD", "number": 1, "cat": 2, "t": [4]}, {"word": "LEGS", "number": 1, "cat": 2, "t": [17]}, {"word": "BOWS", "number": 1, "cat": 2, "t": [14]}, {"word": "RINGS", "number": 1, "cat": 2, "t": [1]}, {"word": "CRESCENT", "number": 1, "cat": 2, "t": [0]}, {"word": "FINS", "number": 1, "cat": 2, "t": [18]}]'::jsonb,
   '[{"name": "Salamence", "colour": "blue", "position": 0}, {"name": "Umbreon", "colour": "blue", "position": 1}, {"name": "Wigglytuff", "colour": "neutral", "position": 2}, {"name": "Gardevoir", "colour": "blue", "position": 3}, {"name": "Espeon", "colour": "blue", "position": 4}, {"name": "Lucario", "colour": "neutral", "position": 5}, {"name": "Kakuna", "colour": "neutral", "position": 6}, {"name": "Ponyta", "colour": "neutral", "position": 7}, {"name": "Seel", "colour": "neutral", "position": 8}, {"name": "Froslass", "colour": "neutral", "position": 9}, {"name": "Vileplume", "colour": "neutral", "position": 10}, {"name": "Victreebel", "colour": "neutral", "position": 11}, {"name": "Vulpix", "colour": "neutral", "position": 12}, {"name": "Mimikyu", "colour": "neutral", "position": 13}, {"name": "Sylveon", "colour": "blue", "position": 14}, {"name": "Sableye", "colour": "blue", "position": 15}, {"name": "Geodude", "colour": "neutral", "position": 16}, {"name": "Metagross", "colour": "blue", "position": 17}, {"name": "Garchomp", "colour": "blue", "position": 18}, {"name": "Jigglypuff", "colour": "neutral", "position": 19}, {"name": "Gyarados", "colour": "neutral", "position": 20}, {"name": "Haxorus", "colour": "blue", "position": 21}, {"name": "Lickitung", "colour": "neutral", "position": 22}, {"name": "Corviknight", "colour": "neutral", "position": 23}, {"name": "Horsea", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-26', 'gen1',
   '[{"word": "ELECTRIC", "number": 2, "cat": 1, "t": [2, 13]}, {"word": "FANGS", "number": 2, "cat": 2, "t": [3, 21]}, {"word": "EQUINE", "number": 2, "cat": 3, "t": [0, 15]}, {"word": "MIRAGE", "number": 1, "cat": 4, "t": [16]}, {"word": "FELINE", "number": 2, "cat": 3, "t": [6, 11]}]'::jsonb,
   '[{"word": "MANE-FIRE", "number": 1, "cat": 2, "t": [0]}, {"word": "COIN", "number": 1, "cat": 2, "t": [11]}, {"word": "BLAZE-MANE", "number": 1, "cat": 2, "t": [15]}, {"word": "GEM", "number": 1, "cat": 2, "t": [6]}, {"word": "BIG-FANGS", "number": 1, "cat": 2, "t": [21]}, {"word": "BALL", "number": 1, "cat": 3, "t": [13]}, {"word": "PENDULUM", "number": 1, "cat": 2, "t": [16]}, {"word": "HOOD", "number": 1, "cat": 2, "t": [3]}, {"word": "SCREW", "number": 1, "cat": 2, "t": [2]}]'::jsonb,
   '[{"name": "Ponyta", "colour": "blue", "position": 0}, {"name": "Venusaur", "colour": "neutral", "position": 1}, {"name": "Magnemite", "colour": "blue", "position": 2}, {"name": "Arbok", "colour": "blue", "position": 3}, {"name": "Vaporeon", "colour": "neutral", "position": 4}, {"name": "Snorlax", "colour": "neutral", "position": 5}, {"name": "Persian", "colour": "blue", "position": 6}, {"name": "Scyther", "colour": "neutral", "position": 7}, {"name": "Gengar", "colour": "neutral", "position": 8}, {"name": "Pidgeotto", "colour": "neutral", "position": 9}, {"name": "Hitmonlee", "colour": "neutral", "position": 10}, {"name": "Meowth", "colour": "blue", "position": 11}, {"name": "Weedle", "colour": "neutral", "position": 12}, {"name": "Voltorb", "colour": "blue", "position": 13}, {"name": "Pinsir", "colour": "neutral", "position": 14}, {"name": "Rapidash", "colour": "blue", "position": 15}, {"name": "Hypno", "colour": "blue", "position": 16}, {"name": "Rhydon", "colour": "neutral", "position": 17}, {"name": "Machop", "colour": "neutral", "position": 18}, {"name": "Hitmonchan", "colour": "neutral", "position": 19}, {"name": "Dodrio", "colour": "neutral", "position": 20}, {"name": "Golbat", "colour": "blue", "position": 21}, {"name": "Kabutops", "colour": "neutral", "position": 22}, {"name": "Mr. Mime", "colour": "neutral", "position": 23}, {"name": "Exeggutor", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-26', 'mixed',
   '[{"word": "RIBBON", "number": 1, "cat": 2, "t": [11]}, {"word": "FAIRY", "number": 2, "cat": 1, "t": [9, 20]}, {"word": "LYNX", "number": 2, "cat": 3, "t": [14, 23]}, {"word": "FOX", "number": 2, "cat": 3, "t": [1, 22]}, {"word": "MEGA", "number": 2, "cat": 5, "t": [8, 18]}]'::jsonb,
   '[{"word": "CRESCENT", "number": 1, "cat": 2, "t": [18]}, {"word": "MANE", "number": 1, "cat": 2, "t": [23]}, {"word": "RIBBON", "number": 1, "cat": 2, "t": [11]}, {"word": "BLOSSOM", "number": 1, "cat": 2, "t": [20]}, {"word": "SLEEK-CAT", "number": 1, "cat": 2, "t": [14]}, {"word": "EGG-WINGS", "number": 1, "cat": 2, "t": [9]}, {"word": "PONYTAIL", "number": 1, "cat": 2, "t": [1]}, {"word": "FINS", "number": 1, "cat": 2, "t": [8]}, {"word": "CURLS", "number": 1, "cat": 2, "t": [22]}]'::jsonb,
   '[{"name": "Gengar", "colour": "neutral", "position": 0}, {"name": "Zoroark", "colour": "blue", "position": 1}, {"name": "Espeon", "colour": "neutral", "position": 2}, {"name": "Cloyster", "colour": "neutral", "position": 3}, {"name": "Blaziken", "colour": "neutral", "position": 4}, {"name": "Kartana", "colour": "neutral", "position": 5}, {"name": "Kadabra", "colour": "neutral", "position": 6}, {"name": "Onix", "colour": "neutral", "position": 7}, {"name": "Garchomp", "colour": "blue", "position": 8}, {"name": "Togekiss", "colour": "blue", "position": 9}, {"name": "Chansey", "colour": "neutral", "position": 10}, {"name": "Milotic", "colour": "blue", "position": 11}, {"name": "Swampert", "colour": "neutral", "position": 12}, {"name": "Feraligatr", "colour": "neutral", "position": 13}, {"name": "Liepard", "colour": "blue", "position": 14}, {"name": "Hydreigon", "colour": "neutral", "position": 15}, {"name": "Empoleon", "colour": "neutral", "position": 16}, {"name": "Squirtle", "colour": "neutral", "position": 17}, {"name": "Salamence", "colour": "blue", "position": 18}, {"name": "Flygon", "colour": "neutral", "position": 19}, {"name": "Florges", "colour": "blue", "position": 20}, {"name": "Goodra", "colour": "neutral", "position": 21}, {"name": "Vulpix", "colour": "blue", "position": 22}, {"name": "Luxray", "colour": "blue", "position": 23}, {"name": "Chandelure", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-27', 'gen1',
   '[{"word": "COILS", "number": 1, "cat": 2, "t": [4]}, {"word": "EMBER", "number": 2, "cat": 3, "t": [6, 10]}, {"word": "SLUMBER", "number": 2, "cat": 3, "t": [2, 23]}, {"word": "TUSKER", "number": 2, "cat": 4, "t": [13, 18]}, {"word": "RODENT", "number": 2, "cat": 4, "t": [5, 7]}]'::jsonb,
   '[{"word": "PENDULUM", "number": 1, "cat": 2, "t": [2]}, {"word": "CURLS", "number": 1, "cat": 2, "t": [6]}, {"word": "COILS", "number": 1, "cat": 2, "t": [4]}, {"word": "TUSK", "number": 1, "cat": 2, "t": [18]}, {"word": "BUCK-TEETH", "number": 1, "cat": 2, "t": [5]}, {"word": "PUP", "number": 1, "cat": 2, "t": [10]}, {"word": "CURLED", "number": 1, "cat": 2, "t": [7]}, {"word": "TAPIR", "number": 1, "cat": 3, "t": [23]}, {"word": "SLEEK", "number": 1, "cat": 2, "t": [13]}]'::jsonb,
   '[{"name": "Onix", "colour": "neutral", "position": 0}, {"name": "Mankey", "colour": "neutral", "position": 1}, {"name": "Hypno", "colour": "blue", "position": 2}, {"name": "Kingler", "colour": "neutral", "position": 3}, {"name": "Ekans", "colour": "blue", "position": 4}, {"name": "Rattata", "colour": "blue", "position": 5}, {"name": "Vulpix", "colour": "blue", "position": 6}, {"name": "Sandshrew", "colour": "blue", "position": 7}, {"name": "Kangaskhan", "colour": "neutral", "position": 8}, {"name": "Muk", "colour": "neutral", "position": 9}, {"name": "Growlithe", "colour": "blue", "position": 10}, {"name": "Dodrio", "colour": "neutral", "position": 11}, {"name": "Kabutops", "colour": "neutral", "position": 12}, {"name": "Dewgong", "colour": "blue", "position": 13}, {"name": "Electabuzz", "colour": "neutral", "position": 14}, {"name": "Chansey", "colour": "neutral", "position": 15}, {"name": "Abra", "colour": "neutral", "position": 16}, {"name": "Nidoqueen", "colour": "neutral", "position": 17}, {"name": "Seel", "colour": "blue", "position": 18}, {"name": "Dragonair", "colour": "neutral", "position": 19}, {"name": "Koffing", "colour": "neutral", "position": 20}, {"name": "Graveler", "colour": "neutral", "position": 21}, {"name": "Grimer", "colour": "neutral", "position": 22}, {"name": "Drowzee", "colour": "blue", "position": 23}, {"name": "Jigglypuff", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-27', 'mixed',
   '[{"word": "SLINK", "number": 2, "cat": 3, "t": [12, 23]}, {"word": "ROYAL", "number": 2, "cat": 4, "t": [7, 21]}, {"word": "AXE", "number": 2, "cat": 4, "t": [0, 4]}, {"word": "SIZZLE", "number": 2, "cat": 3, "t": [5, 10]}, {"word": "LAMP", "number": 1, "cat": 2, "t": [24]}]'::jsonb,
   '[{"word": "TUSKS", "number": 1, "cat": 2, "t": [5]}, {"word": "AXE-JAW", "number": 1, "cat": 2, "t": [0]}, {"word": "SLEEK-CAT", "number": 1, "cat": 2, "t": [12]}, {"word": "TRIDENT", "number": 1, "cat": 2, "t": [7]}, {"word": "BELT-FIRE", "number": 1, "cat": 2, "t": [10]}, {"word": "LANTERN", "number": 1, "cat": 2, "t": [24]}, {"word": "PAPER", "number": 1, "cat": 2, "t": [4]}, {"word": "SCALES", "number": 1, "cat": 2, "t": [21]}, {"word": "PONYTAIL", "number": 1, "cat": 2, "t": [23]}]'::jsonb,
   '[{"name": "Haxorus", "colour": "blue", "position": 0}, {"name": "Grapploct", "colour": "neutral", "position": 1}, {"name": "Venusaur", "colour": "neutral", "position": 2}, {"name": "Corviknight", "colour": "neutral", "position": 3}, {"name": "Kartana", "colour": "blue", "position": 4}, {"name": "Emboar", "colour": "blue", "position": 5}, {"name": "Braviary", "colour": "neutral", "position": 6}, {"name": "Empoleon", "colour": "blue", "position": 7}, {"name": "Golduck", "colour": "neutral", "position": 8}, {"name": "Fearow", "colour": "neutral", "position": 9}, {"name": "Incineroar", "colour": "blue", "position": 10}, {"name": "Tyranitar", "colour": "neutral", "position": 11}, {"name": "Liepard", "colour": "blue", "position": 12}, {"name": "Espeon", "colour": "neutral", "position": 13}, {"name": "Articuno", "colour": "neutral", "position": 14}, {"name": "Machop", "colour": "neutral", "position": 15}, {"name": "Beartic", "colour": "neutral", "position": 16}, {"name": "Metagross", "colour": "neutral", "position": 17}, {"name": "Milotic", "colour": "neutral", "position": 18}, {"name": "Drowzee", "colour": "neutral", "position": 19}, {"name": "Mimikyu", "colour": "neutral", "position": 20}, {"name": "Nidoqueen", "colour": "blue", "position": 21}, {"name": "Geodude", "colour": "neutral", "position": 22}, {"name": "Zoroark", "colour": "blue", "position": 23}, {"name": "Chandelure", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-08-28', 'gen1',
   '[{"word": "SPARK", "number": 3, "cat": 3, "t": [14, 15, 21]}, {"word": "PEARL", "number": 1, "cat": 2, "t": [3]}, {"word": "AMBER", "number": 1, "cat": 4, "t": [16]}, {"word": "SPOOKY", "number": 2, "cat": 3, "t": [2, 11]}, {"word": "RELIC", "number": 2, "cat": 4, "t": [12, 20]}]'::jsonb,
   '[{"word": "BALL", "number": 1, "cat": 3, "t": [14]}, {"word": "HANDS", "number": 1, "cat": 2, "t": [2]}, {"word": "SPIRAL-SHELL", "number": 1, "cat": 2, "t": [12]}, {"word": "VAPOUR", "number": 1, "cat": 2, "t": [11]}, {"word": "SPHERE", "number": 1, "cat": 2, "t": [15]}, {"word": "SPIRAL", "number": 1, "cat": 2, "t": [20]}, {"word": "SCREW", "number": 1, "cat": 2, "t": [21]}, {"word": "PEARL", "number": 1, "cat": 2, "t": [3]}, {"word": "ROCK-WINGS", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
   '[{"name": "Weedle", "colour": "neutral", "position": 0}, {"name": "Rapidash", "colour": "neutral", "position": 1}, {"name": "Haunter", "colour": "blue", "position": 2}, {"name": "Cloyster", "colour": "blue", "position": 3}, {"name": "Electabuzz", "colour": "neutral", "position": 4}, {"name": "Growlithe", "colour": "neutral", "position": 5}, {"name": "Alakazam", "colour": "neutral", "position": 6}, {"name": "Krabby", "colour": "neutral", "position": 7}, {"name": "Rattata", "colour": "neutral", "position": 8}, {"name": "Articuno", "colour": "neutral", "position": 9}, {"name": "Golduck", "colour": "neutral", "position": 10}, {"name": "Gastly", "colour": "blue", "position": 11}, {"name": "Omanyte", "colour": "blue", "position": 12}, {"name": "Tentacruel", "colour": "neutral", "position": 13}, {"name": "Voltorb", "colour": "blue", "position": 14}, {"name": "Electrode", "colour": "blue", "position": 15}, {"name": "Aerodactyl", "colour": "blue", "position": 16}, {"name": "Onix", "colour": "neutral", "position": 17}, {"name": "Pinsir", "colour": "neutral", "position": 18}, {"name": "Arbok", "colour": "neutral", "position": 19}, {"name": "Omastar", "colour": "blue", "position": 20}, {"name": "Magnemite", "colour": "blue", "position": 21}, {"name": "Vileplume", "colour": "neutral", "position": 22}, {"name": "Farfetch''d", "colour": "neutral", "position": 23}, {"name": "Tentacool", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-28', 'mixed',
   '[{"word": "ARMOURED", "number": 2, "cat": 4, "t": [10, 20]}, {"word": "BRINE", "number": 2, "cat": 3, "t": [7, 22]}, {"word": "SERPENT", "number": 2, "cat": 3, "t": [5, 15]}, {"word": "JAWS", "number": 1, "cat": 2, "t": [1]}, {"word": "AERIAL", "number": 2, "cat": 4, "t": [2, 12]}]'::jsonb,
   '[{"word": "BLADES", "number": 1, "cat": 2, "t": [20]}, {"word": "WHISKERS", "number": 1, "cat": 2, "t": [22]}, {"word": "RIBBON", "number": 1, "cat": 2, "t": [5]}, {"word": "JAWS", "number": 1, "cat": 2, "t": [1]}, {"word": "TRIDENT", "number": 1, "cat": 2, "t": [7]}, {"word": "ARMOUR", "number": 1, "cat": 2, "t": [10]}, {"word": "EAGLE", "number": 1, "cat": 3, "t": [12]}, {"word": "SERPENT-JAW", "number": 1, "cat": 2, "t": [15]}, {"word": "HAWK-CREST", "number": 1, "cat": 2, "t": [2]}]'::jsonb,
   '[{"name": "Wailord", "colour": "neutral", "position": 0}, {"name": "Feraligatr", "colour": "blue", "position": 1}, {"name": "Staraptor", "colour": "blue", "position": 2}, {"name": "Malamar", "colour": "neutral", "position": 3}, {"name": "Lickitung", "colour": "neutral", "position": 4}, {"name": "Milotic", "colour": "blue", "position": 5}, {"name": "Mudsdale", "colour": "neutral", "position": 6}, {"name": "Empoleon", "colour": "blue", "position": 7}, {"name": "Staryu", "colour": "neutral", "position": 8}, {"name": "Alakazam", "colour": "neutral", "position": 9}, {"name": "Corviknight", "colour": "blue", "position": 10}, {"name": "Dragapult", "colour": "neutral", "position": 11}, {"name": "Braviary", "colour": "blue", "position": 12}, {"name": "Golduck", "colour": "neutral", "position": 13}, {"name": "Umbreon", "colour": "neutral", "position": 14}, {"name": "Gyarados", "colour": "blue", "position": 15}, {"name": "Metapod", "colour": "neutral", "position": 16}, {"name": "Seaking", "colour": "neutral", "position": 17}, {"name": "Tyrantrum", "colour": "neutral", "position": 18}, {"name": "Octillery", "colour": "neutral", "position": 19}, {"name": "Bisharp", "colour": "blue", "position": 20}, {"name": "Mr. Mime", "colour": "neutral", "position": 21}, {"name": "Samurott", "colour": "blue", "position": 22}, {"name": "Hydreigon", "colour": "neutral", "position": 23}, {"name": "Grimer", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-29', 'gen1',
   '[{"word": "KICK", "number": 2, "cat": 3, "t": [13, 18]}, {"word": "TRILOBITE", "number": 2, "cat": 4, "t": [15, 16]}, {"word": "SPIRAL", "number": 1, "cat": 2, "t": [15]}, {"word": "BRAWLER", "number": 3, "cat": 4, "t": [2, 13, 18]}, {"word": "QUAKE", "number": 4, "cat": 4, "t": [4, 11, 20, 21]}]'::jsonb,
   '[{"word": "SPIKES", "number": 1, "cat": 2, "t": [21]}, {"word": "BONE-CLUB", "number": 1, "cat": 2, "t": [11]}, {"word": "FOUR-ARMS", "number": 1, "cat": 2, "t": [18]}, {"word": "KICK-LEGS", "number": 1, "cat": 2, "t": [13]}, {"word": "DOME", "number": 1, "cat": 2, "t": [16]}, {"word": "DRILL-HORN", "number": 1, "cat": 2, "t": [20]}, {"word": "GLOVES", "number": 1, "cat": 2, "t": [2]}, {"word": "BOULDER", "number": 1, "cat": 2, "t": [4]}, {"word": "SPIRAL", "number": 1, "cat": 2, "t": [15]}]'::jsonb,
   '[{"name": "Fearow", "colour": "neutral", "position": 0}, {"name": "Farfetch''d", "colour": "neutral", "position": 1}, {"name": "Hitmonchan", "colour": "blue", "position": 2}, {"name": "Kangaskhan", "colour": "neutral", "position": 3}, {"name": "Golem", "colour": "blue", "position": 4}, {"name": "Poliwag", "colour": "neutral", "position": 5}, {"name": "Hypno", "colour": "neutral", "position": 6}, {"name": "Jolteon", "colour": "neutral", "position": 7}, {"name": "Vulpix", "colour": "neutral", "position": 8}, {"name": "Mr. Mime", "colour": "neutral", "position": 9}, {"name": "Dragonair", "colour": "neutral", "position": 10}, {"name": "Marowak", "colour": "blue", "position": 11}, {"name": "Blastoise", "colour": "neutral", "position": 12}, {"name": "Hitmonlee", "colour": "blue", "position": 13}, {"name": "Magmar", "colour": "neutral", "position": 14}, {"name": "Omastar", "colour": "blue", "position": 15}, {"name": "Kabuto", "colour": "blue", "position": 16}, {"name": "Gengar", "colour": "neutral", "position": 17}, {"name": "Machamp", "colour": "blue", "position": 18}, {"name": "Charizard", "colour": "neutral", "position": 19}, {"name": "Rhydon", "colour": "blue", "position": 20}, {"name": "Nidoking", "colour": "blue", "position": 21}, {"name": "Alakazam", "colour": "neutral", "position": 22}, {"name": "Arcanine", "colour": "neutral", "position": 23}, {"name": "Seaking", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-29', 'mixed',
   '[{"word": "FERRET", "number": 2, "cat": 4, "t": [4, 6]}, {"word": "KRAKEN", "number": 3, "cat": 4, "t": [8, 9, 10]}, {"word": "EEL", "number": 2, "cat": 3, "t": [0, 13]}, {"word": "MANE", "number": 1, "cat": 2, "t": [4]}, {"word": "DAUNT", "number": 3, "cat": 5, "t": [11, 13, 20]}]'::jsonb,
   '[{"word": "PONYTAIL", "number": 1, "cat": 2, "t": [4]}, {"word": "SUCKERS", "number": 1, "cat": 2, "t": [10]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [6]}, {"word": "RIBBON", "number": 1, "cat": 2, "t": [0]}, {"word": "SQUID", "number": 1, "cat": 3, "t": [8]}, {"word": "CRESCENT", "number": 1, "cat": 2, "t": [20]}, {"word": "MANE", "number": 1, "cat": 2, "t": [11]}, {"word": "SERPENT-JAW", "number": 1, "cat": 2, "t": [13]}, {"word": "SUCKERS", "number": 1, "cat": 2, "t": [9]}]'::jsonb,
   '[{"name": "Milotic", "colour": "blue", "position": 0}, {"name": "Espeon", "colour": "neutral", "position": 1}, {"name": "Alomomola", "colour": "neutral", "position": 2}, {"name": "Samurott", "colour": "neutral", "position": 3}, {"name": "Zoroark", "colour": "blue", "position": 4}, {"name": "Geodude", "colour": "neutral", "position": 5}, {"name": "Weavile", "colour": "blue", "position": 6}, {"name": "Umbreon", "colour": "neutral", "position": 7}, {"name": "Malamar", "colour": "blue", "position": 8}, {"name": "Grapploct", "colour": "blue", "position": 9}, {"name": "Octillery", "colour": "blue", "position": 10}, {"name": "Luxray", "colour": "blue", "position": 11}, {"name": "Braviary", "colour": "neutral", "position": 12}, {"name": "Gyarados", "colour": "blue", "position": 13}, {"name": "Jynx", "colour": "neutral", "position": 14}, {"name": "Farfetch''d", "colour": "neutral", "position": 15}, {"name": "Dragonite", "colour": "neutral", "position": 16}, {"name": "Flareon", "colour": "neutral", "position": 17}, {"name": "Koffing", "colour": "neutral", "position": 18}, {"name": "Ninetales", "colour": "neutral", "position": 19}, {"name": "Salamence", "colour": "blue", "position": 20}, {"name": "Drowzee", "colour": "neutral", "position": 21}, {"name": "Shellder", "colour": "neutral", "position": 22}, {"name": "Staryu", "colour": "neutral", "position": 23}, {"name": "Pikachu", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-30', 'gen1',
   '[{"word": "HOOK", "number": 2, "cat": 3, "t": [3, 13]}, {"word": "SIMIAN", "number": 2, "cat": 4, "t": [3, 16]}, {"word": "VENOM", "number": 2, "cat": 4, "t": [10, 11]}, {"word": "CLOBBER", "number": 2, "cat": 5, "t": [3, 9]}, {"word": "TREMOR", "number": 4, "cat": 4, "t": [2, 8, 11, 24]}]'::jsonb,
   '[{"word": "ANGRY", "number": 1, "cat": 3, "t": [16]}, {"word": "BELT", "number": 1, "cat": 2, "t": [9]}, {"word": "SCALES", "number": 1, "cat": 2, "t": [10]}, {"word": "DRILL-HORN", "number": 1, "cat": 2, "t": [24]}, {"word": "GLOVES", "number": 1, "cat": 2, "t": [13]}, {"word": "BOULDER", "number": 1, "cat": 2, "t": [8]}, {"word": "SPIKES", "number": 1, "cat": 2, "t": [11]}, {"word": "FOUR-ARMS", "number": 1, "cat": 2, "t": [3]}, {"word": "BONE-CLUB", "number": 1, "cat": 2, "t": [2]}]'::jsonb,
   '[{"name": "Staryu", "colour": "neutral", "position": 0}, {"name": "Magmar", "colour": "neutral", "position": 1}, {"name": "Marowak", "colour": "blue", "position": 2}, {"name": "Machamp", "colour": "blue", "position": 3}, {"name": "Vileplume", "colour": "neutral", "position": 4}, {"name": "Scyther", "colour": "neutral", "position": 5}, {"name": "Aerodactyl", "colour": "neutral", "position": 6}, {"name": "Mr. Mime", "colour": "neutral", "position": 7}, {"name": "Golem", "colour": "blue", "position": 8}, {"name": "Machoke", "colour": "blue", "position": 9}, {"name": "Nidoqueen", "colour": "blue", "position": 10}, {"name": "Nidoking", "colour": "blue", "position": 11}, {"name": "Squirtle", "colour": "neutral", "position": 12}, {"name": "Hitmonchan", "colour": "blue", "position": 13}, {"name": "Seel", "colour": "neutral", "position": 14}, {"name": "Meowth", "colour": "neutral", "position": 15}, {"name": "Mankey", "colour": "blue", "position": 16}, {"name": "Gastly", "colour": "neutral", "position": 17}, {"name": "Dewgong", "colour": "neutral", "position": 18}, {"name": "Electrode", "colour": "neutral", "position": 19}, {"name": "Pidgeotto", "colour": "neutral", "position": 20}, {"name": "Magneton", "colour": "neutral", "position": 21}, {"name": "Haunter", "colour": "neutral", "position": 22}, {"name": "Metapod", "colour": "neutral", "position": 23}, {"name": "Rhydon", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-08-30', 'mixed',
   '[{"word": "INKLING", "number": 2, "cat": 4, "t": [7, 10]}, {"word": "HEX", "number": 3, "cat": 5, "t": [16, 17, 23]}, {"word": "BANSHEE", "number": 2, "cat": 3, "t": [22, 23]}, {"word": "FLOAT", "number": 2, "cat": 5, "t": [15, 22]}, {"word": "POLECAT", "number": 2, "cat": 4, "t": [11, 21]}]'::jsonb,
   '[{"word": "CLAWS", "number": 1, "cat": 2, "t": [21]}, {"word": "HAT", "number": 1, "cat": 2, "t": [22]}, {"word": "GEMSTONE", "number": 1, "cat": 2, "t": [17]}, {"word": "RAG", "number": 1, "cat": 2, "t": [16]}, {"word": "SUCKERS", "number": 1, "cat": 2, "t": [10]}, {"word": "LANTERN", "number": 1, "cat": 2, "t": [15]}, {"word": "KEYSTONE", "number": 1, "cat": 2, "t": [23]}, {"word": "SQUID", "number": 1, "cat": 3, "t": [7]}, {"word": "PONYTAIL", "number": 1, "cat": 2, "t": [11]}]'::jsonb,
   '[{"name": "Rhyperior", "colour": "neutral", "position": 0}, {"name": "Incineroar", "colour": "neutral", "position": 1}, {"name": "Exeggutor", "colour": "neutral", "position": 2}, {"name": "Kakuna", "colour": "neutral", "position": 3}, {"name": "Gallade", "colour": "neutral", "position": 4}, {"name": "Staraptor", "colour": "neutral", "position": 5}, {"name": "Onix", "colour": "neutral", "position": 6}, {"name": "Malamar", "colour": "blue", "position": 7}, {"name": "Rattata", "colour": "neutral", "position": 8}, {"name": "Hitmonchan", "colour": "neutral", "position": 9}, {"name": "Octillery", "colour": "blue", "position": 10}, {"name": "Zoroark", "colour": "blue", "position": 11}, {"name": "Magnemite", "colour": "neutral", "position": 12}, {"name": "Jigglypuff", "colour": "neutral", "position": 13}, {"name": "Pinsir", "colour": "neutral", "position": 14}, {"name": "Chandelure", "colour": "blue", "position": 15}, {"name": "Mimikyu", "colour": "blue", "position": 16}, {"name": "Sableye", "colour": "blue", "position": 17}, {"name": "Dewgong", "colour": "neutral", "position": 18}, {"name": "Krabby", "colour": "neutral", "position": 19}, {"name": "Toxtricity", "colour": "neutral", "position": 20}, {"name": "Weavile", "colour": "blue", "position": 21}, {"name": "Mismagius", "colour": "blue", "position": 22}, {"name": "Spiritomb", "colour": "blue", "position": 23}, {"name": "Vileplume", "colour": "neutral", "position": 24}]'::jsonb)
on conflict (puzzle_date, pool) do update
  set clues = excluded.clues, hints = excluded.hints, tiles = excluded.tiles;

-- Fix 2026-08-17 mixed: replace neutral 'Alomomola' with 'Ampharos' (same position).
update public.daily_puzzles
   set tiles = (
         select jsonb_agg(
           case when t->>'name' = 'Alomomola'
                then jsonb_set(t, '{name}', '"Ampharos"'::jsonb)
                else t end)
         from jsonb_array_elements(tiles) t)
 where puzzle_date = '2026-08-17' and pool = 'mixed'
   and tiles @> '[{"name":"Alomomola"}]'::jsonb;
