-- 31_updates.sql
--
-- Two daily-puzzle upgrades (batched with the Aug 31 - Sep 6 puzzle data below):
--
--   (1) Per-clue explanations. Each base clue now carries an "explain" sentence
--       (why the clue points at those Pokemon + which category it is). The end
--       screen shows it under each clue. get_daily_puzzle strips it mid-game so
--       it can't leak the answers early.
--
--   (2) Offline play. New RPC get_daily_full returns the whole puzzle "sealed":
--       the colour key + hints (with targets) + clues (with targets and
--       explanations), XOR-obfuscated + base64 so it isn't plain text in the
--       network response. The client unseals it once at load and then does every
--       reveal / hint / finish LOCALLY, so a player who loses connection after
--       the page has loaded can still finish the puzzle.
--
-- Safe to re-run (create-or-replace + upsert).

-- ----------------------------------------------------------------------------
-- _daily_seal: XOR-obfuscate a jsonb payload with a fixed repeating key, then
-- base64-encode it. The matching key + un-seal live in app.js. This is light
-- obfuscation (not encryption) - enough that the answers aren't readable at a
-- glance, while letting the whole puzzle be played offline once loaded.
-- ----------------------------------------------------------------------------
create or replace function public._daily_seal(p jsonb)
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  b bytea;
  i int;
  n int;
  k int[] := array[142,55,91,44,116,17,163];
begin
  b := convert_to(p::text, 'UTF8');
  n := octet_length(b);
  for i in 0..n-1 loop
    b := set_byte(b, i, get_byte(b, i) # k[(i % 7) + 1]);
  end loop;
  return encode(b, 'base64');
end;
$$;

-- ----------------------------------------------------------------------------
-- get_daily_puzzle: serve today's board + base clues WITHOUT target positions
-- OR the explanation text (both must stay hidden until the game ends).
-- ----------------------------------------------------------------------------
create or replace function public.get_daily_puzzle(p_pool text)
returns table(puzzle_date date, clues jsonb, tiles jsonb)
language sql
security definer
set search_path = public
as $$
  select dp.puzzle_date,
    (
      select jsonb_agg((c - 't' - 'explain') order by ord)
      from jsonb_array_elements(dp.clues) with ordinality as x(c, ord)
    ) as clues,
    (
      select jsonb_agg(
        jsonb_build_object(
          'position',   (t->>'position')::int,
          'name',       t->>'name',
          'pokemon_id', pk.id,
          'sprite_url', pk.sprite_url
        ) order by (t->>'position')::int
      )
      from jsonb_array_elements(dp.tiles) t
      left join pokemon pk on lower(pk.name) = lower(t->>'name')
    ) as tiles
  from daily_puzzles dp
  where dp.pool = p_pool and dp.puzzle_date <= current_date
  order by dp.puzzle_date desc
  limit 1;
$$;

-- ----------------------------------------------------------------------------
-- get_daily_full: today's board (tiles WITHOUT colours, for rendering) plus a
-- sealed blob carrying everything needed to play + finish OFFLINE:
--   c = { position -> colour },  h = hints (with t),  k = clues (with t+explain)
-- ----------------------------------------------------------------------------
create or replace function public.get_daily_full(p_pool text)
returns table(puzzle_date date, tiles jsonb, sealed text)
language sql
security definer
set search_path = public
as $$
  select dp.puzzle_date,
    (
      select jsonb_agg(
        jsonb_build_object(
          'position',   (t->>'position')::int,
          'name',       t->>'name',
          'pokemon_id', pk.id,
          'sprite_url', pk.sprite_url
        ) order by (t->>'position')::int
      )
      from jsonb_array_elements(dp.tiles) t
      left join pokemon pk on lower(pk.name) = lower(t->>'name')
    ) as tiles,
    public._daily_seal(jsonb_build_object(
      'c', (
        select jsonb_object_agg(t->>'position', t->>'colour')
        from jsonb_array_elements(dp.tiles) t
      ),
      'h', coalesce(dp.hints, '[]'::jsonb),
      'k', dp.clues
    )) as sealed
  from daily_puzzles dp
  where dp.pool = p_pool and dp.puzzle_date <= current_date
  order by dp.puzzle_date desc
  limit 1;
$$;

grant execute on function public.get_daily_puzzle(text) to authenticated;
grant execute on function public.get_daily_full(text)   to authenticated;


-- ------------------------------------------------------------------
-- Puzzle data: 2026-08-31 .. 2026-09-06 (fact-bank authored, with per-clue explanations).

insert into public.daily_puzzles (puzzle_date, pool, clues, hints, tiles) values
  ('2026-08-31', 'gen1',
   '[{"word": "PUNCH", "number": 2, "cat": 2, "t": [20, 23], "explain": "You can spot it on the sprite \u2014 the raised fists."}, {"word": "BOULDER", "number": 2, "cat": 3, "t": [4, 7], "explain": "They''re all based on the real-world rock golem."}, {"word": "GRASS", "number": 2, "cat": 1, "t": [9, 14], "explain": "Every one is a Grass-type."}, {"word": "PSYCHIC", "number": 2, "cat": 1, "t": [11, 21], "explain": "Every one is a Psychic-type."}, {"word": "POLLINATOR", "number": 1, "cat": 3, "t": [6], "explain": "They''re all based on the real-world butterfly."}]'::jsonb,
   '[{"word": "SLEEPS-18H", "number": 1, "cat": 2, "t": [11]}, {"word": "PLANT", "number": 1, "cat": 3, "t": [9]}, {"word": "PRIMATE", "number": 1, "cat": 3, "t": [23]}, {"word": "BLUE-BODY", "number": 1, "cat": 2, "t": [14]}, {"word": "PENDULUM-HANDS", "number": 1, "cat": 2, "t": [21]}, {"word": "TAIL", "number": 1, "cat": 2, "t": [20]}, {"word": "SHELL-PLATES", "number": 1, "cat": 2, "t": [7]}, {"word": "ROCKY-BODY", "number": 1, "cat": 2, "t": [4]}, {"word": "BIG-EYES", "number": 1, "cat": 2, "t": [6]}]'::jsonb,
   '[{"name": "Koffing", "colour": "neutral", "position": 0}, {"name": "Golbat", "colour": "neutral", "position": 1}, {"name": "Magikarp", "colour": "neutral", "position": 2}, {"name": "Seadra", "colour": "neutral", "position": 3}, {"name": "Geodude", "colour": "blue", "position": 4}, {"name": "Tauros", "colour": "neutral", "position": 5}, {"name": "Butterfree", "colour": "blue", "position": 6}, {"name": "Golem", "colour": "blue", "position": 7}, {"name": "Blastoise", "colour": "neutral", "position": 8}, {"name": "Gloom", "colour": "blue", "position": 9}, {"name": "Vulpix", "colour": "neutral", "position": 10}, {"name": "Abra", "colour": "blue", "position": 11}, {"name": "Marowak", "colour": "neutral", "position": 12}, {"name": "Persian", "colour": "neutral", "position": 13}, {"name": "Oddish", "colour": "blue", "position": 14}, {"name": "Muk", "colour": "neutral", "position": 15}, {"name": "Rapidash", "colour": "neutral", "position": 16}, {"name": "Dodrio", "colour": "neutral", "position": 17}, {"name": "Articuno", "colour": "neutral", "position": 18}, {"name": "Seel", "colour": "neutral", "position": 19}, {"name": "Machop", "colour": "blue", "position": 20}, {"name": "Drowzee", "colour": "blue", "position": 21}, {"name": "Porygon", "colour": "neutral", "position": 22}, {"name": "Machoke", "colour": "blue", "position": 23}, {"name": "Clefairy", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-31', 'mixed',
   '[{"word": "TOADSTOOL", "number": 1, "cat": 2, "t": [14], "explain": "You can spot it on the sprite \u2014 the mushroom on its back."}, {"word": "DRAGON", "number": 2, "cat": 1, "t": [4, 12], "explain": "Every one is a Dragon-type."}, {"word": "GRUB", "number": 2, "cat": 3, "t": [16, 24], "explain": "They''re all based on the real-world caterpillar."}, {"word": "WATER", "number": 2, "cat": 1, "t": [1, 13], "explain": "Every one is a Water-type."}, {"word": "FOX", "number": 2, "cat": 3, "t": [18, 22], "explain": "They''re all based on the real-world fox."}]'::jsonb,
   '[{"word": "FIN-HOOD", "number": 1, "cat": 2, "t": [12]}, {"word": "LEAF-CLOAK", "number": 1, "cat": 2, "t": [24]}, {"word": "TWIG-WAND", "number": 1, "cat": 2, "t": [18]}, {"word": "HEAD-SCALE", "number": 1, "cat": 2, "t": [4]}, {"word": "LEAF-HOOD", "number": 1, "cat": 2, "t": [16]}, {"word": "BEAK", "number": 1, "cat": 2, "t": [1]}, {"word": "CAP", "number": 1, "cat": 2, "t": [14]}, {"word": "EAR-TUFTS", "number": 1, "cat": 2, "t": [22]}, {"word": "HORN-TOOTH", "number": 1, "cat": 2, "t": [13]}]'::jsonb,
   '[{"name": "Aipom", "colour": "neutral", "position": 0}, {"name": "Wingull", "colour": "blue", "position": 1}, {"name": "Salazzle", "colour": "neutral", "position": 2}, {"name": "Gigalith", "colour": "neutral", "position": 3}, {"name": "Jangmo-o", "colour": "blue", "position": 4}, {"name": "Herdier", "colour": "neutral", "position": 5}, {"name": "Ralts", "colour": "neutral", "position": 6}, {"name": "Kangaskhan", "colour": "neutral", "position": 7}, {"name": "Rampardos", "colour": "neutral", "position": 8}, {"name": "Decidueye", "colour": "neutral", "position": 9}, {"name": "Heracross", "colour": "neutral", "position": 10}, {"name": "Sentret", "colour": "neutral", "position": 11}, {"name": "Gible", "colour": "blue", "position": 12}, {"name": "Chewtle", "colour": "blue", "position": 13}, {"name": "Shroomish", "colour": "blue", "position": 14}, {"name": "Swinub", "colour": "neutral", "position": 15}, {"name": "Sewaddle", "colour": "blue", "position": 16}, {"name": "Petilil", "colour": "neutral", "position": 17}, {"name": "Braixen", "colour": "blue", "position": 18}, {"name": "Magmar", "colour": "neutral", "position": 19}, {"name": "Orbeetle", "colour": "neutral", "position": 20}, {"name": "Chikorita", "colour": "neutral", "position": 21}, {"name": "Fennekin", "colour": "blue", "position": 22}, {"name": "Ursaring", "colour": "neutral", "position": 23}, {"name": "Swadloon", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-01', 'gen1',
   '[{"word": "ELECTRIC", "number": 2, "cat": 1, "t": [1, 2], "explain": "Every one is a Electric-type."}, {"word": "ROCK", "number": 2, "cat": 1, "t": [10, 11], "explain": "Every one is a Rock-type."}, {"word": "GROUND", "number": 2, "cat": 1, "t": [19, 24], "explain": "Every one is a Ground-type."}, {"word": "SEEDS", "number": 1, "cat": 2, "t": [22], "explain": "You can spot it on the sprite \u2014 the seeds on its body."}, {"word": "DRACULA", "number": 2, "cat": 4, "t": [16, 17], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re vampire bats."}]'::jsonb,
   '[{"word": "HUGE-MOUTH", "number": 1, "cat": 2, "t": [16]}, {"word": "UFO", "number": 1, "cat": 3, "t": [1]}, {"word": "BACK-SPIKES", "number": 1, "cat": 2, "t": [24]}, {"word": "DOME-SHELL", "number": 1, "cat": 2, "t": [10]}, {"word": "SPIRAL-SHELL", "number": 1, "cat": 2, "t": [11]}, {"word": "CURL", "number": 1, "cat": 2, "t": [19]}, {"word": "GRAY-BODY", "number": 1, "cat": 2, "t": [2]}, {"word": "NO-EYES", "number": 1, "cat": 2, "t": [17]}, {"word": "CRACKS", "number": 1, "cat": 2, "t": [22]}]'::jsonb,
   '[{"name": "Tentacool", "colour": "neutral", "position": 0}, {"name": "Magnemite", "colour": "blue", "position": 1}, {"name": "Magneton", "colour": "blue", "position": 2}, {"name": "Ninetales", "colour": "neutral", "position": 3}, {"name": "Clefairy", "colour": "neutral", "position": 4}, {"name": "Snorlax", "colour": "neutral", "position": 5}, {"name": "Poliwag", "colour": "neutral", "position": 6}, {"name": "Haunter", "colour": "neutral", "position": 7}, {"name": "Jynx", "colour": "neutral", "position": 8}, {"name": "Mewtwo", "colour": "neutral", "position": 9}, {"name": "Kabuto", "colour": "blue", "position": 10}, {"name": "Omanyte", "colour": "blue", "position": 11}, {"name": "Machoke", "colour": "neutral", "position": 12}, {"name": "Magmar", "colour": "neutral", "position": 13}, {"name": "Moltres", "colour": "neutral", "position": 14}, {"name": "Meowth", "colour": "neutral", "position": 15}, {"name": "Golbat", "colour": "blue", "position": 16}, {"name": "Zubat", "colour": "blue", "position": 17}, {"name": "Koffing", "colour": "neutral", "position": 18}, {"name": "Sandshrew", "colour": "blue", "position": 19}, {"name": "Venonat", "colour": "neutral", "position": 20}, {"name": "Pinsir", "colour": "neutral", "position": 21}, {"name": "Exeggcute", "colour": "blue", "position": 22}, {"name": "Wigglytuff", "colour": "neutral", "position": 23}, {"name": "Sandslash", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-01', 'mixed',
   '[{"word": "FAIRY", "number": 2, "cat": 1, "t": [19, 22], "explain": "Every one is a Fairy-type."}, {"word": "SNAIL", "number": 1, "cat": 3, "t": [24], "explain": "They''re all based on the real-world snail."}, {"word": "RAVEN", "number": 2, "cat": 3, "t": [0, 6], "explain": "They''re all based on the real-world crow."}, {"word": "GROUND", "number": 2, "cat": 1, "t": [4, 13], "explain": "Every one is a Ground-type."}, {"word": "ELECTRIC", "number": 2, "cat": 1, "t": [7, 23], "explain": "Every one is a Electric-type."}]'::jsonb,
   '[{"word": "WINGS", "number": 1, "cat": 2, "t": [19]}, {"word": "BIG-EARS", "number": 1, "cat": 2, "t": [4]}, {"word": "BIRD", "number": 1, "cat": 3, "t": [0]}, {"word": "CHEEKS", "number": 1, "cat": 2, "t": [23]}, {"word": "SPIKES", "number": 1, "cat": 2, "t": [22]}, {"word": "FRILLS", "number": 1, "cat": 2, "t": [24]}, {"word": "CANINE", "number": 1, "cat": 3, "t": [7]}, {"word": "WITCH-HAT-CREST", "number": 1, "cat": 2, "t": [6]}, {"word": "SAND-BODY", "number": 1, "cat": 2, "t": [13]}]'::jsonb,
   '[{"name": "Honchkrow", "colour": "blue", "position": 0}, {"name": "Zoroark", "colour": "neutral", "position": 1}, {"name": "Rowlet", "colour": "neutral", "position": 2}, {"name": "Hydrapple", "colour": "neutral", "position": 3}, {"name": "Phanpy", "colour": "blue", "position": 4}, {"name": "Duraludon", "colour": "neutral", "position": 5}, {"name": "Murkrow", "colour": "blue", "position": 6}, {"name": "Yamper", "colour": "blue", "position": 7}, {"name": "Snom", "colour": "neutral", "position": 8}, {"name": "Minior", "colour": "neutral", "position": 9}, {"name": "Rellor", "colour": "neutral", "position": 10}, {"name": "Rolycoly", "colour": "neutral", "position": 11}, {"name": "Pidgey", "colour": "neutral", "position": 12}, {"name": "Hippopotas", "colour": "blue", "position": 13}, {"name": "Kartana", "colour": "neutral", "position": 14}, {"name": "Ferrothorn", "colour": "neutral", "position": 15}, {"name": "Vullaby", "colour": "neutral", "position": 16}, {"name": "Dracovish", "colour": "neutral", "position": 17}, {"name": "Panpour", "colour": "neutral", "position": 18}, {"name": "Togetic", "colour": "blue", "position": 19}, {"name": "Crustle", "colour": "neutral", "position": 20}, {"name": "Bonsly", "colour": "neutral", "position": 21}, {"name": "Togepi", "colour": "blue", "position": 22}, {"name": "Pichu", "colour": "blue", "position": 23}, {"name": "Shellos", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-02', 'gen1',
   '[{"word": "SKULL-MASK", "number": 2, "cat": 3, "t": [4, 16], "explain": "They''re based on the bone club and skull helmet it wears."}, {"word": "SOPRANO", "number": 1, "cat": 4, "t": [15], "explain": "It''s from their Pok\u00e9dex lore \u2014 an opera diva / snow-hag."}, {"word": "TELEPORT", "number": 2, "cat": 3, "t": [8, 18], "explain": "It''s from their Pok\u00e9dex lore \u2014 its signature Teleport move."}, {"word": "BUG", "number": 2, "cat": 1, "t": [2, 7], "explain": "Every one is a Bug-type."}, {"word": "POISON", "number": 2, "cat": 1, "t": [3, 9], "explain": "Every one is a Poison-type."}]'::jsonb,
   '[{"word": "SKULL-HELMET", "number": 1, "cat": 2, "t": [16]}, {"word": "HORN", "number": 1, "cat": 2, "t": [3]}, {"word": "MUSHROOMS", "number": 1, "cat": 2, "t": [2]}, {"word": "GOWN", "number": 1, "cat": 2, "t": [15]}, {"word": "SPOON", "number": 1, "cat": 2, "t": [18]}, {"word": "TWIN-SPOONS", "number": 1, "cat": 2, "t": [8]}, {"word": "ANTENNA", "number": 1, "cat": 2, "t": [7]}, {"word": "MAMMAL", "number": 1, "cat": 3, "t": [4]}, {"word": "SPINES", "number": 1, "cat": 2, "t": [9]}]'::jsonb,
   '[{"name": "Moltres", "colour": "neutral", "position": 0}, {"name": "Dragonite", "colour": "neutral", "position": 1}, {"name": "Paras", "colour": "blue", "position": 2}, {"name": "Nidorino", "colour": "blue", "position": 3}, {"name": "Marowak", "colour": "blue", "position": 4}, {"name": "Starmie", "colour": "neutral", "position": 5}, {"name": "Rapidash", "colour": "neutral", "position": 6}, {"name": "Caterpie", "colour": "blue", "position": 7}, {"name": "Alakazam", "colour": "blue", "position": 8}, {"name": "Nidorina", "colour": "blue", "position": 9}, {"name": "Dragonair", "colour": "neutral", "position": 10}, {"name": "Lickitung", "colour": "neutral", "position": 11}, {"name": "Articuno", "colour": "neutral", "position": 12}, {"name": "Omanyte", "colour": "neutral", "position": 13}, {"name": "Magmar", "colour": "neutral", "position": 14}, {"name": "Jynx", "colour": "blue", "position": 15}, {"name": "Cubone", "colour": "blue", "position": 16}, {"name": "Staryu", "colour": "neutral", "position": 17}, {"name": "Kadabra", "colour": "blue", "position": 18}, {"name": "Machop", "colour": "neutral", "position": 19}, {"name": "Poliwrath", "colour": "neutral", "position": 20}, {"name": "Tangela", "colour": "neutral", "position": 21}, {"name": "Dodrio", "colour": "neutral", "position": 22}, {"name": "Growlithe", "colour": "neutral", "position": 23}, {"name": "Clefairy", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-02', 'mixed',
   '[{"word": "ACORN", "number": 1, "cat": 2, "t": [10], "explain": "You can spot it on the sprite \u2014 the acorn cap."}, {"word": "GATOR", "number": 2, "cat": 3, "t": [3, 21], "explain": "They''re all based on the real-world crocodile."}, {"word": "ICE", "number": 2, "cat": 1, "t": [6, 15], "explain": "Every one is a Ice-type."}, {"word": "FIGHTING", "number": 2, "cat": 1, "t": [0, 8], "explain": "Every one is a Fighting-type."}, {"word": "TAPIR", "number": 2, "cat": 3, "t": [1, 20], "explain": "They''re all based on the real-world tapir (a dream-eating baku)."}]'::jsonb,
   '[{"word": "ACORN-BODY", "number": 1, "cat": 2, "t": [10]}, {"word": "TAPIR", "number": 1, "cat": 3, "t": [1]}, {"word": "BIG-FISTS", "number": 1, "cat": 2, "t": [8]}, {"word": "ICE-BLOCK", "number": 1, "cat": 2, "t": [6]}, {"word": "JAWS", "number": 1, "cat": 2, "t": [21]}, {"word": "HOOD-BODY", "number": 1, "cat": 2, "t": [15]}, {"word": "BIG", "number": 1, "cat": 2, "t": [3]}, {"word": "LOTUS-POSE", "number": 1, "cat": 2, "t": [0]}, {"word": "FOREHEAD", "number": 1, "cat": 2, "t": [20]}]'::jsonb,
   '[{"name": "Meditite", "colour": "blue", "position": 0}, {"name": "Munna", "colour": "blue", "position": 1}, {"name": "Sentret", "colour": "neutral", "position": 2}, {"name": "Croconaw", "colour": "blue", "position": 3}, {"name": "Nidoqueen", "colour": "neutral", "position": 4}, {"name": "Spinarak", "colour": "neutral", "position": 5}, {"name": "Bergmite", "colour": "blue", "position": 6}, {"name": "Sunflora", "colour": "neutral", "position": 7}, {"name": "Makuhita", "colour": "blue", "position": 8}, {"name": "Inkay", "colour": "neutral", "position": 9}, {"name": "Seedot", "colour": "blue", "position": 10}, {"name": "Brute Bonnet", "colour": "neutral", "position": 11}, {"name": "Alomomola", "colour": "neutral", "position": 12}, {"name": "Palkia", "colour": "neutral", "position": 13}, {"name": "Sewaddle", "colour": "neutral", "position": 14}, {"name": "Snorunt", "colour": "blue", "position": 15}, {"name": "Loudred", "colour": "neutral", "position": 16}, {"name": "Lickitung", "colour": "neutral", "position": 17}, {"name": "Hoppip", "colour": "neutral", "position": 18}, {"name": "Cleffa", "colour": "neutral", "position": 19}, {"name": "Musharna", "colour": "blue", "position": 20}, {"name": "Totodile", "colour": "blue", "position": 21}, {"name": "Vullaby", "colour": "neutral", "position": 22}, {"name": "Lairon", "colour": "neutral", "position": 23}, {"name": "Sobble", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-03', 'gen1',
   '[{"word": "SERPENT", "number": 1, "cat": 3, "t": [13], "explain": "They''re all based on the real-world eel and sea-serpent."}, {"word": "FIRST-CHOICE", "number": 3, "cat": 1, "t": [9, 15, 22], "explain": "They''re first-partner (starter) Pok\u00e9mon."}, {"word": "DUX", "number": 2, "cat": 3, "t": [14, 16], "explain": "They''re all based on the real-world duck."}, {"word": "PINCERS", "number": 2, "cat": 2, "t": [11, 21], "explain": "You can spot it on the sprite \u2014 the big pincers."}, {"word": "GENIE", "number": 1, "cat": 5, "t": [6], "explain": "It''s from their Pok\u00e9dex lore \u2014 a mythical dragon."}]'::jsonb,
   '[{"word": "SHELL", "number": 1, "cat": 2, "t": [15]}, {"word": "HUGE-CLAW", "number": 1, "cat": 2, "t": [21]}, {"word": "FOREHEAD-GEM", "number": 1, "cat": 2, "t": [14]}, {"word": "SERPENT-BODY", "number": 1, "cat": 2, "t": [13]}, {"word": "PINCERS", "number": 1, "cat": 2, "t": [11]}, {"word": "BLANK-STARE", "number": 1, "cat": 2, "t": [16]}, {"word": "TOAD", "number": 1, "cat": 3, "t": [9]}, {"word": "SERPENT", "number": 1, "cat": 3, "t": [6]}, {"word": "FLAME-TAIL", "number": 1, "cat": 2, "t": [22]}]'::jsonb,
   '[{"name": "Pikachu", "colour": "neutral", "position": 0}, {"name": "Dugtrio", "colour": "neutral", "position": 1}, {"name": "Kangaskhan", "colour": "neutral", "position": 2}, {"name": "Onix", "colour": "neutral", "position": 3}, {"name": "Snorlax", "colour": "neutral", "position": 4}, {"name": "Porygon", "colour": "neutral", "position": 5}, {"name": "Dratini", "colour": "blue", "position": 6}, {"name": "Eevee", "colour": "neutral", "position": 7}, {"name": "Sandshrew", "colour": "neutral", "position": 8}, {"name": "Bulbasaur", "colour": "blue", "position": 9}, {"name": "Poliwrath", "colour": "neutral", "position": 10}, {"name": "Krabby", "colour": "blue", "position": 11}, {"name": "Gloom", "colour": "neutral", "position": 12}, {"name": "Gyarados", "colour": "blue", "position": 13}, {"name": "Golduck", "colour": "blue", "position": 14}, {"name": "Squirtle", "colour": "blue", "position": 15}, {"name": "Psyduck", "colour": "blue", "position": 16}, {"name": "Lapras", "colour": "neutral", "position": 17}, {"name": "Exeggutor", "colour": "neutral", "position": 18}, {"name": "Rapidash", "colour": "neutral", "position": 19}, {"name": "Poliwhirl", "colour": "neutral", "position": 20}, {"name": "Kingler", "colour": "blue", "position": 21}, {"name": "Charmander", "colour": "blue", "position": 22}, {"name": "Jolteon", "colour": "neutral", "position": 23}, {"name": "Venonat", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-03', 'mixed',
   '[{"word": "LEGENDARY", "number": 3, "cat": 1, "t": [10, 21, 23], "explain": "They''re all Legendary Pok\u00e9mon."}, {"word": "SICKLE", "number": 2, "cat": 2, "t": [6, 17], "explain": "You can spot it on the sprite \u2014 the scythe-shaped arms."}, {"word": "EIGHT-ARMS", "number": 1, "cat": 4, "t": [22], "explain": "They''re all based on the real-world octopus."}, {"word": "SIMIAN", "number": 2, "cat": 3, "t": [1, 12], "explain": "They''re all based on the real-world monkey."}, {"word": "LAZYBONES", "number": 1, "cat": 3, "t": [18], "explain": "They''re all based on the real-world sloth."}]'::jsonb,
   '[{"word": "METAL-BODY", "number": 1, "cat": 2, "t": [21]}, {"word": "GOLEM", "number": 1, "cat": 3, "t": [23]}, {"word": "MONKEY", "number": 1, "cat": 3, "t": [1]}, {"word": "PETAL-BLADES", "number": 1, "cat": 2, "t": [17]}, {"word": "LEAF-SCYTHES", "number": 1, "cat": 2, "t": [6]}, {"word": "LAZY-FACE", "number": 1, "cat": 2, "t": [18]}, {"word": "MONKEY-+-WATER-TUFT", "number": 1, "cat": 3, "t": [12]}, {"word": "DOT-FACE", "number": 1, "cat": 2, "t": [10]}, {"word": "MUSCLE-TENTACLES", "number": 1, "cat": 2, "t": [22]}]'::jsonb,
   '[{"name": "Shedinja", "colour": "neutral", "position": 0}, {"name": "Pansage", "colour": "blue", "position": 1}, {"name": "Amaura", "colour": "neutral", "position": 2}, {"name": "Infernape", "colour": "neutral", "position": 3}, {"name": "Grimer", "colour": "neutral", "position": 4}, {"name": "Stantler", "colour": "neutral", "position": 5}, {"name": "Fomantis", "colour": "blue", "position": 6}, {"name": "Kartana", "colour": "neutral", "position": 7}, {"name": "Sliggoo", "colour": "neutral", "position": 8}, {"name": "Mudsdale", "colour": "neutral", "position": 9}, {"name": "Regirock", "colour": "blue", "position": 10}, {"name": "Marowak", "colour": "neutral", "position": 11}, {"name": "Panpour", "colour": "blue", "position": 12}, {"name": "Psyduck", "colour": "neutral", "position": 13}, {"name": "Raging Bolt", "colour": "neutral", "position": 14}, {"name": "Hypno", "colour": "neutral", "position": 15}, {"name": "Yamask", "colour": "neutral", "position": 16}, {"name": "Lurantis", "colour": "blue", "position": 17}, {"name": "Slakoth", "colour": "blue", "position": 18}, {"name": "Horsea", "colour": "neutral", "position": 19}, {"name": "Iron Jugulis", "colour": "neutral", "position": 20}, {"name": "Registeel", "colour": "blue", "position": 21}, {"name": "Grapploct", "colour": "blue", "position": 22}, {"name": "Regice", "colour": "blue", "position": 23}, {"name": "Finizen", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-04', 'gen1',
   '[{"word": "RHINO", "number": 2, "cat": 3, "t": [8, 24], "explain": "They''re all based on the real-world rhinoceros."}, {"word": "COBRA", "number": 2, "cat": 3, "t": [9, 17], "explain": "They''re all based on the real-world cobra."}, {"word": "COIN", "number": 1, "cat": 2, "t": [16], "explain": "You can spot it on the sprite \u2014 the gold coin on its forehead."}, {"word": "FELINE", "number": 1, "cat": 3, "t": [13], "explain": "They''re all based on the real-world cat."}, {"word": "BRANCH-EVO", "number": 3, "cat": 1, "t": [10, 15, 19], "explain": "They''re all part of the Eevee family."}]'::jsonb,
   '[{"word": "FLUFFY-COLLAR", "number": 1, "cat": 2, "t": [19]}, {"word": "HOOD-PATTERN", "number": 1, "cat": 2, "t": [17]}, {"word": "FINS", "number": 1, "cat": 2, "t": [10]}, {"word": "COIN-CHARM", "number": 1, "cat": 2, "t": [16]}, {"word": "FELINE", "number": 1, "cat": 3, "t": [13]}, {"word": "SPIKY-FUR", "number": 1, "cat": 2, "t": [15]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [9]}, {"word": "ARMOUR-HIDE", "number": 1, "cat": 2, "t": [24]}, {"word": "TAIL", "number": 1, "cat": 2, "t": [8]}]'::jsonb,
   '[{"name": "Ponyta", "colour": "neutral", "position": 0}, {"name": "Weedle", "colour": "neutral", "position": 1}, {"name": "Graveler", "colour": "neutral", "position": 2}, {"name": "Machoke", "colour": "neutral", "position": 3}, {"name": "Oddish", "colour": "neutral", "position": 4}, {"name": "Hitmonlee", "colour": "neutral", "position": 5}, {"name": "Vulpix", "colour": "neutral", "position": 6}, {"name": "Bulbasaur", "colour": "neutral", "position": 7}, {"name": "Rhydon", "colour": "blue", "position": 8}, {"name": "Ekans", "colour": "blue", "position": 9}, {"name": "Vaporeon", "colour": "blue", "position": 10}, {"name": "Pidgeot", "colour": "neutral", "position": 11}, {"name": "Aerodactyl", "colour": "neutral", "position": 12}, {"name": "Persian", "colour": "blue", "position": 13}, {"name": "Krabby", "colour": "neutral", "position": 14}, {"name": "Jolteon", "colour": "blue", "position": 15}, {"name": "Meowth", "colour": "blue", "position": 16}, {"name": "Arbok", "colour": "blue", "position": 17}, {"name": "Poliwrath", "colour": "neutral", "position": 18}, {"name": "Eevee", "colour": "blue", "position": 19}, {"name": "Kakuna", "colour": "neutral", "position": 20}, {"name": "Electrode", "colour": "neutral", "position": 21}, {"name": "Tentacool", "colour": "neutral", "position": 22}, {"name": "Squirtle", "colour": "neutral", "position": 23}, {"name": "Rhyhorn", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-04', 'mixed',
   '[{"word": "MOLE", "number": 1, "cat": 3, "t": [24], "explain": "They''re all based on the real-world mole."}, {"word": "LANTERN", "number": 1, "cat": 4, "t": [3], "explain": "They''re based on a haunted lantern."}, {"word": "OTTER", "number": 2, "cat": 3, "t": [8, 11], "explain": "They''re all based on the real-world sea otter."}, {"word": "PSEUDO-LEGENDARY", "number": 3, "cat": 1, "t": [7, 12, 19], "explain": "They''re pseudo-legendary Pok\u00e9mon."}, {"word": "FIREFLY", "number": 2, "cat": 3, "t": [1, 4], "explain": "They''re all based on the real-world firefly."}]'::jsonb,
   '[{"word": "CLAWS", "number": 1, "cat": 2, "t": [24]}, {"word": "ROCK-HEAD", "number": 1, "cat": 2, "t": [19]}, {"word": "TWIN-TAILS", "number": 1, "cat": 2, "t": [8]}, {"word": "FINS", "number": 1, "cat": 2, "t": [11]}, {"word": "LIGHT-TAIL", "number": 1, "cat": 2, "t": [4]}, {"word": "BELLY-PLATE", "number": 1, "cat": 2, "t": [12]}, {"word": "ANTENNAE", "number": 1, "cat": 2, "t": [1]}, {"word": "FLAMES", "number": 1, "cat": 2, "t": [3]}, {"word": "FUR-MANE", "number": 1, "cat": 2, "t": [7]}]'::jsonb,
   '[{"name": "Toedscruel", "colour": "neutral", "position": 0}, {"name": "Illumise", "colour": "blue", "position": 1}, {"name": "Vileplume", "colour": "neutral", "position": 2}, {"name": "Chandelure", "colour": "blue", "position": 3}, {"name": "Volbeat", "colour": "blue", "position": 4}, {"name": "Sobble", "colour": "neutral", "position": 5}, {"name": "Orthworm", "colour": "neutral", "position": 6}, {"name": "Deino", "colour": "blue", "position": 7}, {"name": "Buizel", "colour": "blue", "position": 8}, {"name": "Volcanion", "colour": "neutral", "position": 9}, {"name": "Luxio", "colour": "neutral", "position": 10}, {"name": "Floatzel", "colour": "blue", "position": 11}, {"name": "Larvitar", "colour": "blue", "position": 12}, {"name": "Scolipede", "colour": "neutral", "position": 13}, {"name": "Misdreavus", "colour": "neutral", "position": 14}, {"name": "Squirtle", "colour": "neutral", "position": 15}, {"name": "Impidimp", "colour": "neutral", "position": 16}, {"name": "Scorbunny", "colour": "neutral", "position": 17}, {"name": "Slakoth", "colour": "neutral", "position": 18}, {"name": "Bagon", "colour": "blue", "position": 19}, {"name": "Skorupi", "colour": "neutral", "position": 20}, {"name": "Vivillon", "colour": "neutral", "position": 21}, {"name": "Pancham", "colour": "neutral", "position": 22}, {"name": "Swadloon", "colour": "neutral", "position": 23}, {"name": "Drilbur", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-05', 'gen1',
   '[{"word": "FERRY", "number": 1, "cat": 3, "t": [13], "explain": "It''s from their Pok\u00e9dex lore \u2014 it ferries travellers across the sea."}, {"word": "FOSSILISED", "number": 2, "cat": 5, "t": [17, 23], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re prehistoric fossils brought back to life."}, {"word": "JELLYFISH", "number": 2, "cat": 4, "t": [11, 14], "explain": "They''re all based on the real-world jellyfish."}, {"word": "SPHERE", "number": 2, "cat": 2, "t": [5, 22], "explain": "You can spot it on the sprite \u2014 a Pok\u00e9 Ball shape."}, {"word": "SLUDGE", "number": 2, "cat": 3, "t": [9, 16], "explain": "They''re all based on the real-world blob of living sludge."}]'::jsonb,
   '[{"word": "SHELL", "number": 1, "cat": 2, "t": [17]}, {"word": "SPIRAL-SHELL", "number": 1, "cat": 2, "t": [23]}, {"word": "OOZE-BODY", "number": 1, "cat": 2, "t": [16]}, {"word": "RED-JEWELS", "number": 1, "cat": 2, "t": [11]}, {"word": "FACE", "number": 1, "cat": 2, "t": [22]}, {"word": "SHELL-BACK", "number": 1, "cat": 2, "t": [13]}, {"word": "MINERAL", "number": 1, "cat": 3, "t": [5]}, {"word": "OOZING-BODY", "number": 1, "cat": 2, "t": [9]}, {"word": "CNIDARIAN", "number": 1, "cat": 3, "t": [14]}]'::jsonb,
   '[{"name": "Onix", "colour": "neutral", "position": 0}, {"name": "Dratini", "colour": "neutral", "position": 1}, {"name": "Ponyta", "colour": "neutral", "position": 2}, {"name": "Lickitung", "colour": "neutral", "position": 3}, {"name": "Primeape", "colour": "neutral", "position": 4}, {"name": "Electrode", "colour": "blue", "position": 5}, {"name": "Fearow", "colour": "neutral", "position": 6}, {"name": "Rhyhorn", "colour": "neutral", "position": 7}, {"name": "Jolteon", "colour": "neutral", "position": 8}, {"name": "Muk", "colour": "blue", "position": 9}, {"name": "Alakazam", "colour": "neutral", "position": 10}, {"name": "Tentacruel", "colour": "blue", "position": 11}, {"name": "Dewgong", "colour": "neutral", "position": 12}, {"name": "Lapras", "colour": "blue", "position": 13}, {"name": "Tentacool", "colour": "blue", "position": 14}, {"name": "Goldeen", "colour": "neutral", "position": 15}, {"name": "Grimer", "colour": "blue", "position": 16}, {"name": "Kabutops", "colour": "blue", "position": 17}, {"name": "Raticate", "colour": "neutral", "position": 18}, {"name": "Graveler", "colour": "neutral", "position": 19}, {"name": "Paras", "colour": "neutral", "position": 20}, {"name": "Gloom", "colour": "neutral", "position": 21}, {"name": "Voltorb", "colour": "blue", "position": 22}, {"name": "Omastar", "colour": "blue", "position": 23}, {"name": "Charmander", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-05', 'mixed',
   '[{"word": "FROG", "number": 2, "cat": 3, "t": [4, 14], "explain": "They''re all based on the real-world frog."}, {"word": "SQUID", "number": 2, "cat": 4, "t": [8, 22], "explain": "They''re all based on the real-world squid."}, {"word": "GEM", "number": 1, "cat": 2, "t": [18], "explain": "You can spot it on the sprite \u2014 a gemstone body."}, {"word": "HIVE", "number": 2, "cat": 3, "t": [11, 17], "explain": "They''re all based on the real-world bee."}, {"word": "MOLTEN", "number": 2, "cat": 3, "t": [1, 20], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re made of molten lava."}]'::jsonb,
   '[{"word": "INSECT", "number": 1, "cat": 3, "t": [17]}, {"word": "BUMPS", "number": 1, "cat": 2, "t": [4]}, {"word": "GLOW-SPOTS", "number": 1, "cat": 2, "t": [22]}, {"word": "CHEEK-VIBRATIONS", "number": 1, "cat": 2, "t": [14]}, {"word": "TENTACLE-ARMS", "number": 1, "cat": 2, "t": [8]}, {"word": "ROCK-SHELL", "number": 1, "cat": 2, "t": [20]}, {"word": "JEWEL-BODY", "number": 1, "cat": 2, "t": [18]}, {"word": "MOLTEN-BODY", "number": 1, "cat": 2, "t": [1]}, {"word": "THREE-FACES", "number": 1, "cat": 2, "t": [11]}]'::jsonb,
   '[{"name": "Fezandipiti", "colour": "neutral", "position": 0}, {"name": "Slugma", "colour": "blue", "position": 1}, {"name": "Flamigo", "colour": "neutral", "position": 2}, {"name": "Umbreon", "colour": "neutral", "position": 3}, {"name": "Palpitoad", "colour": "blue", "position": 4}, {"name": "Baltoy", "colour": "neutral", "position": 5}, {"name": "Dodrio", "colour": "neutral", "position": 6}, {"name": "Rowlet", "colour": "neutral", "position": 7}, {"name": "Malamar", "colour": "blue", "position": 8}, {"name": "Budew", "colour": "neutral", "position": 9}, {"name": "Skorupi", "colour": "neutral", "position": 10}, {"name": "Combee", "colour": "blue", "position": 11}, {"name": "Mightyena", "colour": "neutral", "position": 12}, {"name": "Wugtrio", "colour": "neutral", "position": 13}, {"name": "Tympole", "colour": "blue", "position": 14}, {"name": "Dudunsparce", "colour": "neutral", "position": 15}, {"name": "Grapploct", "colour": "neutral", "position": 16}, {"name": "Vespiquen", "colour": "blue", "position": 17}, {"name": "Carbink", "colour": "blue", "position": 18}, {"name": "Wimpod", "colour": "neutral", "position": 19}, {"name": "Magcargo", "colour": "blue", "position": 20}, {"name": "Solgaleo", "colour": "neutral", "position": 21}, {"name": "Inkay", "colour": "blue", "position": 22}, {"name": "Azumarill", "colour": "neutral", "position": 23}, {"name": "Onix", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-06', 'gen1',
   '[{"word": "SEA-DOG", "number": 2, "cat": 3, "t": [1, 23], "explain": "They''re all based on the real-world seal and sea lion."}, {"word": "UNICORN", "number": 2, "cat": 3, "t": [3, 5], "explain": "They''re all based on the real-world unicorn."}, {"word": "SUMO", "number": 2, "cat": 3, "t": [8, 24], "explain": "They''re based on sumo wrestlers."}, {"word": "SPORES", "number": 2, "cat": 2, "t": [4, 15], "explain": "You can spot it on the sprite \u2014 the spores it puffs out."}, {"word": "DUCK-KNIGHT", "number": 1, "cat": 4, "t": [20], "explain": "It''s from their Pok\u00e9dex lore \u2014 the spring onion (leek) it carries."}]'::jsonb,
   '[{"word": "HORN", "number": 1, "cat": 2, "t": [1]}, {"word": "POWER-SAVE-BELT", "number": 1, "cat": 2, "t": [24]}, {"word": "DROOL", "number": 1, "cat": 2, "t": [4]}, {"word": "SLEEK-BODY", "number": 1, "cat": 2, "t": [23]}, {"word": "MUSCLES", "number": 1, "cat": 2, "t": [8]}, {"word": "PLANT", "number": 1, "cat": 3, "t": [15]}, {"word": "BEAK", "number": 1, "cat": 2, "t": [20]}, {"word": "EQUINE", "number": 1, "cat": 3, "t": [3]}, {"word": "FIRE-MANE", "number": 1, "cat": 2, "t": [5]}]'::jsonb,
   '[{"name": "Charmeleon", "colour": "neutral", "position": 0}, {"name": "Seel", "colour": "blue", "position": 1}, {"name": "Exeggutor", "colour": "neutral", "position": 2}, {"name": "Rapidash", "colour": "blue", "position": 3}, {"name": "Gloom", "colour": "blue", "position": 4}, {"name": "Ponyta", "colour": "blue", "position": 5}, {"name": "Dratini", "colour": "neutral", "position": 6}, {"name": "Hypno", "colour": "neutral", "position": 7}, {"name": "Machop", "colour": "blue", "position": 8}, {"name": "Omastar", "colour": "neutral", "position": 9}, {"name": "Kangaskhan", "colour": "neutral", "position": 10}, {"name": "Nidoking", "colour": "neutral", "position": 11}, {"name": "Metapod", "colour": "neutral", "position": 12}, {"name": "Mew", "colour": "neutral", "position": 13}, {"name": "Doduo", "colour": "neutral", "position": 14}, {"name": "Vileplume", "colour": "blue", "position": 15}, {"name": "Slowbro", "colour": "neutral", "position": 16}, {"name": "Voltorb", "colour": "neutral", "position": 17}, {"name": "Wigglytuff", "colour": "neutral", "position": 18}, {"name": "Magikarp", "colour": "neutral", "position": 19}, {"name": "Farfetch''d", "colour": "blue", "position": 20}, {"name": "Primeape", "colour": "neutral", "position": 21}, {"name": "Goldeen", "colour": "neutral", "position": 22}, {"name": "Dewgong", "colour": "blue", "position": 23}, {"name": "Machoke", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-06', 'mixed',
   '[{"word": "PRIMATE", "number": 3, "cat": 3, "t": [4, 8, 24], "explain": "They''re all based on the real-world gorilla."}, {"word": "WATERBIRD", "number": 2, "cat": 3, "t": [20, 23], "explain": "They''re all based on the real-world swan."}, {"word": "WEASEL", "number": 2, "cat": 3, "t": [3, 19], "explain": "They''re all based on the real-world weasel."}, {"word": "SCARAB", "number": 1, "cat": 4, "t": [6], "explain": "They''re based on the scarab beetle."}, {"word": "HOARD", "number": 1, "cat": 2, "t": [10], "explain": "You can spot it on the sprite \u2014 a hoard of gold coins."}]'::jsonb,
   '[{"word": "LOG-DRUM", "number": 1, "cat": 2, "t": [8]}, {"word": "ROUND-BODY", "number": 1, "cat": 2, "t": [20]}, {"word": "LONG-BODY", "number": 1, "cat": 2, "t": [3]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [6]}, {"word": "PRIMATE", "number": 1, "cat": 3, "t": [24]}, {"word": "SCOUT-TAIL", "number": 1, "cat": 2, "t": [19]}, {"word": "LONG-NECK", "number": 1, "cat": 2, "t": [23]}, {"word": "CHEST-BODY", "number": 1, "cat": 2, "t": [10]}, {"word": "BEAT", "number": 1, "cat": 2, "t": [4]}]'::jsonb,
   '[{"name": "Drowzee", "colour": "neutral", "position": 0}, {"name": "Corsola", "colour": "neutral", "position": 1}, {"name": "Pidgey", "colour": "neutral", "position": 2}, {"name": "Furret", "colour": "blue", "position": 3}, {"name": "Thwackey", "colour": "blue", "position": 4}, {"name": "Yungoos", "colour": "neutral", "position": 5}, {"name": "Nincada", "colour": "blue", "position": 6}, {"name": "Timburr", "colour": "neutral", "position": 7}, {"name": "Rillaboom", "colour": "blue", "position": 8}, {"name": "Keldeo", "colour": "neutral", "position": 9}, {"name": "Gimmighoul", "colour": "blue", "position": 10}, {"name": "Jellicent", "colour": "neutral", "position": 11}, {"name": "Pupitar", "colour": "neutral", "position": 12}, {"name": "Gastrodon", "colour": "neutral", "position": 13}, {"name": "Lickitung", "colour": "neutral", "position": 14}, {"name": "Salamence", "colour": "neutral", "position": 15}, {"name": "Weepinbell", "colour": "neutral", "position": 16}, {"name": "Basculegion", "colour": "neutral", "position": 17}, {"name": "Staryu", "colour": "neutral", "position": 18}, {"name": "Sentret", "colour": "blue", "position": 19}, {"name": "Ducklett", "colour": "blue", "position": 20}, {"name": "Rapidash", "colour": "neutral", "position": 21}, {"name": "Lunatone", "colour": "neutral", "position": 22}, {"name": "Swanna", "colour": "blue", "position": 23}, {"name": "Grookey", "colour": "blue", "position": 24}]'::jsonb)
on conflict (puzzle_date, pool) do update
  set clues = excluded.clues, hints = excluded.hints, tiles = excluded.tiles;
