-- 31_updates.sql
--
-- Two daily-puzzle upgrades (batched with the Aug 31 - Sep 6 puzzle data below):
--
--   (1) Per-clue explanations. Each base clue now carries an "explain" sentence
--       (why the clue points at those Pokemon + which category it is). The end
--       screen shows it under each clue. get_daily_puzzle strips it mid-game so
--       it can't leak the answers early.
--
--   (2) Offline play. New RPC get_daily_full returns the whole puzzle "sealed":
--       the colour key + hints (with targets) + clues (with targets and
--       explanations), XOR-obfuscated + base64 so it isn't plain text in the
--       network response. The client unseals it once at load and then does every
--       reveal / hint / finish LOCALLY, so a player who loses connection after
--       the page has loaded can still finish the puzzle.
--
-- Safe to re-run (create-or-replace + upsert).

-- ----------------------------------------------------------------------------
-- _daily_seal: XOR-obfuscate a jsonb payload with a fixed repeating key, then
-- base64-encode it. The matching key + un-seal live in app.js. This is light
-- obfuscation (not encryption) - enough that the answers aren't readable at a
-- glance, while letting the whole puzzle be played offline once loaded.
-- ----------------------------------------------------------------------------
create or replace function public._daily_seal(p jsonb)
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  b bytea;
  i int;
  n int;
  k int[] := array[142,55,91,44,116,17,163];
begin
  b := convert_to(p::text, 'UTF8');
  n := octet_length(b);
  for i in 0..n-1 loop
    b := set_byte(b, i, get_byte(b, i) # k[(i % 7) + 1]);
  end loop;
  return encode(b, 'base64');
end;
$$;

-- ----------------------------------------------------------------------------
-- get_daily_puzzle: serve today's board + base clues WITHOUT target positions
-- OR the explanation text (both must stay hidden until the game ends).
-- ----------------------------------------------------------------------------
create or replace function public.get_daily_puzzle(p_pool text)
returns table(puzzle_date date, clues jsonb, tiles jsonb)
language sql
security definer
set search_path = public
as $$
  select dp.puzzle_date,
    (
      select jsonb_agg((c - 't' - 'explain') order by ord)
      from jsonb_array_elements(dp.clues) with ordinality as x(c, ord)
    ) as clues,
    (
      select jsonb_agg(
        jsonb_build_object(
          'position',   (t->>'position')::int,
          'name',       t->>'name',
          'pokemon_id', pk.id,
          'sprite_url', pk.sprite_url
        ) order by (t->>'position')::int
      )
      from jsonb_array_elements(dp.tiles) t
      left join pokemon pk on lower(pk.name) = lower(t->>'name')
    ) as tiles
  from daily_puzzles dp
  where dp.pool = p_pool and dp.puzzle_date <= current_date
  order by dp.puzzle_date desc
  limit 1;
$$;

-- ----------------------------------------------------------------------------
-- get_daily_full: today's board (tiles WITHOUT colours, for rendering) plus a
-- sealed blob carrying everything needed to play + finish OFFLINE:
--   c = { position -> colour },  h = hints (with t),  k = clues (with t+explain)
-- ----------------------------------------------------------------------------
create or replace function public.get_daily_full(p_pool text)
returns table(puzzle_date date, tiles jsonb, sealed text)
language sql
security definer
set search_path = public
as $$
  select dp.puzzle_date,
    (
      select jsonb_agg(
        jsonb_build_object(
          'position',   (t->>'position')::int,
          'name',       t->>'name',
          'pokemon_id', pk.id,
          'sprite_url', pk.sprite_url
        ) order by (t->>'position')::int
      )
      from jsonb_array_elements(dp.tiles) t
      left join pokemon pk on lower(pk.name) = lower(t->>'name')
    ) as tiles,
    public._daily_seal(jsonb_build_object(
      'c', (
        select jsonb_object_agg(t->>'position', t->>'colour')
        from jsonb_array_elements(dp.tiles) t
      ),
      'h', coalesce(dp.hints, '[]'::jsonb),
      'k', dp.clues
    )) as sealed
  from daily_puzzles dp
  where dp.pool = p_pool and dp.puzzle_date <= current_date
  order by dp.puzzle_date desc
  limit 1;
$$;

grant execute on function public.get_daily_puzzle(text) to authenticated;
grant execute on function public.get_daily_full(text)   to authenticated;


-- ------------------------------------------------------------------
-- Puzzle data: 2026-08-31 .. 2026-09-06 (fact-bank authored, with per-clue explanations).

insert into public.daily_puzzles (puzzle_date, pool, clues, hints, tiles) values
  ('2026-08-31', 'gen1',
   '[{"word": "PUNCH", "number": 2, "cat": 2, "t": [2, 21], "explain": "You can spot it on the sprite \u2014 the raised fists."}, {"word": "PSYCHIC", "number": 2, "cat": 1, "t": [5, 10], "explain": "Every one is a Psychic-type."}, {"word": "BOULDER", "number": 2, "cat": 3, "t": [7, 15], "explain": "They''re all based on the real-world rock golem."}, {"word": "POLLINATOR", "number": 1, "cat": 3, "t": [8], "explain": "They''re all based on the real-world butterfly."}, {"word": "GRASS", "number": 2, "cat": 1, "t": [12, 22], "explain": "Every one is a Grass-type."}]'::jsonb,
   '[{"word": "SHELL-PLATES", "number": 1, "cat": 2, "t": [7]}, {"word": "LEAF-HEAD", "number": 1, "cat": 2, "t": [22]}, {"word": "FLOWER-HEAD", "number": 1, "cat": 2, "t": [12]}, {"word": "TAIL", "number": 1, "cat": 2, "t": [21]}, {"word": "BIG-EYES", "number": 1, "cat": 2, "t": [8]}, {"word": "PRIMATE", "number": 1, "cat": 3, "t": [2]}, {"word": "SLEEPS-18H", "number": 1, "cat": 2, "t": [10]}, {"word": "ROCKY-BODY", "number": 1, "cat": 2, "t": [15]}, {"word": "PENDULUM-HANDS", "number": 1, "cat": 2, "t": [5]}]'::jsonb,
   '[{"name": "Cloyster", "colour": "neutral", "position": 0}, {"name": "Koffing", "colour": "neutral", "position": 1}, {"name": "Machoke", "colour": "blue", "position": 2}, {"name": "Magikarp", "colour": "neutral", "position": 3}, {"name": "Dragonair", "colour": "neutral", "position": 4}, {"name": "Drowzee", "colour": "blue", "position": 5}, {"name": "Farfetch''d", "colour": "neutral", "position": 6}, {"name": "Golem", "colour": "blue", "position": 7}, {"name": "Butterfree", "colour": "blue", "position": 8}, {"name": "Clefairy", "colour": "neutral", "position": 9}, {"name": "Abra", "colour": "blue", "position": 10}, {"name": "Weedle", "colour": "neutral", "position": 11}, {"name": "Gloom", "colour": "blue", "position": 12}, {"name": "Vulpix", "colour": "neutral", "position": 13}, {"name": "Magnemite", "colour": "neutral", "position": 14}, {"name": "Geodude", "colour": "blue", "position": 15}, {"name": "Eevee", "colour": "neutral", "position": 16}, {"name": "Arcanine", "colour": "neutral", "position": 17}, {"name": "Gyarados", "colour": "neutral", "position": 18}, {"name": "Seel", "colour": "neutral", "position": 19}, {"name": "Electrode", "colour": "neutral", "position": 20}, {"name": "Machop", "colour": "blue", "position": 21}, {"name": "Oddish", "colour": "blue", "position": 22}, {"name": "Rattata", "colour": "neutral", "position": 23}, {"name": "Persian", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-31', 'mixed',
   '[{"word": "DRAGON", "number": 2, "cat": 1, "t": [4, 23], "explain": "Every one is a Dragon-type."}, {"word": "WATER", "number": 2, "cat": 1, "t": [1, 22], "explain": "Every one is a Water-type."}, {"word": "FOX", "number": 2, "cat": 3, "t": [8, 9], "explain": "They''re all based on the real-world fox."}, {"word": "GRUB", "number": 2, "cat": 3, "t": [2, 11], "explain": "They''re all based on the real-world caterpillar."}, {"word": "TOADSTOOL", "number": 1, "cat": 2, "t": [18], "explain": "You can spot it on the sprite \u2014 the mushroom on its back."}]'::jsonb,
   '[{"word": "HORN-TOOTH", "number": 1, "cat": 2, "t": [22]}, {"word": "INSECT", "number": 1, "cat": 3, "t": [2]}, {"word": "JAWS", "number": 1, "cat": 2, "t": [4]}, {"word": "LEAF-HOOD", "number": 1, "cat": 2, "t": [11]}, {"word": "DRAGON", "number": 1, "cat": 3, "t": [23]}, {"word": "BEAK", "number": 1, "cat": 2, "t": [1]}, {"word": "EAR-TUFTS", "number": 1, "cat": 2, "t": [9]}, {"word": "CAP", "number": 1, "cat": 2, "t": [18]}, {"word": "TWIG-WAND", "number": 1, "cat": 2, "t": [8]}]'::jsonb,
   '[{"name": "Koffing", "colour": "neutral", "position": 0}, {"name": "Wingull", "colour": "blue", "position": 1}, {"name": "Swadloon", "colour": "blue", "position": 2}, {"name": "Clobbopus", "colour": "neutral", "position": 3}, {"name": "Gible", "colour": "blue", "position": 4}, {"name": "Cleffa", "colour": "neutral", "position": 5}, {"name": "Pachirisu", "colour": "neutral", "position": 6}, {"name": "Persian", "colour": "neutral", "position": 7}, {"name": "Braixen", "colour": "blue", "position": 8}, {"name": "Fennekin", "colour": "blue", "position": 9}, {"name": "Hariyama", "colour": "neutral", "position": 10}, {"name": "Sewaddle", "colour": "blue", "position": 11}, {"name": "Necrozma", "colour": "neutral", "position": 12}, {"name": "Wynaut", "colour": "neutral", "position": 13}, {"name": "Marowak", "colour": "neutral", "position": 14}, {"name": "Mime Jr.", "colour": "neutral", "position": 15}, {"name": "Masquerain", "colour": "neutral", "position": 16}, {"name": "Ninetales", "colour": "neutral", "position": 17}, {"name": "Shroomish", "colour": "blue", "position": 18}, {"name": "Litten", "colour": "neutral", "position": 19}, {"name": "Shinx", "colour": "neutral", "position": 20}, {"name": "Meowstic", "colour": "neutral", "position": 21}, {"name": "Chewtle", "colour": "blue", "position": 22}, {"name": "Jangmo-o", "colour": "blue", "position": 23}, {"name": "Bastiodon", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-01', 'gen1',
   '[{"word": "ROCK", "number": 2, "cat": 1, "t": [1, 11], "explain": "Every one is a Rock-type."}, {"word": "SEEDS", "number": 1, "cat": 2, "t": [20], "explain": "You can spot it on the sprite \u2014 the seeds on its body."}, {"word": "ELECTRIC", "number": 2, "cat": 1, "t": [14, 24], "explain": "Every one is a Electric-type."}, {"word": "DRACULA", "number": 2, "cat": 4, "t": [9, 18], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re vampire bats."}, {"word": "GROUND", "number": 2, "cat": 1, "t": [6, 13], "explain": "Every one is a Ground-type."}]'::jsonb,
   '[{"word": "TENTACLES", "number": 1, "cat": 2, "t": [1]}, {"word": "MINERAL", "number": 1, "cat": 3, "t": [14]}, {"word": "NO-EYES", "number": 1, "cat": 2, "t": [9]}, {"word": "RED-EYES", "number": 1, "cat": 2, "t": [11]}, {"word": "HUGE-MOUTH", "number": 1, "cat": 2, "t": [18]}, {"word": "CRACKS", "number": 1, "cat": 2, "t": [20]}, {"word": "CURL", "number": 1, "cat": 2, "t": [6]}, {"word": "SINGLE-EYE", "number": 1, "cat": 2, "t": [24]}, {"word": "BACK-SPIKES", "number": 1, "cat": 2, "t": [13]}]'::jsonb,
   '[{"name": "Poliwag", "colour": "neutral", "position": 0}, {"name": "Omanyte", "colour": "blue", "position": 1}, {"name": "Ponyta", "colour": "neutral", "position": 2}, {"name": "Slowpoke", "colour": "neutral", "position": 3}, {"name": "Charmander", "colour": "neutral", "position": 4}, {"name": "Haunter", "colour": "neutral", "position": 5}, {"name": "Sandshrew", "colour": "blue", "position": 6}, {"name": "Venomoth", "colour": "neutral", "position": 7}, {"name": "Eevee", "colour": "neutral", "position": 8}, {"name": "Zubat", "colour": "blue", "position": 9}, {"name": "Butterfree", "colour": "neutral", "position": 10}, {"name": "Kabuto", "colour": "blue", "position": 11}, {"name": "Fearow", "colour": "neutral", "position": 12}, {"name": "Sandslash", "colour": "blue", "position": 13}, {"name": "Magneton", "colour": "blue", "position": 14}, {"name": "Paras", "colour": "neutral", "position": 15}, {"name": "Vulpix", "colour": "neutral", "position": 16}, {"name": "Mewtwo", "colour": "neutral", "position": 17}, {"name": "Golbat", "colour": "blue", "position": 18}, {"name": "Weepinbell", "colour": "neutral", "position": 19}, {"name": "Exeggcute", "colour": "blue", "position": 20}, {"name": "Gyarados", "colour": "neutral", "position": 21}, {"name": "Horsea", "colour": "neutral", "position": 22}, {"name": "Venusaur", "colour": "neutral", "position": 23}, {"name": "Magnemite", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-01', 'mixed',
   '[{"word": "FAIRY", "number": 2, "cat": 1, "t": [5, 17], "explain": "Every one is a Fairy-type."}, {"word": "ELECTRIC", "number": 2, "cat": 1, "t": [4, 20], "explain": "Every one is a Electric-type."}, {"word": "RAVEN", "number": 2, "cat": 3, "t": [8, 16], "explain": "They''re all based on the real-world crow."}, {"word": "GROUND", "number": 2, "cat": 1, "t": [0, 12], "explain": "Every one is a Ground-type."}, {"word": "SNAIL", "number": 1, "cat": 3, "t": [3], "explain": "They''re all based on the real-world snail."}]'::jsonb,
   '[{"word": "SAND-BODY", "number": 1, "cat": 2, "t": [12]}, {"word": "WITCH-HAT-CREST", "number": 1, "cat": 2, "t": [8]}, {"word": "WINGS", "number": 1, "cat": 2, "t": [5]}, {"word": "FAIRY", "number": 1, "cat": 3, "t": [17]}, {"word": "FEDORA-CREST", "number": 1, "cat": 2, "t": [16]}, {"word": "FRILLS", "number": 1, "cat": 2, "t": [3]}, {"word": "CHEEKS", "number": 1, "cat": 2, "t": [20]}, {"word": "CORGI", "number": 1, "cat": 3, "t": [4]}, {"word": "TRUNK", "number": 1, "cat": 2, "t": [0]}]'::jsonb,
   '[{"name": "Phanpy", "colour": "blue", "position": 0}, {"name": "Eternatus", "colour": "neutral", "position": 1}, {"name": "Orbeetle", "colour": "neutral", "position": 2}, {"name": "Shellos", "colour": "blue", "position": 3}, {"name": "Yamper", "colour": "blue", "position": 4}, {"name": "Togetic", "colour": "blue", "position": 5}, {"name": "Pinsir", "colour": "neutral", "position": 6}, {"name": "Vespiquen", "colour": "neutral", "position": 7}, {"name": "Murkrow", "colour": "blue", "position": 8}, {"name": "Happiny", "colour": "neutral", "position": 9}, {"name": "Spearow", "colour": "neutral", "position": 10}, {"name": "Solgaleo", "colour": "neutral", "position": 11}, {"name": "Hippopotas", "colour": "blue", "position": 12}, {"name": "Gothitelle", "colour": "neutral", "position": 13}, {"name": "Cranidos", "colour": "neutral", "position": 14}, {"name": "Regice", "colour": "neutral", "position": 15}, {"name": "Honchkrow", "colour": "blue", "position": 16}, {"name": "Togepi", "colour": "blue", "position": 17}, {"name": "Overqwil", "colour": "neutral", "position": 18}, {"name": "Gastly", "colour": "neutral", "position": 19}, {"name": "Pichu", "colour": "blue", "position": 20}, {"name": "Toxicroak", "colour": "neutral", "position": 21}, {"name": "Pidgeot", "colour": "neutral", "position": 22}, {"name": "Loudred", "colour": "neutral", "position": 23}, {"name": "Torchic", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-02', 'gen1',
   '[{"word": "SOPRANO", "number": 1, "cat": 4, "t": [23], "explain": "It''s from their Pok\u00e9dex lore \u2014 an opera diva / snow-hag."}, {"word": "TELEPORT", "number": 2, "cat": 3, "t": [0, 12], "explain": "It''s from their Pok\u00e9dex lore \u2014 its signature Teleport move."}, {"word": "SKULL-MASK", "number": 2, "cat": 3, "t": [11, 17], "explain": "They''re based on the bone club and skull helmet it wears."}, {"word": "BUG", "number": 2, "cat": 1, "t": [6, 13], "explain": "Every one is a Bug-type."}, {"word": "POISON", "number": 2, "cat": 1, "t": [8, 22], "explain": "Every one is a Poison-type."}]'::jsonb,
   '[{"word": "GOWN", "number": 1, "cat": 2, "t": [23]}, {"word": "TWIN-SPOONS", "number": 1, "cat": 2, "t": [12]}, {"word": "RODENT", "number": 1, "cat": 3, "t": [22]}, {"word": "ANTENNA", "number": 1, "cat": 2, "t": [6]}, {"word": "SPINES", "number": 1, "cat": 2, "t": [8]}, {"word": "SPOON", "number": 1, "cat": 2, "t": [0]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [13]}, {"word": "SKULL-HELMET", "number": 1, "cat": 2, "t": [17]}, {"word": "MAMMAL", "number": 1, "cat": 3, "t": [11]}]'::jsonb,
   '[{"name": "Kadabra", "colour": "blue", "position": 0}, {"name": "Doduo", "colour": "neutral", "position": 1}, {"name": "Sandshrew", "colour": "neutral", "position": 2}, {"name": "Magnemite", "colour": "neutral", "position": 3}, {"name": "Primeape", "colour": "neutral", "position": 4}, {"name": "Seel", "colour": "neutral", "position": 5}, {"name": "Caterpie", "colour": "blue", "position": 6}, {"name": "Sandslash", "colour": "neutral", "position": 7}, {"name": "Nidorino", "colour": "blue", "position": 8}, {"name": "Zapdos", "colour": "neutral", "position": 9}, {"name": "Poliwag", "colour": "neutral", "position": 10}, {"name": "Marowak", "colour": "blue", "position": 11}, {"name": "Alakazam", "colour": "blue", "position": 12}, {"name": "Paras", "colour": "blue", "position": 13}, {"name": "Farfetch''d", "colour": "neutral", "position": 14}, {"name": "Vulpix", "colour": "neutral", "position": 15}, {"name": "Omanyte", "colour": "neutral", "position": 16}, {"name": "Cubone", "colour": "blue", "position": 17}, {"name": "Spearow", "colour": "neutral", "position": 18}, {"name": "Golduck", "colour": "neutral", "position": 19}, {"name": "Onix", "colour": "neutral", "position": 20}, {"name": "Dragonair", "colour": "neutral", "position": 21}, {"name": "Nidorina", "colour": "blue", "position": 22}, {"name": "Jynx", "colour": "blue", "position": 23}, {"name": "Horsea", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-02', 'mixed',
   '[{"word": "TAPIR", "number": 2, "cat": 3, "t": [5, 13], "explain": "They''re all based on the real-world tapir (a dream-eating baku)."}, {"word": "ACORN", "number": 1, "cat": 2, "t": [8], "explain": "You can spot it on the sprite \u2014 the acorn cap."}, {"word": "FIGHTING", "number": 2, "cat": 1, "t": [4, 21], "explain": "Every one is a Fighting-type."}, {"word": "ICE", "number": 2, "cat": 1, "t": [20, 23], "explain": "Every one is a Ice-type."}, {"word": "GATOR", "number": 2, "cat": 3, "t": [2, 7], "explain": "They''re all based on the real-world crocodile."}]'::jsonb,
   '[{"word": "ICE-BLOCK", "number": 1, "cat": 2, "t": [23]}, {"word": "FOREHEAD", "number": 1, "cat": 2, "t": [5]}, {"word": "ACORN-BODY", "number": 1, "cat": 2, "t": [8]}, {"word": "LOTUS-POSE", "number": 1, "cat": 2, "t": [21]}, {"word": "FLOWER-PATTERN", "number": 1, "cat": 2, "t": [13]}, {"word": "HOOD-BODY", "number": 1, "cat": 2, "t": [20]}, {"word": "BIG", "number": 1, "cat": 2, "t": [7]}, {"word": "JAWS", "number": 1, "cat": 2, "t": [2]}, {"word": "BIG-FISTS", "number": 1, "cat": 2, "t": [4]}]'::jsonb,
   '[{"name": "Dusclops", "colour": "neutral", "position": 0}, {"name": "Misdreavus", "colour": "neutral", "position": 1}, {"name": "Totodile", "colour": "blue", "position": 2}, {"name": "Shieldon", "colour": "neutral", "position": 3}, {"name": "Makuhita", "colour": "blue", "position": 4}, {"name": "Musharna", "colour": "blue", "position": 5}, {"name": "Sandygast", "colour": "neutral", "position": 6}, {"name": "Croconaw", "colour": "blue", "position": 7}, {"name": "Seedot", "colour": "blue", "position": 8}, {"name": "Dugtrio", "colour": "neutral", "position": 9}, {"name": "Pikachu", "colour": "neutral", "position": 10}, {"name": "Azurill", "colour": "neutral", "position": 11}, {"name": "Eldegoss", "colour": "neutral", "position": 12}, {"name": "Munna", "colour": "blue", "position": 13}, {"name": "Karrablast", "colour": "neutral", "position": 14}, {"name": "Vullaby", "colour": "neutral", "position": 15}, {"name": "Vulpix", "colour": "neutral", "position": 16}, {"name": "Electivire", "colour": "neutral", "position": 17}, {"name": "Porygon", "colour": "neutral", "position": 18}, {"name": "Wishiwashi", "colour": "neutral", "position": 19}, {"name": "Snorunt", "colour": "blue", "position": 20}, {"name": "Meditite", "colour": "blue", "position": 21}, {"name": "Chimchar", "colour": "neutral", "position": 22}, {"name": "Bergmite", "colour": "blue", "position": 23}, {"name": "Weedle", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-03', 'gen1',
   '[{"word": "PINCERS", "number": 2, "cat": 2, "t": [5, 20], "explain": "You can spot it on the sprite \u2014 the big pincers."}, {"word": "DUX", "number": 2, "cat": 3, "t": [12, 14], "explain": "They''re all based on the real-world duck."}, {"word": "SERPENT", "number": 1, "cat": 3, "t": [2], "explain": "They''re all based on the real-world eel and sea-serpent."}, {"word": "GENIE", "number": 1, "cat": 5, "t": [23], "explain": "It''s from their Pok\u00e9dex lore \u2014 a mythical dragon."}, {"word": "FIRST-CHOICE", "number": 3, "cat": 1, "t": [7, 11, 21], "explain": "They''re first-partner (starter) Pok\u00e9mon."}]'::jsonb,
   '[{"word": "PLATYPUS", "number": 1, "cat": 3, "t": [14]}, {"word": "PINCERS", "number": 1, "cat": 2, "t": [5]}, {"word": "SERPENT-BODY", "number": 1, "cat": 2, "t": [2]}, {"word": "SERPENT", "number": 1, "cat": 3, "t": [23]}, {"word": "FLAME-TAIL", "number": 1, "cat": 2, "t": [21]}, {"word": "SHELL", "number": 1, "cat": 2, "t": [11]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [7]}, {"word": "HUGE-CLAW", "number": 1, "cat": 2, "t": [20]}, {"word": "WEBBED", "number": 1, "cat": 2, "t": [12]}]'::jsonb,
   '[{"name": "Pidgeot", "colour": "neutral", "position": 0}, {"name": "Graveler", "colour": "neutral", "position": 1}, {"name": "Gyarados", "colour": "blue", "position": 2}, {"name": "Exeggcute", "colour": "neutral", "position": 3}, {"name": "Omanyte", "colour": "neutral", "position": 4}, {"name": "Krabby", "colour": "blue", "position": 5}, {"name": "Starmie", "colour": "neutral", "position": 6}, {"name": "Bulbasaur", "colour": "blue", "position": 7}, {"name": "Clefairy", "colour": "neutral", "position": 8}, {"name": "Golem", "colour": "neutral", "position": 9}, {"name": "Kakuna", "colour": "neutral", "position": 10}, {"name": "Squirtle", "colour": "blue", "position": 11}, {"name": "Golduck", "colour": "blue", "position": 12}, {"name": "Mr. Mime", "colour": "neutral", "position": 13}, {"name": "Psyduck", "colour": "blue", "position": 14}, {"name": "Onix", "colour": "neutral", "position": 15}, {"name": "Seaking", "colour": "neutral", "position": 16}, {"name": "Poliwag", "colour": "neutral", "position": 17}, {"name": "Snorlax", "colour": "neutral", "position": 18}, {"name": "Muk", "colour": "neutral", "position": 19}, {"name": "Kingler", "colour": "blue", "position": 20}, {"name": "Charmander", "colour": "blue", "position": 21}, {"name": "Koffing", "colour": "neutral", "position": 22}, {"name": "Dratini", "colour": "blue", "position": 23}, {"name": "Grimer", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-03', 'mixed',
   '[{"word": "EIGHT-ARMS", "number": 1, "cat": 4, "t": [22], "explain": "They''re all based on the real-world octopus."}, {"word": "SICKLE", "number": 2, "cat": 2, "t": [15, 19], "explain": "You can spot it on the sprite \u2014 the scythe-shaped arms."}, {"word": "LAZYBONES", "number": 1, "cat": 3, "t": [24], "explain": "They''re all based on the real-world sloth."}, {"word": "LEGENDARY", "number": 3, "cat": 1, "t": [8, 9, 13], "explain": "They''re all Legendary Pok\u00e9mon."}, {"word": "SIMIAN", "number": 2, "cat": 3, "t": [0, 14], "explain": "They''re all based on the real-world monkey."}]'::jsonb,
   '[{"word": "DOT-FACE", "number": 1, "cat": 2, "t": [8]}, {"word": "PRIMATE", "number": 1, "cat": 3, "t": [0]}, {"word": "LEAF-SCYTHES", "number": 1, "cat": 2, "t": [15]}, {"word": "CEPHALOPOD", "number": 1, "cat": 3, "t": [22]}, {"word": "LAZY-FACE", "number": 1, "cat": 2, "t": [24]}, {"word": "BLUE-BODY", "number": 1, "cat": 2, "t": [9]}, {"word": "LEAF-CROWN", "number": 1, "cat": 2, "t": [14]}, {"word": "PETAL-BLADES", "number": 1, "cat": 2, "t": [19]}, {"word": "METAL-BODY", "number": 1, "cat": 2, "t": [13]}]'::jsonb,
   '[{"name": "Panpour", "colour": "blue", "position": 0}, {"name": "Ting-Lu", "colour": "neutral", "position": 1}, {"name": "Fraxure", "colour": "neutral", "position": 2}, {"name": "Corphish", "colour": "neutral", "position": 3}, {"name": "Misdreavus", "colour": "neutral", "position": 4}, {"name": "Goldeen", "colour": "neutral", "position": 5}, {"name": "Golduck", "colour": "neutral", "position": 6}, {"name": "Flareon", "colour": "neutral", "position": 7}, {"name": "Regirock", "colour": "blue", "position": 8}, {"name": "Regice", "colour": "blue", "position": 9}, {"name": "Skuntank", "colour": "neutral", "position": 10}, {"name": "Exeggutor", "colour": "neutral", "position": 11}, {"name": "Gastrodon", "colour": "neutral", "position": 12}, {"name": "Registeel", "colour": "blue", "position": 13}, {"name": "Pansage", "colour": "blue", "position": 14}, {"name": "Fomantis", "colour": "blue", "position": 15}, {"name": "Nymble", "colour": "neutral", "position": 16}, {"name": "Weedle", "colour": "neutral", "position": 17}, {"name": "Mew", "colour": "neutral", "position": 18}, {"name": "Lurantis", "colour": "blue", "position": 19}, {"name": "Shiinotic", "colour": "neutral", "position": 20}, {"name": "Watchog", "colour": "neutral", "position": 21}, {"name": "Grapploct", "colour": "blue", "position": 22}, {"name": "Grumpig", "colour": "neutral", "position": 23}, {"name": "Slakoth", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-04', 'gen1',
   '[{"word": "FELINE", "number": 1, "cat": 3, "t": [20], "explain": "They''re all based on the real-world cat."}, {"word": "RHINO", "number": 2, "cat": 3, "t": [5, 8], "explain": "They''re all based on the real-world rhinoceros."}, {"word": "COIN", "number": 1, "cat": 2, "t": [24], "explain": "You can spot it on the sprite \u2014 the gold coin on its forehead."}, {"word": "BRANCH-EVO", "number": 3, "cat": 1, "t": [4, 10, 12], "explain": "They''re all part of the Eevee family."}, {"word": "COBRA", "number": 2, "cat": 3, "t": [1, 18], "explain": "They''re all based on the real-world cobra."}]'::jsonb,
   '[{"word": "MAMMAL", "number": 1, "cat": 3, "t": [4]}, {"word": "TAIL", "number": 1, "cat": 2, "t": [8]}, {"word": "FINS", "number": 1, "cat": 2, "t": [12]}, {"word": "FELINE", "number": 1, "cat": 3, "t": [20]}, {"word": "ARMOUR-HIDE", "number": 1, "cat": 2, "t": [5]}, {"word": "FLUFFY-COLLAR", "number": 1, "cat": 2, "t": [10]}, {"word": "SERPENT", "number": 1, "cat": 3, "t": [18]}, {"word": "CAT", "number": 1, "cat": 3, "t": [24]}, {"word": "RATTLE-TAIL", "number": 1, "cat": 2, "t": [1]}]'::jsonb,
   '[{"name": "Nidoqueen", "colour": "neutral", "position": 0}, {"name": "Ekans", "colour": "blue", "position": 1}, {"name": "Dewgong", "colour": "neutral", "position": 2}, {"name": "Moltres", "colour": "neutral", "position": 3}, {"name": "Jolteon", "colour": "blue", "position": 4}, {"name": "Rhyhorn", "colour": "blue", "position": 5}, {"name": "Haunter", "colour": "neutral", "position": 6}, {"name": "Machamp", "colour": "neutral", "position": 7}, {"name": "Rhydon", "colour": "blue", "position": 8}, {"name": "Zapdos", "colour": "neutral", "position": 9}, {"name": "Eevee", "colour": "blue", "position": 10}, {"name": "Nidorina", "colour": "neutral", "position": 11}, {"name": "Vaporeon", "colour": "blue", "position": 12}, {"name": "Pikachu", "colour": "neutral", "position": 13}, {"name": "Snorlax", "colour": "neutral", "position": 14}, {"name": "Golem", "colour": "neutral", "position": 15}, {"name": "Dodrio", "colour": "neutral", "position": 16}, {"name": "Clefable", "colour": "neutral", "position": 17}, {"name": "Arbok", "colour": "blue", "position": 18}, {"name": "Alakazam", "colour": "neutral", "position": 19}, {"name": "Persian", "colour": "blue", "position": 20}, {"name": "Kangaskhan", "colour": "neutral", "position": 21}, {"name": "Staryu", "colour": "neutral", "position": 22}, {"name": "Pidgey", "colour": "neutral", "position": 23}, {"name": "Meowth", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-04', 'mixed',
   '[{"word": "FIREFLY", "number": 2, "cat": 3, "t": [3, 20], "explain": "They''re all based on the real-world firefly."}, {"word": "LANTERN", "number": 1, "cat": 4, "t": [24], "explain": "They''re based on a haunted lantern."}, {"word": "MOLE", "number": 1, "cat": 3, "t": [23], "explain": "They''re all based on the real-world mole."}, {"word": "PSEUDO-LEGENDARY", "number": 3, "cat": 1, "t": [8, 9, 12], "explain": "They''re pseudo-legendary Pok\u00e9mon."}, {"word": "OTTER", "number": 2, "cat": 3, "t": [7, 14], "explain": "They''re all based on the real-world sea otter."}]'::jsonb,
   '[{"word": "FINS", "number": 1, "cat": 2, "t": [7]}, {"word": "FLAMES", "number": 1, "cat": 2, "t": [24]}, {"word": "FUR-MANE", "number": 1, "cat": 2, "t": [12]}, {"word": "TWIN-TAILS", "number": 1, "cat": 2, "t": [14]}, {"word": "LIGHT-TAIL", "number": 1, "cat": 2, "t": [20]}, {"word": "HEADBUTTS", "number": 1, "cat": 3, "t": [9]}, {"word": "ANTENNAE", "number": 1, "cat": 2, "t": [3]}, {"word": "BELLY-PLATE", "number": 1, "cat": 2, "t": [8]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [23]}]'::jsonb,
   '[{"name": "Mime Jr.", "colour": "neutral", "position": 0}, {"name": "Serperior", "colour": "neutral", "position": 1}, {"name": "Dondozo", "colour": "neutral", "position": 2}, {"name": "Illumise", "colour": "blue", "position": 3}, {"name": "Chespin", "colour": "neutral", "position": 4}, {"name": "Dachsbun", "colour": "neutral", "position": 5}, {"name": "Jynx", "colour": "neutral", "position": 6}, {"name": "Floatzel", "colour": "blue", "position": 7}, {"name": "Larvitar", "colour": "blue", "position": 8}, {"name": "Bagon", "colour": "blue", "position": 9}, {"name": "Charizard", "colour": "neutral", "position": 10}, {"name": "Simipour", "colour": "neutral", "position": 11}, {"name": "Deino", "colour": "blue", "position": 12}, {"name": "Blipbug", "colour": "neutral", "position": 13}, {"name": "Buizel", "colour": "blue", "position": 14}, {"name": "Kricketot", "colour": "neutral", "position": 15}, {"name": "Heliolisk", "colour": "neutral", "position": 16}, {"name": "Nosepass", "colour": "neutral", "position": 17}, {"name": "Aipom", "colour": "neutral", "position": 18}, {"name": "Fuecoco", "colour": "neutral", "position": 19}, {"name": "Volbeat", "colour": "blue", "position": 20}, {"name": "Crocalor", "colour": "neutral", "position": 21}, {"name": "Pumpkaboo", "colour": "neutral", "position": 22}, {"name": "Drilbur", "colour": "blue", "position": 23}, {"name": "Chandelure", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-05', 'gen1',
   '[{"word": "SHAPESHIFTER", "number": 2, "cat": 5, "t": [16, 18], "explain": "It''s from their Pok\u00e9dex lore \u2014 it can transform into any Pok\u00e9mon."}, {"word": "UNICORN", "number": 2, "cat": 3, "t": [8, 10], "explain": "They''re all based on the real-world unicorn."}, {"word": "KITSUNE", "number": 2, "cat": 5, "t": [2, 5], "explain": "It''s rooted in mythology \u2014 the kitsune fox-spirit."}, {"word": "MANEATER", "number": 1, "cat": 4, "t": [4], "explain": "They''re based on a Venus flytrap."}, {"word": "PUGILIST", "number": 2, "cat": 3, "t": [11, 14], "explain": "They''re based on a boxer."}]'::jsonb,
   '[{"word": "NO-HEAD-NECK", "number": 1, "cat": 2, "t": [14]}, {"word": "PINK-BLOB", "number": 1, "cat": 2, "t": [16]}, {"word": "SMALL", "number": 1, "cat": 2, "t": [18]}, {"word": "HUMANOID", "number": 1, "cat": 3, "t": [11]}, {"word": "CURLED-TAILS", "number": 1, "cat": 2, "t": [5]}, {"word": "FIRE-MANE", "number": 1, "cat": 2, "t": [10]}, {"word": "PITCHER-MOUTH", "number": 1, "cat": 2, "t": [4]}, {"word": "UNICORN", "number": 1, "cat": 3, "t": [8]}, {"word": "MANE", "number": 1, "cat": 2, "t": [2]}]'::jsonb,
   '[{"name": "Kingler", "colour": "neutral", "position": 0}, {"name": "Jynx", "colour": "neutral", "position": 1}, {"name": "Ninetales", "colour": "blue", "position": 2}, {"name": "Vaporeon", "colour": "neutral", "position": 3}, {"name": "Victreebel", "colour": "blue", "position": 4}, {"name": "Vulpix", "colour": "blue", "position": 5}, {"name": "Magnemite", "colour": "neutral", "position": 6}, {"name": "Mr. Mime", "colour": "neutral", "position": 7}, {"name": "Rapidash", "colour": "blue", "position": 8}, {"name": "Lapras", "colour": "neutral", "position": 9}, {"name": "Ponyta", "colour": "blue", "position": 10}, {"name": "Hitmonchan", "colour": "blue", "position": 11}, {"name": "Pikachu", "colour": "neutral", "position": 12}, {"name": "Golduck", "colour": "neutral", "position": 13}, {"name": "Hitmonlee", "colour": "blue", "position": 14}, {"name": "Pidgey", "colour": "neutral", "position": 15}, {"name": "Ditto", "colour": "blue", "position": 16}, {"name": "Horsea", "colour": "neutral", "position": 17}, {"name": "Mew", "colour": "blue", "position": 18}, {"name": "Fearow", "colour": "neutral", "position": 19}, {"name": "Charmeleon", "colour": "neutral", "position": 20}, {"name": "Gastly", "colour": "neutral", "position": 21}, {"name": "Kadabra", "colour": "neutral", "position": 22}, {"name": "Gengar", "colour": "neutral", "position": 23}, {"name": "Pidgeotto", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-05', 'mixed',
   '[{"word": "GHOST-FOREST", "number": 2, "cat": 5, "t": [6, 20], "explain": "It''s from their Pok\u00e9dex lore \u2014 a haunted tree."}, {"word": "WEASEL", "number": 2, "cat": 3, "t": [8, 16], "explain": "They''re all based on the real-world weasel."}, {"word": "SAMURAI", "number": 2, "cat": 4, "t": [0, 9], "explain": "They''re based on a samurai."}, {"word": "PELICAN", "number": 1, "cat": 3, "t": [21], "explain": "They''re all based on the real-world pelican."}, {"word": "SCARECROW", "number": 2, "cat": 4, "t": [18, 24], "explain": "They''re based on a scarecrow."}]'::jsonb,
   '[{"word": "TWIG", "number": 1, "cat": 2, "t": [6]}, {"word": "SPIKY-ARMS", "number": 1, "cat": 2, "t": [18]}, {"word": "FISTS", "number": 1, "cat": 2, "t": [9]}, {"word": "SCOUT-TAIL", "number": 1, "cat": 2, "t": [8]}, {"word": "BEAR", "number": 1, "cat": 3, "t": [0]}, {"word": "GULPS-PREY", "number": 1, "cat": 2, "t": [21]}, {"word": "SPIKES", "number": 1, "cat": 2, "t": [24]}, {"word": "ROOTS", "number": 1, "cat": 2, "t": [20]}, {"word": "STRIPES", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
   '[{"name": "Kubfu", "colour": "blue", "position": 0}, {"name": "Shellos", "colour": "neutral", "position": 1}, {"name": "Bramblin", "colour": "neutral", "position": 2}, {"name": "Swablu", "colour": "neutral", "position": 3}, {"name": "Coalossal", "colour": "neutral", "position": 4}, {"name": "Chimecho", "colour": "neutral", "position": 5}, {"name": "Phantump", "colour": "blue", "position": 6}, {"name": "Gligar", "colour": "neutral", "position": 7}, {"name": "Sentret", "colour": "blue", "position": 8}, {"name": "Urshifu", "colour": "blue", "position": 9}, {"name": "Togetic", "colour": "neutral", "position": 10}, {"name": "Quilava", "colour": "neutral", "position": 11}, {"name": "Purrloin", "colour": "neutral", "position": 12}, {"name": "Kricketune", "colour": "neutral", "position": 13}, {"name": "Chewtle", "colour": "neutral", "position": 14}, {"name": "Houndoom", "colour": "neutral", "position": 15}, {"name": "Furret", "colour": "blue", "position": 16}, {"name": "Poipole", "colour": "neutral", "position": 17}, {"name": "Cacturne", "colour": "blue", "position": 18}, {"name": "Fezandipiti", "colour": "neutral", "position": 19}, {"name": "Trevenant", "colour": "blue", "position": 20}, {"name": "Cramorant", "colour": "blue", "position": 21}, {"name": "Corphish", "colour": "neutral", "position": 22}, {"name": "Raging Bolt", "colour": "neutral", "position": 23}, {"name": "Cacnea", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-06', 'gen1',
   '[{"word": "FOSSILISED", "number": 2, "cat": 5, "t": [15, 18], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re prehistoric fossils brought back to life."}, {"word": "FERRY", "number": 1, "cat": 3, "t": [9], "explain": "It''s from their Pok\u00e9dex lore \u2014 it ferries travellers across the sea."}, {"word": "SPHERE", "number": 2, "cat": 2, "t": [1, 22], "explain": "You can spot it on the sprite \u2014 a Pok\u00e9 Ball shape."}, {"word": "SLUDGE", "number": 2, "cat": 3, "t": [10, 24], "explain": "They''re all based on the real-world sludge."}, {"word": "JELLYFISH", "number": 2, "cat": 4, "t": [7, 13], "explain": "They''re all based on the real-world jellyfish."}]'::jsonb,
   '[{"word": "SPIRAL-SHELL", "number": 1, "cat": 2, "t": [15]}, {"word": "POKE-BALL", "number": 1, "cat": 3, "t": [22]}, {"word": "BALL-SHAPE", "number": 1, "cat": 2, "t": [1]}, {"word": "LOCH-NESS-MONSTER", "number": 1, "cat": 3, "t": [9]}, {"word": "RED-JEWELS", "number": 1, "cat": 2, "t": [7]}, {"word": "JELLYFISH", "number": 1, "cat": 3, "t": [13]}, {"word": "SCYTHE-ARMS", "number": 1, "cat": 2, "t": [18]}, {"word": "OOZING-BODY", "number": 1, "cat": 2, "t": [24]}, {"word": "OOZE-BODY", "number": 1, "cat": 2, "t": [10]}]'::jsonb,
   '[{"name": "Parasect", "colour": "neutral", "position": 0}, {"name": "Voltorb", "colour": "blue", "position": 1}, {"name": "Gyarados", "colour": "neutral", "position": 2}, {"name": "Hypno", "colour": "neutral", "position": 3}, {"name": "Tangela", "colour": "neutral", "position": 4}, {"name": "Mankey", "colour": "neutral", "position": 5}, {"name": "Arcanine", "colour": "neutral", "position": 6}, {"name": "Tentacruel", "colour": "blue", "position": 7}, {"name": "Magneton", "colour": "neutral", "position": 8}, {"name": "Lapras", "colour": "blue", "position": 9}, {"name": "Grimer", "colour": "blue", "position": 10}, {"name": "Venusaur", "colour": "neutral", "position": 11}, {"name": "Chansey", "colour": "neutral", "position": 12}, {"name": "Tentacool", "colour": "blue", "position": 13}, {"name": "Golbat", "colour": "neutral", "position": 14}, {"name": "Omastar", "colour": "blue", "position": 15}, {"name": "Snorlax", "colour": "neutral", "position": 16}, {"name": "Jolteon", "colour": "neutral", "position": 17}, {"name": "Kabutops", "colour": "blue", "position": 18}, {"name": "Jigglypuff", "colour": "neutral", "position": 19}, {"name": "Nidorino", "colour": "neutral", "position": 20}, {"name": "Vaporeon", "colour": "neutral", "position": 21}, {"name": "Electrode", "colour": "blue", "position": 22}, {"name": "Machamp", "colour": "neutral", "position": 23}, {"name": "Muk", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-06', 'mixed',
   '[{"word": "HIVE", "number": 2, "cat": 3, "t": [18, 20], "explain": "They''re all based on the real-world bee."}, {"word": "GEM", "number": 1, "cat": 2, "t": [14], "explain": "You can spot it on the sprite \u2014 a gemstone body."}, {"word": "FROG", "number": 2, "cat": 3, "t": [9, 13], "explain": "They''re all based on the real-world frog."}, {"word": "SQUID", "number": 2, "cat": 4, "t": [10, 16], "explain": "They''re all based on the real-world squid."}, {"word": "MOLTEN", "number": 2, "cat": 3, "t": [3, 23], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re made of molten lava."}]'::jsonb,
   '[{"word": "CEPHALOPOD", "number": 1, "cat": 3, "t": [16]}, {"word": "JEWEL-BODY", "number": 1, "cat": 2, "t": [14]}, {"word": "THREE-FACES", "number": 1, "cat": 2, "t": [20]}, {"word": "MOLTEN-BODY", "number": 1, "cat": 2, "t": [23]}, {"word": "MOLTEN", "number": 1, "cat": 2, "t": [3]}, {"word": "YELLOW-BODY", "number": 1, "cat": 2, "t": [18]}, {"word": "GLOW-SPOTS", "number": 1, "cat": 2, "t": [10]}, {"word": "FROG", "number": 1, "cat": 3, "t": [13]}, {"word": "BUMPS", "number": 1, "cat": 2, "t": [9]}]'::jsonb,
   '[{"name": "Woobat", "colour": "neutral", "position": 0}, {"name": "Pansear", "colour": "neutral", "position": 1}, {"name": "Grimmsnarl", "colour": "neutral", "position": 2}, {"name": "Magcargo", "colour": "blue", "position": 3}, {"name": "Buneary", "colour": "neutral", "position": 4}, {"name": "Ekans", "colour": "neutral", "position": 5}, {"name": "Solrock", "colour": "neutral", "position": 6}, {"name": "Lillipup", "colour": "neutral", "position": 7}, {"name": "Tyrantrum", "colour": "neutral", "position": 8}, {"name": "Palpitoad", "colour": "blue", "position": 9}, {"name": "Inkay", "colour": "blue", "position": 10}, {"name": "Probopass", "colour": "neutral", "position": 11}, {"name": "Dratini", "colour": "neutral", "position": 12}, {"name": "Tympole", "colour": "blue", "position": 13}, {"name": "Carbink", "colour": "blue", "position": 14}, {"name": "Volcanion", "colour": "neutral", "position": 15}, {"name": "Malamar", "colour": "blue", "position": 16}, {"name": "Minior", "colour": "neutral", "position": 17}, {"name": "Vespiquen", "colour": "blue", "position": 18}, {"name": "Togetic", "colour": "neutral", "position": 19}, {"name": "Combee", "colour": "blue", "position": 20}, {"name": "Zygarde", "colour": "neutral", "position": 21}, {"name": "Heracross", "colour": "neutral", "position": 22}, {"name": "Slugma", "colour": "blue", "position": 23}, {"name": "Clamperl", "colour": "neutral", "position": 24}]'::jsonb)
on conflict (puzzle_date, pool) do update
  set clues = excluded.clues, hints = excluded.hints, tiles = excluded.tiles;
