-- 31_updates.sql
--
-- Two daily-puzzle upgrades (batched with the Aug 31 - Sep 6 puzzle data below):
--
--   (1) Per-clue explanations. Each base clue now carries an "explain" sentence
--       (why the clue points at those Pokemon + which category it is). The end
--       screen shows it under each clue. get_daily_puzzle strips it mid-game so
--       it can't leak the answers early.
--
--   (2) Offline play. New RPC get_daily_full returns the whole puzzle "sealed":
--       the colour key + hints (with targets) + clues (with targets and
--       explanations), XOR-obfuscated + base64 so it isn't plain text in the
--       network response. The client unseals it once at load and then does every
--       reveal / hint / finish LOCALLY, so a player who loses connection after
--       the page has loaded can still finish the puzzle.
--
-- Safe to re-run (create-or-replace + upsert).

-- ----------------------------------------------------------------------------
-- _daily_seal: XOR-obfuscate a jsonb payload with a fixed repeating key, then
-- base64-encode it. The matching key + un-seal live in app.js. This is light
-- obfuscation (not encryption) - enough that the answers aren't readable at a
-- glance, while letting the whole puzzle be played offline once loaded.
-- ----------------------------------------------------------------------------
create or replace function public._daily_seal(p jsonb)
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  b bytea;
  i int;
  n int;
  k int[] := array[142,55,91,44,116,17,163];
begin
  b := convert_to(p::text, 'UTF8');
  n := octet_length(b);
  for i in 0..n-1 loop
    b := set_byte(b, i, get_byte(b, i) # k[(i % 7) + 1]);
  end loop;
  return encode(b, 'base64');
end;
$$;

-- ----------------------------------------------------------------------------
-- get_daily_puzzle: serve today's board + base clues WITHOUT target positions
-- OR the explanation text (both must stay hidden until the game ends).
-- ----------------------------------------------------------------------------
create or replace function public.get_daily_puzzle(p_pool text)
returns table(puzzle_date date, clues jsonb, tiles jsonb)
language sql
security definer
set search_path = public
as $$
  select dp.puzzle_date,
    (
      select jsonb_agg((c - 't' - 'explain') order by ord)
      from jsonb_array_elements(dp.clues) with ordinality as x(c, ord)
    ) as clues,
    (
      select jsonb_agg(
        jsonb_build_object(
          'position',   (t->>'position')::int,
          'name',       t->>'name',
          'pokemon_id', pk.id,
          'sprite_url', pk.sprite_url
        ) order by (t->>'position')::int
      )
      from jsonb_array_elements(dp.tiles) t
      left join pokemon pk on lower(pk.name) = lower(t->>'name')
    ) as tiles
  from daily_puzzles dp
  where dp.pool = p_pool and dp.puzzle_date <= current_date
  order by dp.puzzle_date desc
  limit 1;
$$;

-- ----------------------------------------------------------------------------
-- get_daily_full: today's board (tiles WITHOUT colours, for rendering) plus a
-- sealed blob carrying everything needed to play + finish OFFLINE:
--   c = { position -> colour },  h = hints (with t),  k = clues (with t+explain)
-- ----------------------------------------------------------------------------
create or replace function public.get_daily_full(p_pool text)
returns table(puzzle_date date, tiles jsonb, sealed text)
language sql
security definer
set search_path = public
as $$
  select dp.puzzle_date,
    (
      select jsonb_agg(
        jsonb_build_object(
          'position',   (t->>'position')::int,
          'name',       t->>'name',
          'pokemon_id', pk.id,
          'sprite_url', pk.sprite_url
        ) order by (t->>'position')::int
      )
      from jsonb_array_elements(dp.tiles) t
      left join pokemon pk on lower(pk.name) = lower(t->>'name')
    ) as tiles,
    public._daily_seal(jsonb_build_object(
      'c', (
        select jsonb_object_agg(t->>'position', t->>'colour')
        from jsonb_array_elements(dp.tiles) t
      ),
      'h', coalesce(dp.hints, '[]'::jsonb),
      'k', dp.clues
    )) as sealed
  from daily_puzzles dp
  where dp.pool = p_pool and dp.puzzle_date <= current_date
  order by dp.puzzle_date desc
  limit 1;
$$;

grant execute on function public.get_daily_puzzle(text) to authenticated;
grant execute on function public.get_daily_full(text)   to authenticated;


-- ------------------------------------------------------------------
-- Puzzle data: 2026-08-31 .. 2026-09-06 (fact-bank authored, with per-clue explanations).

insert into public.daily_puzzles (puzzle_date, pool, clues, hints, tiles) values
  ('2026-08-31', 'gen1',
   '[{"word": "GRASS", "number": 2, "cat": 1, "t": [13, 18], "explain": "Every one is a Grass-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "POLLINATOR", "number": 1, "cat": 3, "t": [1], "explain": "They''re all based on the real-world butterfly. (Category 3: a real-world basis.)"}, {"word": "PSYCHIC", "number": 2, "cat": 1, "t": [8, 10], "explain": "Every one is a Psychic-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "BOULDER", "number": 2, "cat": 3, "t": [11, 22], "explain": "They''re all based on the real-world rock golem. (Category 3: a real-world basis.)"}, {"word": "PUNCH", "number": 2, "cat": 2, "t": [3, 14], "explain": "You can spot it on the sprite \u2014 the raised fists. (Category 2: look at the sprite.)"}]'::jsonb,
   '[{"word": "FLOWER-HEAD", "number": 1, "cat": 2, "t": [13]}, {"word": "TRUNK", "number": 1, "cat": 2, "t": [10]}, {"word": "TAIL", "number": 1, "cat": 2, "t": [3]}, {"word": "BIG-EYES", "number": 1, "cat": 2, "t": [1]}, {"word": "HUMANOID", "number": 1, "cat": 3, "t": [14]}, {"word": "LEAF-HEAD", "number": 1, "cat": 2, "t": [18]}, {"word": "ROCKY-BODY", "number": 1, "cat": 2, "t": [11]}, {"word": "STUBBY-LIMBS", "number": 1, "cat": 2, "t": [22]}, {"word": "SLEEPS-18H", "number": 1, "cat": 2, "t": [8]}]'::jsonb,
   '[{"name": "Primeape", "colour": "neutral", "position": 0}, {"name": "Butterfree", "colour": "blue", "position": 1}, {"name": "Magikarp", "colour": "neutral", "position": 2}, {"name": "Machop", "colour": "blue", "position": 3}, {"name": "Dugtrio", "colour": "neutral", "position": 4}, {"name": "Raticate", "colour": "neutral", "position": 5}, {"name": "Caterpie", "colour": "neutral", "position": 6}, {"name": "Dratini", "colour": "neutral", "position": 7}, {"name": "Abra", "colour": "blue", "position": 8}, {"name": "Snorlax", "colour": "neutral", "position": 9}, {"name": "Drowzee", "colour": "blue", "position": 10}, {"name": "Geodude", "colour": "blue", "position": 11}, {"name": "Blastoise", "colour": "neutral", "position": 12}, {"name": "Gloom", "colour": "blue", "position": 13}, {"name": "Machoke", "colour": "blue", "position": 14}, {"name": "Chansey", "colour": "neutral", "position": 15}, {"name": "Clefable", "colour": "neutral", "position": 16}, {"name": "Koffing", "colour": "neutral", "position": 17}, {"name": "Oddish", "colour": "blue", "position": 18}, {"name": "Kabuto", "colour": "neutral", "position": 19}, {"name": "Flareon", "colour": "neutral", "position": 20}, {"name": "Persian", "colour": "neutral", "position": 21}, {"name": "Golem", "colour": "blue", "position": 22}, {"name": "Gyarados", "colour": "neutral", "position": 23}, {"name": "Raichu", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-31', 'mixed',
   '[{"word": "GRUB", "number": 2, "cat": 3, "t": [10, 22], "explain": "They''re all based on the real-world caterpillar. (Category 3: a real-world basis.)"}, {"word": "FOX", "number": 2, "cat": 3, "t": [4, 24], "explain": "They''re all based on the real-world fox. (Category 3: a real-world basis.)"}, {"word": "DRAGON", "number": 2, "cat": 1, "t": [3, 12], "explain": "Every one is a Dragon-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "TOADSTOOL", "number": 1, "cat": 2, "t": [18], "explain": "You can spot it on the sprite \u2014 the mushroom on its back. (Category 2: look at the sprite.)"}, {"word": "WATER", "number": 2, "cat": 1, "t": [14, 15], "explain": "Every one is a Water-type. (Category 1: the easy one \u2014 type or family.)"}]'::jsonb,
   '[{"word": "BEAK", "number": 1, "cat": 2, "t": [15]}, {"word": "JAWS", "number": 1, "cat": 2, "t": [12]}, {"word": "INSECT", "number": 1, "cat": 3, "t": [10]}, {"word": "EAR-TUFTS", "number": 1, "cat": 2, "t": [4]}, {"word": "LEAF-CLOAK", "number": 1, "cat": 2, "t": [22]}, {"word": "CAP", "number": 1, "cat": 2, "t": [18]}, {"word": "TWIG-WAND", "number": 1, "cat": 2, "t": [24]}, {"word": "HEAD-SCALE", "number": 1, "cat": 2, "t": [3]}, {"word": "GREEN-BODY", "number": 1, "cat": 2, "t": [14]}]'::jsonb,
   '[{"name": "Ferroseed", "colour": "neutral", "position": 0}, {"name": "Munkidori", "colour": "neutral", "position": 1}, {"name": "Sudowoodo", "colour": "neutral", "position": 2}, {"name": "Jangmo-o", "colour": "blue", "position": 3}, {"name": "Fennekin", "colour": "blue", "position": 4}, {"name": "Rowlet", "colour": "neutral", "position": 5}, {"name": "Masquerain", "colour": "neutral", "position": 6}, {"name": "Tropius", "colour": "neutral", "position": 7}, {"name": "Xerneas", "colour": "neutral", "position": 8}, {"name": "Tinkaton", "colour": "neutral", "position": 9}, {"name": "Sewaddle", "colour": "blue", "position": 10}, {"name": "Urshifu", "colour": "neutral", "position": 11}, {"name": "Gible", "colour": "blue", "position": 12}, {"name": "Gothita", "colour": "neutral", "position": 13}, {"name": "Chewtle", "colour": "blue", "position": 14}, {"name": "Wingull", "colour": "blue", "position": 15}, {"name": "Dugtrio", "colour": "neutral", "position": 16}, {"name": "Swellow", "colour": "neutral", "position": 17}, {"name": "Shroomish", "colour": "blue", "position": 18}, {"name": "Roggenrola", "colour": "neutral", "position": 19}, {"name": "Comfey", "colour": "neutral", "position": 20}, {"name": "Skarmory", "colour": "neutral", "position": 21}, {"name": "Swadloon", "colour": "blue", "position": 22}, {"name": "Sunkern", "colour": "neutral", "position": 23}, {"name": "Braixen", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-01', 'gen1',
   '[{"word": "DRACULA", "number": 2, "cat": 4, "t": [1, 13], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re vampire bats. (Category 4: a trickier grouping.)"}, {"word": "ELECTRIC", "number": 2, "cat": 1, "t": [2, 4], "explain": "Every one is a Electric-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "ROCK", "number": 2, "cat": 1, "t": [0, 15], "explain": "Every one is a Rock-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "SEEDS", "number": 1, "cat": 2, "t": [5], "explain": "You can spot it on the sprite \u2014 the seeds on its body. (Category 2: look at the sprite.)"}, {"word": "GROUND", "number": 2, "cat": 1, "t": [8, 12], "explain": "Every one is a Ground-type. (Category 1: the easy one \u2014 type or family.)"}]'::jsonb,
   '[{"word": "CRACKS", "number": 1, "cat": 2, "t": [5]}, {"word": "UFO", "number": 1, "cat": 3, "t": [4]}, {"word": "NO-EYES", "number": 1, "cat": 2, "t": [1]}, {"word": "SPIRAL-SHELL", "number": 1, "cat": 2, "t": [15]}, {"word": "MINERAL", "number": 1, "cat": 3, "t": [2]}, {"word": "BACK-SPIKES", "number": 1, "cat": 2, "t": [12]}, {"word": "CURL", "number": 1, "cat": 2, "t": [8]}, {"word": "HUGE-MOUTH", "number": 1, "cat": 2, "t": [13]}, {"word": "DOME-SHELL", "number": 1, "cat": 2, "t": [0]}]'::jsonb,
   '[{"name": "Kabuto", "colour": "blue", "position": 0}, {"name": "Zubat", "colour": "blue", "position": 1}, {"name": "Magnemite", "colour": "blue", "position": 2}, {"name": "Spearow", "colour": "neutral", "position": 3}, {"name": "Magneton", "colour": "blue", "position": 4}, {"name": "Exeggcute", "colour": "blue", "position": 5}, {"name": "Alakazam", "colour": "neutral", "position": 6}, {"name": "Slowpoke", "colour": "neutral", "position": 7}, {"name": "Sandshrew", "colour": "blue", "position": 8}, {"name": "Tentacool", "colour": "neutral", "position": 9}, {"name": "Moltres", "colour": "neutral", "position": 10}, {"name": "Gastly", "colour": "neutral", "position": 11}, {"name": "Sandslash", "colour": "blue", "position": 12}, {"name": "Golbat", "colour": "blue", "position": 13}, {"name": "Tauros", "colour": "neutral", "position": 14}, {"name": "Omanyte", "colour": "blue", "position": 15}, {"name": "Dewgong", "colour": "neutral", "position": 16}, {"name": "Lapras", "colour": "neutral", "position": 17}, {"name": "Mewtwo", "colour": "neutral", "position": 18}, {"name": "Mew", "colour": "neutral", "position": 19}, {"name": "Machoke", "colour": "neutral", "position": 20}, {"name": "Poliwrath", "colour": "neutral", "position": 21}, {"name": "Venonat", "colour": "neutral", "position": 22}, {"name": "Psyduck", "colour": "neutral", "position": 23}, {"name": "Seaking", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-01', 'mixed',
   '[{"word": "GROUND", "number": 2, "cat": 1, "t": [7, 13], "explain": "Every one is a Ground-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "RAVEN", "number": 2, "cat": 3, "t": [10, 14], "explain": "They''re all based on the real-world crow. (Category 3: a real-world basis.)"}, {"word": "FAIRY", "number": 2, "cat": 1, "t": [11, 12], "explain": "Every one is a Fairy-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "ELECTRIC", "number": 2, "cat": 1, "t": [2, 6], "explain": "Every one is a Electric-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "SNAIL", "number": 1, "cat": 3, "t": [3], "explain": "They''re all based on the real-world snail. (Category 3: a real-world basis.)"}]'::jsonb,
   '[{"word": "CORGI", "number": 1, "cat": 3, "t": [6]}, {"word": "CHEEKS", "number": 1, "cat": 2, "t": [2]}, {"word": "SPIKES", "number": 1, "cat": 2, "t": [12]}, {"word": "FAIRY", "number": 1, "cat": 3, "t": [11]}, {"word": "FRILLS", "number": 1, "cat": 2, "t": [3]}, {"word": "BIG-EARS", "number": 1, "cat": 2, "t": [7]}, {"word": "WITCH-HAT-CREST", "number": 1, "cat": 2, "t": [14]}, {"word": "BIRD", "number": 1, "cat": 3, "t": [10]}, {"word": "SAND-BODY", "number": 1, "cat": 2, "t": [13]}]'::jsonb,
   '[{"name": "Happiny", "colour": "neutral", "position": 0}, {"name": "Dragalge", "colour": "neutral", "position": 1}, {"name": "Pichu", "colour": "blue", "position": 2}, {"name": "Shellos", "colour": "blue", "position": 3}, {"name": "Virizion", "colour": "neutral", "position": 4}, {"name": "Arctibax", "colour": "neutral", "position": 5}, {"name": "Yamper", "colour": "blue", "position": 6}, {"name": "Phanpy", "colour": "blue", "position": 7}, {"name": "Magikarp", "colour": "neutral", "position": 8}, {"name": "Arcanine", "colour": "neutral", "position": 9}, {"name": "Honchkrow", "colour": "blue", "position": 10}, {"name": "Togetic", "colour": "blue", "position": 11}, {"name": "Togepi", "colour": "blue", "position": 12}, {"name": "Hippopotas", "colour": "blue", "position": 13}, {"name": "Murkrow", "colour": "blue", "position": 14}, {"name": "Lotad", "colour": "neutral", "position": 15}, {"name": "Volcarona", "colour": "neutral", "position": 16}, {"name": "Skrelp", "colour": "neutral", "position": 17}, {"name": "Nidorina", "colour": "neutral", "position": 18}, {"name": "Pidgeotto", "colour": "neutral", "position": 19}, {"name": "Pecharunt", "colour": "neutral", "position": 20}, {"name": "Wingull", "colour": "neutral", "position": 21}, {"name": "Seaking", "colour": "neutral", "position": 22}, {"name": "Manaphy", "colour": "neutral", "position": 23}, {"name": "Gossifleur", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-02', 'gen1',
   '[{"word": "SKULL-MASK", "number": 2, "cat": 3, "t": [15, 22], "explain": "They''re based on the bone club and skull helmet it wears. (Category 3: a real-world basis.)"}, {"word": "SOPRANO", "number": 1, "cat": 4, "t": [5], "explain": "It''s from their Pok\u00e9dex lore \u2014 an opera diva / snow-hag. (Category 4: a trickier grouping.)"}, {"word": "BUG", "number": 2, "cat": 1, "t": [4, 7], "explain": "Every one is a Bug-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "TELEPORT", "number": 2, "cat": 3, "t": [12, 19], "explain": "It''s from their Pok\u00e9dex lore \u2014 its signature Teleport move. (Category 3: a real-world basis.)"}, {"word": "POISON", "number": 2, "cat": 1, "t": [2, 9], "explain": "Every one is a Poison-type. (Category 1: the easy one \u2014 type or family.)"}]'::jsonb,
   '[{"word": "SPINES", "number": 1, "cat": 2, "t": [2]}, {"word": "GOWN", "number": 1, "cat": 2, "t": [5]}, {"word": "MUSHROOMS", "number": 1, "cat": 2, "t": [4]}, {"word": "MAMMAL", "number": 1, "cat": 3, "t": [15]}, {"word": "SKULL-HELMET", "number": 1, "cat": 2, "t": [22]}, {"word": "EARS", "number": 1, "cat": 2, "t": [9]}, {"word": "TWIN-SPOONS", "number": 1, "cat": 2, "t": [12]}, {"word": "SPOON", "number": 1, "cat": 2, "t": [19]}, {"word": "ANTENNA", "number": 1, "cat": 2, "t": [7]}]'::jsonb,
   '[{"name": "Zapdos", "colour": "neutral", "position": 0}, {"name": "Kingler", "colour": "neutral", "position": 1}, {"name": "Nidorino", "colour": "blue", "position": 2}, {"name": "Magneton", "colour": "neutral", "position": 3}, {"name": "Paras", "colour": "blue", "position": 4}, {"name": "Jynx", "colour": "blue", "position": 5}, {"name": "Dugtrio", "colour": "neutral", "position": 6}, {"name": "Caterpie", "colour": "blue", "position": 7}, {"name": "Diglett", "colour": "neutral", "position": 8}, {"name": "Nidorina", "colour": "blue", "position": 9}, {"name": "Rattata", "colour": "neutral", "position": 10}, {"name": "Cloyster", "colour": "neutral", "position": 11}, {"name": "Alakazam", "colour": "blue", "position": 12}, {"name": "Charizard", "colour": "neutral", "position": 13}, {"name": "Omanyte", "colour": "neutral", "position": 14}, {"name": "Marowak", "colour": "blue", "position": 15}, {"name": "Starmie", "colour": "neutral", "position": 16}, {"name": "Articuno", "colour": "neutral", "position": 17}, {"name": "Primeape", "colour": "neutral", "position": 18}, {"name": "Kadabra", "colour": "blue", "position": 19}, {"name": "Horsea", "colour": "neutral", "position": 20}, {"name": "Meowth", "colour": "neutral", "position": 21}, {"name": "Cubone", "colour": "blue", "position": 22}, {"name": "Magikarp", "colour": "neutral", "position": 23}, {"name": "Raichu", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-02', 'mixed',
   '[{"word": "ACORN", "number": 1, "cat": 2, "t": [1], "explain": "You can spot it on the sprite \u2014 the acorn cap. (Category 2: look at the sprite.)"}, {"word": "ICE", "number": 2, "cat": 1, "t": [6, 8], "explain": "Every one is a Ice-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "FIGHTING", "number": 2, "cat": 1, "t": [5, 16], "explain": "Every one is a Fighting-type. (Category 1: the easy one \u2014 type or family.)"}, {"word": "GATOR", "number": 2, "cat": 3, "t": [13, 23], "explain": "They''re all based on the real-world crocodile. (Category 3: a real-world basis.)"}, {"word": "TAPIR", "number": 2, "cat": 3, "t": [0, 19], "explain": "They''re all based on the real-world tapir (a dream-eating baku). (Category 3: a real-world basis.)"}]'::jsonb,
   '[{"word": "FLOWER-PATTERN", "number": 1, "cat": 2, "t": [0]}, {"word": "LOTUS-POSE", "number": 1, "cat": 2, "t": [16]}, {"word": "BIG-FISTS", "number": 1, "cat": 2, "t": [5]}, {"word": "ACORN-BODY", "number": 1, "cat": 2, "t": [1]}, {"word": "DREAM-MIST", "number": 1, "cat": 2, "t": [19]}, {"word": "HOOD-BODY", "number": 1, "cat": 2, "t": [6]}, {"word": "ICE-BLOCK", "number": 1, "cat": 2, "t": [8]}, {"word": "SPIKES", "number": 1, "cat": 2, "t": [13]}, {"word": "JAWS", "number": 1, "cat": 2, "t": [23]}]'::jsonb,
   '[{"name": "Munna", "colour": "blue", "position": 0}, {"name": "Seedot", "colour": "blue", "position": 1}, {"name": "Dusknoir", "colour": "neutral", "position": 2}, {"name": "Spearow", "colour": "neutral", "position": 3}, {"name": "Dewott", "colour": "neutral", "position": 4}, {"name": "Makuhita", "colour": "blue", "position": 5}, {"name": "Snorunt", "colour": "blue", "position": 6}, {"name": "Combee", "colour": "neutral", "position": 7}, {"name": "Bergmite", "colour": "blue", "position": 8}, {"name": "Foongus", "colour": "neutral", "position": 9}, {"name": "Xurkitree", "colour": "neutral", "position": 10}, {"name": "Yveltal", "colour": "neutral", "position": 11}, {"name": "Amoonguss", "colour": "neutral", "position": 12}, {"name": "Croconaw", "colour": "blue", "position": 13}, {"name": "Furfrou", "colour": "neutral", "position": 14}, {"name": "Snivy", "colour": "neutral", "position": 15}, {"name": "Meditite", "colour": "blue", "position": 16}, {"name": "Ribombee", "colour": "neutral", "position": 17}, {"name": "Whirlipede", "colour": "neutral", "position": 18}, {"name": "Musharna", "colour": "blue", "position": 19}, {"name": "Espurr", "colour": "neutral", "position": 20}, {"name": "Igglybuff", "colour": "neutral", "position": 21}, {"name": "Palpitoad", "colour": "neutral", "position": 22}, {"name": "Totodile", "colour": "blue", "position": 23}, {"name": "Alakazam", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-03', 'gen1',
   '[{"word": "PINCERS", "number": 2, "cat": 2, "t": [3, 15], "explain": "You can spot it on the sprite \u2014 the big pincers. (Category 2: look at the sprite.)"}, {"word": "DUX", "number": 2, "cat": 3, "t": [0, 14], "explain": "They''re all based on the real-world duck. (Category 3: a real-world basis.)"}, {"word": "FIRST-CHOICE", "number": 3, "cat": 1, "t": [2, 9, 17], "explain": "They''re first-partner (starter) Pok\u00e9mon. (Category 1: the easy one \u2014 type or family.)"}, {"word": "GENIE", "number": 1, "cat": 5, "t": [13], "explain": "It''s from their Pok\u00e9dex lore \u2014 a mythical dragon. (Category 5: a deeper connection.)"}, {"word": "SERPENT", "number": 1, "cat": 3, "t": [1], "explain": "They''re all based on the real-world eel and sea-serpent. (Category 3: a real-world basis.)"}]'::jsonb,
   '[{"word": "SHELL", "number": 1, "cat": 2, "t": [9]}, {"word": "PINCERS", "number": 1, "cat": 2, "t": [15]}, {"word": "BLANK-STARE", "number": 1, "cat": 2, "t": [14]}, {"word": "SERPENT", "number": 1, "cat": 3, "t": [13]}, {"word": "SERPENT-BODY", "number": 1, "cat": 2, "t": [1]}, {"word": "HUGE-CLAW", "number": 1, "cat": 2, "t": [3]}, {"word": "WEBBED", "number": 1, "cat": 2, "t": [0]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [2]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [17]}]'::jsonb,
   '[{"name": "Golduck", "colour": "blue", "position": 0}, {"name": "Gyarados", "colour": "blue", "position": 1}, {"name": "Bulbasaur", "colour": "blue", "position": 2}, {"name": "Kingler", "colour": "blue", "position": 3}, {"name": "Growlithe", "colour": "neutral", "position": 4}, {"name": "Gloom", "colour": "neutral", "position": 5}, {"name": "Zapdos", "colour": "neutral", "position": 6}, {"name": "Grimer", "colour": "neutral", "position": 7}, {"name": "Venonat", "colour": "neutral", "position": 8}, {"name": "Squirtle", "colour": "blue", "position": 9}, {"name": "Mewtwo", "colour": "neutral", "position": 10}, {"name": "Pidgeotto", "colour": "neutral", "position": 11}, {"name": "Venomoth", "colour": "neutral", "position": 12}, {"name": "Dratini", "colour": "blue", "position": 13}, {"name": "Psyduck", "colour": "blue", "position": 14}, {"name": "Krabby", "colour": "blue", "position": 15}, {"name": "Golem", "colour": "neutral", "position": 16}, {"name": "Charmander", "colour": "blue", "position": 17}, {"name": "Vaporeon", "colour": "neutral", "position": 18}, {"name": "Scyther", "colour": "neutral", "position": 19}, {"name": "Ninetales", "colour": "neutral", "position": 20}, {"name": "Drowzee", "colour": "neutral", "position": 21}, {"name": "Rhyhorn", "colour": "neutral", "position": 22}, {"name": "Nidoqueen", "colour": "neutral", "position": 23}, {"name": "Aerodactyl", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-03', 'mixed',
   '[{"word": "SICKLE", "number": 2, "cat": 2, "t": [9, 19], "explain": "You can spot it on the sprite \u2014 the scythe-shaped arms. (Category 2: look at the sprite.)"}, {"word": "LAZYBONES", "number": 1, "cat": 3, "t": [24], "explain": "They''re all based on the real-world sloth. (Category 3: a real-world basis.)"}, {"word": "SIMIAN", "number": 2, "cat": 3, "t": [4, 18], "explain": "They''re all based on the real-world monkey. (Category 3: a real-world basis.)"}, {"word": "LEGENDARY", "number": 3, "cat": 1, "t": [2, 15, 17], "explain": "They''re all Legendary Pok\u00e9mon. (Category 1: the easy one \u2014 type or family.)"}, {"word": "EIGHT-ARMS", "number": 1, "cat": 4, "t": [1], "explain": "They''re all based on the real-world octopus. (Category 4: a trickier grouping.)"}]'::jsonb,
   '[{"word": "LEAF-SCYTHES", "number": 1, "cat": 2, "t": [19]}, {"word": "PETAL-BLADES", "number": 1, "cat": 2, "t": [9]}, {"word": "LEAF-CROWN", "number": 1, "cat": 2, "t": [4]}, {"word": "CEPHALOPOD", "number": 1, "cat": 3, "t": [1]}, {"word": "GOLEM", "number": 1, "cat": 3, "t": [15]}, {"word": "DOT-FACE", "number": 1, "cat": 2, "t": [2]}, {"word": "METAL-BODY", "number": 1, "cat": 2, "t": [17]}, {"word": "WATER-CROWN", "number": 1, "cat": 2, "t": [18]}, {"word": "LAZY-FACE", "number": 1, "cat": 2, "t": [24]}]'::jsonb,
   '[{"name": "Boldore", "colour": "neutral", "position": 0}, {"name": "Grapploct", "colour": "blue", "position": 1}, {"name": "Regirock", "colour": "blue", "position": 2}, {"name": "Jigglypuff", "colour": "neutral", "position": 3}, {"name": "Pansage", "colour": "blue", "position": 4}, {"name": "Eevee", "colour": "neutral", "position": 5}, {"name": "Venonat", "colour": "neutral", "position": 6}, {"name": "Diglett", "colour": "neutral", "position": 7}, {"name": "Gastrodon", "colour": "neutral", "position": 8}, {"name": "Lurantis", "colour": "blue", "position": 9}, {"name": "Overqwil", "colour": "neutral", "position": 10}, {"name": "Sableye", "colour": "neutral", "position": 11}, {"name": "Charizard", "colour": "neutral", "position": 12}, {"name": "Tinkatuff", "colour": "neutral", "position": 13}, {"name": "Silicobra", "colour": "neutral", "position": 14}, {"name": "Regice", "colour": "blue", "position": 15}, {"name": "Mienshao", "colour": "neutral", "position": 16}, {"name": "Registeel", "colour": "blue", "position": 17}, {"name": "Panpour", "colour": "blue", "position": 18}, {"name": "Fomantis", "colour": "blue", "position": 19}, {"name": "Fletchinder", "colour": "neutral", "position": 20}, {"name": "Litten", "colour": "neutral", "position": 21}, {"name": "Garganacl", "colour": "neutral", "position": 22}, {"name": "Porygon-Z", "colour": "neutral", "position": 23}, {"name": "Slakoth", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-04', 'gen1',
   '[{"word": "COIN", "number": 1, "cat": 2, "t": [23], "explain": "You can spot it on the sprite \u2014 the gold coin on its forehead. (Category 2: look at the sprite.)"}, {"word": "COBRA", "number": 2, "cat": 3, "t": [7, 12], "explain": "They''re all based on the real-world cobra. (Category 3: a real-world basis.)"}, {"word": "FELINE", "number": 1, "cat": 3, "t": [17], "explain": "They''re all based on the real-world cat. (Category 3: a real-world basis.)"}, {"word": "BRANCH-EVO", "number": 3, "cat": 1, "t": [6, 16, 19], "explain": "They''re all part of the Eevee family. (Category 1: the easy one \u2014 type or family.)"}, {"word": "RHINO", "number": 2, "cat": 3, "t": [1, 2], "explain": "They''re all based on the real-world rhinoceros. (Category 3: a real-world basis.)"}]'::jsonb,
   '[{"word": "FLUFFY-COLLAR", "number": 1, "cat": 2, "t": [6]}, {"word": "FRILLED-COLLAR", "number": 1, "cat": 2, "t": [19]}, {"word": "ARMOUR-HIDE", "number": 1, "cat": 2, "t": [2]}, {"word": "FANGS", "number": 1, "cat": 2, "t": [7]}, {"word": "COIN-CHARM", "number": 1, "cat": 2, "t": [23]}, {"word": "FELINE", "number": 1, "cat": 3, "t": [17]}, {"word": "TAIL", "number": 1, "cat": 2, "t": [1]}, {"word": "SERPENT", "number": 1, "cat": 3, "t": [12]}, {"word": "SPIKY-FUR", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
   '[{"name": "Victreebel", "colour": "neutral", "position": 0}, {"name": "Rhydon", "colour": "blue", "position": 1}, {"name": "Rhyhorn", "colour": "blue", "position": 2}, {"name": "Rattata", "colour": "neutral", "position": 3}, {"name": "Weedle", "colour": "neutral", "position": 4}, {"name": "Weezing", "colour": "neutral", "position": 5}, {"name": "Eevee", "colour": "blue", "position": 6}, {"name": "Ekans", "colour": "blue", "position": 7}, {"name": "Pidgeotto", "colour": "neutral", "position": 8}, {"name": "Slowbro", "colour": "neutral", "position": 9}, {"name": "Poliwhirl", "colour": "neutral", "position": 10}, {"name": "Koffing", "colour": "neutral", "position": 11}, {"name": "Arbok", "colour": "blue", "position": 12}, {"name": "Articuno", "colour": "neutral", "position": 13}, {"name": "Hitmonlee", "colour": "neutral", "position": 14}, {"name": "Kakuna", "colour": "neutral", "position": 15}, {"name": "Jolteon", "colour": "blue", "position": 16}, {"name": "Persian", "colour": "blue", "position": 17}, {"name": "Squirtle", "colour": "neutral", "position": 18}, {"name": "Vaporeon", "colour": "blue", "position": 19}, {"name": "Haunter", "colour": "neutral", "position": 20}, {"name": "Butterfree", "colour": "neutral", "position": 21}, {"name": "Pinsir", "colour": "neutral", "position": 22}, {"name": "Meowth", "colour": "blue", "position": 23}, {"name": "Lapras", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-04', 'mixed',
   '[{"word": "PSEUDO-LEGENDARY", "number": 3, "cat": 1, "t": [5, 10, 20], "explain": "They''re pseudo-legendary Pok\u00e9mon. (Category 1: the easy one \u2014 type or family.)"}, {"word": "LANTERN", "number": 1, "cat": 4, "t": [18], "explain": "They''re based on a haunted lantern. (Category 4: a trickier grouping.)"}, {"word": "MOLE", "number": 1, "cat": 3, "t": [19], "explain": "They''re all based on the real-world mole. (Category 3: a real-world basis.)"}, {"word": "FIREFLY", "number": 2, "cat": 3, "t": [0, 9], "explain": "They''re all based on the real-world firefly. (Category 3: a real-world basis.)"}, {"word": "OTTER", "number": 2, "cat": 3, "t": [2, 6], "explain": "They''re all based on the real-world sea otter. (Category 3: a real-world basis.)"}]'::jsonb,
   '[{"word": "BLIND)", "number": 1, "cat": 3, "t": [10]}, {"word": "ROCK-HEAD", "number": 1, "cat": 2, "t": [20]}, {"word": "BELLY-PLATE", "number": 1, "cat": 2, "t": [5]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [19]}, {"word": "TWIN-TAILS", "number": 1, "cat": 2, "t": [6]}, {"word": "LIGHT-TAIL", "number": 1, "cat": 2, "t": [0]}, {"word": "FLAMES", "number": 1, "cat": 2, "t": [18]}, {"word": "FINS", "number": 1, "cat": 2, "t": [2]}, {"word": "ANTENNAE", "number": 1, "cat": 2, "t": [9]}]'::jsonb,
   '[{"name": "Volbeat", "colour": "blue", "position": 0}, {"name": "Crobat", "colour": "neutral", "position": 1}, {"name": "Floatzel", "colour": "blue", "position": 2}, {"name": "Froakie", "colour": "neutral", "position": 3}, {"name": "Hitmonlee", "colour": "neutral", "position": 4}, {"name": "Larvitar", "colour": "blue", "position": 5}, {"name": "Buizel", "colour": "blue", "position": 6}, {"name": "Tangrowth", "colour": "neutral", "position": 7}, {"name": "Gorebyss", "colour": "neutral", "position": 8}, {"name": "Illumise", "colour": "blue", "position": 9}, {"name": "Deino", "colour": "blue", "position": 10}, {"name": "Shiinotic", "colour": "neutral", "position": 11}, {"name": "Purugly", "colour": "neutral", "position": 12}, {"name": "Frigibax", "colour": "neutral", "position": 13}, {"name": "Duosion", "colour": "neutral", "position": 14}, {"name": "Cyclizar", "colour": "neutral", "position": 15}, {"name": "Kingdra", "colour": "neutral", "position": 16}, {"name": "Happiny", "colour": "neutral", "position": 17}, {"name": "Chandelure", "colour": "blue", "position": 18}, {"name": "Drilbur", "colour": "blue", "position": 19}, {"name": "Bagon", "colour": "blue", "position": 20}, {"name": "Mandibuzz", "colour": "neutral", "position": 21}, {"name": "Pidgeot", "colour": "neutral", "position": 22}, {"name": "Mareanie", "colour": "neutral", "position": 23}, {"name": "Centiskorch", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-09-05', 'gen1',
   '[{"word": "SLUDGE", "number": 2, "cat": 3, "t": [11, 23], "explain": "They''re all based on the real-world blob of living sludge. (Category 3: a real-world basis.)"}, {"word": "FERRY", "number": 1, "cat": 3, "t": [4], "explain": "It''s from their Pok\u00e9dex lore \u2014 it ferries travellers across the sea. (Category 3: a real-world basis.)"}, {"word": "SPHERE", "number": 2, "cat": 2, "t": [7, 13], "explain": "You can spot it on the sprite \u2014 a Pok\u00e9 Ball shape. (Category 2: look at the sprite.)"}, {"word": "FOSSILISED", "number": 2, "cat": 5, "t": [15, 24], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re prehistoric fossils brought back to life. (Category 5: a deeper connection.)"}, {"word": "JELLYFISH", "number": 2, "cat": 4, "t": [18, 19], "explain": "They''re all based on the real-world jellyfish. (Category 4: a trickier grouping.)"}]'::jsonb,
   '[{"word": "CNIDARIAN", "number": 1, "cat": 3, "t": [19]}, {"word": "SCYTHE-ARMS", "number": 1, "cat": 2, "t": [15]}, {"word": "RED-JEWELS", "number": 1, "cat": 2, "t": [18]}, {"word": "PLESIOSAUR", "number": 1, "cat": 3, "t": [4]}, {"word": "BALL-SHAPE", "number": 1, "cat": 2, "t": [7]}, {"word": "MINERAL", "number": 1, "cat": 3, "t": [13]}, {"word": "OOZE-BODY", "number": 1, "cat": 2, "t": [23]}, {"word": "OOZING-BODY", "number": 1, "cat": 2, "t": [11]}, {"word": "SPIRAL-SHELL", "number": 1, "cat": 2, "t": [24]}]'::jsonb,
   '[{"name": "Diglett", "colour": "neutral", "position": 0}, {"name": "Venonat", "colour": "neutral", "position": 1}, {"name": "Psyduck", "colour": "neutral", "position": 2}, {"name": "Gloom", "colour": "neutral", "position": 3}, {"name": "Lapras", "colour": "blue", "position": 4}, {"name": "Weedle", "colour": "neutral", "position": 5}, {"name": "Hitmonlee", "colour": "neutral", "position": 6}, {"name": "Voltorb", "colour": "blue", "position": 7}, {"name": "Jigglypuff", "colour": "neutral", "position": 8}, {"name": "Dewgong", "colour": "neutral", "position": 9}, {"name": "Golbat", "colour": "neutral", "position": 10}, {"name": "Muk", "colour": "blue", "position": 11}, {"name": "Caterpie", "colour": "neutral", "position": 12}, {"name": "Electrode", "colour": "blue", "position": 13}, {"name": "Gyarados", "colour": "neutral", "position": 14}, {"name": "Kabutops", "colour": "blue", "position": 15}, {"name": "Dratini", "colour": "neutral", "position": 16}, {"name": "Dodrio", "colour": "neutral", "position": 17}, {"name": "Tentacruel", "colour": "blue", "position": 18}, {"name": "Tentacool", "colour": "blue", "position": 19}, {"name": "Zapdos", "colour": "neutral", "position": 20}, {"name": "Tangela", "colour": "neutral", "position": 21}, {"name": "Horsea", "colour": "neutral", "position": 22}, {"name": "Grimer", "colour": "blue", "position": 23}, {"name": "Omastar", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-05', 'mixed',
   '[{"word": "GEM", "number": 1, "cat": 2, "t": [4], "explain": "You can spot it on the sprite \u2014 a gemstone body. (Category 2: look at the sprite.)"}, {"word": "MOLTEN", "number": 2, "cat": 3, "t": [18, 24], "explain": "It''s from their Pok\u00e9dex lore \u2014 they''re made of molten lava. (Category 3: a real-world basis.)"}, {"word": "FROG", "number": 2, "cat": 3, "t": [3, 8], "explain": "They''re all based on the real-world frog. (Category 3: a real-world basis.)"}, {"word": "HIVE", "number": 2, "cat": 3, "t": [10, 11], "explain": "They''re all based on the real-world bee. (Category 3: a real-world basis.)"}, {"word": "SQUID", "number": 2, "cat": 4, "t": [6, 13], "explain": "They''re all based on the real-world squid. (Category 4: a trickier grouping.)"}]'::jsonb,
   '[{"word": "CROWN", "number": 1, "cat": 2, "t": [11]}, {"word": "MOLTEN-BODY", "number": 1, "cat": 2, "t": [24]}, {"word": "JEWEL-BODY", "number": 1, "cat": 2, "t": [4]}, {"word": "INSECT", "number": 1, "cat": 3, "t": [10]}, {"word": "GLOW-SPOTS", "number": 1, "cat": 2, "t": [6]}, {"word": "BUMPS", "number": 1, "cat": 2, "t": [8]}, {"word": "CHEEK-VIBRATIONS", "number": 1, "cat": 2, "t": [3]}, {"word": "MOLTEN", "number": 1, "cat": 2, "t": [18]}, {"word": "TENTACLE-ARMS", "number": 1, "cat": 2, "t": [13]}]'::jsonb,
   '[{"name": "Weepinbell", "colour": "neutral", "position": 0}, {"name": "Hattrem", "colour": "neutral", "position": 1}, {"name": "Miraidon", "colour": "neutral", "position": 2}, {"name": "Tympole", "colour": "blue", "position": 3}, {"name": "Carbink", "colour": "blue", "position": 4}, {"name": "Silvally", "colour": "neutral", "position": 5}, {"name": "Inkay", "colour": "blue", "position": 6}, {"name": "Tarountula", "colour": "neutral", "position": 7}, {"name": "Palpitoad", "colour": "blue", "position": 8}, {"name": "Arctovish", "colour": "neutral", "position": 9}, {"name": "Combee", "colour": "blue", "position": 10}, {"name": "Vespiquen", "colour": "blue", "position": 11}, {"name": "Oshawott", "colour": "neutral", "position": 12}, {"name": "Malamar", "colour": "blue", "position": 13}, {"name": "Roserade", "colour": "neutral", "position": 14}, {"name": "Togedemaru", "colour": "neutral", "position": 15}, {"name": "Chikorita", "colour": "neutral", "position": 16}, {"name": "Cinderace", "colour": "neutral", "position": 17}, {"name": "Magcargo", "colour": "blue", "position": 18}, {"name": "Wynaut", "colour": "neutral", "position": 19}, {"name": "Greavard", "colour": "neutral", "position": 20}, {"name": "Vanillite", "colour": "neutral", "position": 21}, {"name": "Surskit", "colour": "neutral", "position": 22}, {"name": "Chinchou", "colour": "neutral", "position": 23}, {"name": "Slugma", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-06', 'gen1',
   '[{"word": "DUCK-KNIGHT", "number": 1, "cat": 4, "t": [9], "explain": "It''s from their Pok\u00e9dex lore \u2014 the spring onion (leek) it carries. (Category 4: a trickier grouping.)"}, {"word": "SEA-DOG", "number": 2, "cat": 3, "t": [12, 15], "explain": "They''re all based on the real-world seal and sea lion. (Category 3: a real-world basis.)"}, {"word": "SPORES", "number": 2, "cat": 2, "t": [5, 24], "explain": "You can spot it on the sprite \u2014 the spores it puffs out. (Category 2: look at the sprite.)"}, {"word": "UNICORN", "number": 2, "cat": 3, "t": [1, 11], "explain": "They''re all based on the real-world unicorn. (Category 3: a real-world basis.)"}, {"word": "SUMO", "number": 2, "cat": 3, "t": [7, 14], "explain": "They''re based on sumo wrestlers. (Category 3: a real-world basis.)"}]'::jsonb,
   '[{"word": "HORN", "number": 1, "cat": 2, "t": [15]}, {"word": "HORSE", "number": 1, "cat": 3, "t": [1]}, {"word": "LEEK-STALK", "number": 1, "cat": 2, "t": [9]}, {"word": "GIANT-PETALS", "number": 1, "cat": 2, "t": [24]}, {"word": "MUSCLES", "number": 1, "cat": 2, "t": [14]}, {"word": "DROOL", "number": 1, "cat": 2, "t": [5]}, {"word": "SUPERPOWER", "number": 1, "cat": 2, "t": [7]}, {"word": "HOOVES", "number": 1, "cat": 2, "t": [11]}, {"word": "SLEEK-BODY", "number": 1, "cat": 2, "t": [12]}]'::jsonb,
   '[{"name": "Bulbasaur", "colour": "neutral", "position": 0}, {"name": "Rapidash", "colour": "blue", "position": 1}, {"name": "Pikachu", "colour": "neutral", "position": 2}, {"name": "Nidoqueen", "colour": "neutral", "position": 3}, {"name": "Primeape", "colour": "neutral", "position": 4}, {"name": "Gloom", "colour": "blue", "position": 5}, {"name": "Lickitung", "colour": "neutral", "position": 6}, {"name": "Machoke", "colour": "blue", "position": 7}, {"name": "Exeggutor", "colour": "neutral", "position": 8}, {"name": "Farfetch''d", "colour": "blue", "position": 9}, {"name": "Squirtle", "colour": "neutral", "position": 10}, {"name": "Ponyta", "colour": "blue", "position": 11}, {"name": "Dewgong", "colour": "blue", "position": 12}, {"name": "Gastly", "colour": "neutral", "position": 13}, {"name": "Machop", "colour": "blue", "position": 14}, {"name": "Seel", "colour": "blue", "position": 15}, {"name": "Mew", "colour": "neutral", "position": 16}, {"name": "Eevee", "colour": "neutral", "position": 17}, {"name": "Blastoise", "colour": "neutral", "position": 18}, {"name": "Muk", "colour": "neutral", "position": 19}, {"name": "Mankey", "colour": "neutral", "position": 20}, {"name": "Graveler", "colour": "neutral", "position": 21}, {"name": "Electabuzz", "colour": "neutral", "position": 22}, {"name": "Jolteon", "colour": "neutral", "position": 23}, {"name": "Vileplume", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-09-06', 'mixed',
   '[{"word": "SCARAB", "number": 1, "cat": 4, "t": [12], "explain": "They''re based on the scarab beetle. (Category 4: a trickier grouping.)"}, {"word": "HOARD", "number": 1, "cat": 2, "t": [4], "explain": "You can spot it on the sprite \u2014 a hoard of gold coins. (Category 2: look at the sprite.)"}, {"word": "PRIMATE", "number": 3, "cat": 3, "t": [7, 13, 23], "explain": "They''re all based on the real-world gorilla. (Category 3: a real-world basis.)"}, {"word": "WATERBIRD", "number": 2, "cat": 3, "t": [2, 15], "explain": "They''re all based on the real-world swan. (Category 3: a real-world basis.)"}, {"word": "WEASEL", "number": 2, "cat": 3, "t": [0, 16], "explain": "They''re all based on the real-world weasel. (Category 3: a real-world basis.)"}]'::jsonb,
   '[{"word": "CHEST-BODY", "number": 1, "cat": 2, "t": [4]}, {"word": "STICK-DRUMMER", "number": 1, "cat": 2, "t": [23]}, {"word": "LONG-NECK", "number": 1, "cat": 2, "t": [15]}, {"word": "TWIN-STICKS", "number": 1, "cat": 2, "t": [7]}, {"word": "LOG-DRUM", "number": 1, "cat": 2, "t": [13]}, {"word": "ROUND-BODY", "number": 1, "cat": 2, "t": [2]}, {"word": "CLAWS", "number": 1, "cat": 2, "t": [12]}, {"word": "SCOUT-TAIL", "number": 1, "cat": 2, "t": [0]}, {"word": "LONG-BODY", "number": 1, "cat": 2, "t": [16]}]'::jsonb,
   '[{"name": "Sentret", "colour": "blue", "position": 0}, {"name": "Obstagoon", "colour": "neutral", "position": 1}, {"name": "Ducklett", "colour": "blue", "position": 2}, {"name": "Grovyle", "colour": "neutral", "position": 3}, {"name": "Gimmighoul", "colour": "blue", "position": 4}, {"name": "Spearow", "colour": "neutral", "position": 5}, {"name": "Annihilape", "colour": "neutral", "position": 6}, {"name": "Thwackey", "colour": "blue", "position": 7}, {"name": "Seaking", "colour": "neutral", "position": 8}, {"name": "Aipom", "colour": "neutral", "position": 9}, {"name": "Exeggutor", "colour": "neutral", "position": 10}, {"name": "Bunnelby", "colour": "neutral", "position": 11}, {"name": "Nincada", "colour": "blue", "position": 12}, {"name": "Rillaboom", "colour": "blue", "position": 13}, {"name": "Skuntank", "colour": "neutral", "position": 14}, {"name": "Swanna", "colour": "blue", "position": 15}, {"name": "Furret", "colour": "blue", "position": 16}, {"name": "Starmie", "colour": "neutral", "position": 17}, {"name": "Swoobat", "colour": "neutral", "position": 18}, {"name": "Wishiwashi", "colour": "neutral", "position": 19}, {"name": "Croagunk", "colour": "neutral", "position": 20}, {"name": "Pansage", "colour": "neutral", "position": 21}, {"name": "Relicanth", "colour": "neutral", "position": 22}, {"name": "Grookey", "colour": "blue", "position": 23}, {"name": "Remoraid", "colour": "neutral", "position": 24}]'::jsonb)
on conflict (puzzle_date, pool) do update
  set clues = excluded.clues, hints = excluded.hints, tiles = excluded.tiles;
