-- test_today.sql : fresh 2026-08-21 daily puzzles (fact-bank creativity test)

insert into public.daily_puzzles (puzzle_date, pool, clues, hints, tiles) values
  ('2026-08-21', 'gen1',
   '[{"word": "TEAM-ROCKET", "number": 2, "cat": 3, "t": [3, 24]}, {"word": "PITCHER", "number": 2, "cat": 3, "t": [6, 20]}, {"word": "VAMPIRE", "number": 2, "cat": 4, "t": [5, 16]}, {"word": "DOODLER", "number": 1, "cat": 3, "t": [22]}, {"word": "MONOTREME", "number": 2, "cat": 4, "t": [9, 11]}]'::jsonb,
   '[{"word": "HEADACHE", "number": 1, "cat": 3, "t": [9]}, {"word": "BIG-FANGS", "number": 1, "cat": 2, "t": [5]}, {"word": "RED-GEM", "number": 1, "cat": 2, "t": [11]}, {"word": "HOOK-NOSE", "number": 1, "cat": 2, "t": [20]}, {"word": "STALK", "number": 1, "cat": 2, "t": [6]}, {"word": "SPHERE", "number": 1, "cat": 2, "t": [22]}, {"word": "SMOG", "number": 1, "cat": 2, "t": [24]}, {"word": "NO-EYES", "number": 1, "cat": 2, "t": [16]}, {"word": "HOOD", "number": 1, "cat": 2, "t": [3]}]'::jsonb,
   '[{"name": "Doduo", "colour": "neutral", "position": 0}, {"name": "Parasect", "colour": "neutral", "position": 1}, {"name": "Nidorina", "colour": "neutral", "position": 2}, {"name": "Arbok", "colour": "blue", "position": 3}, {"name": "Horsea", "colour": "neutral", "position": 4}, {"name": "Golbat", "colour": "blue", "position": 5}, {"name": "Bellsprout", "colour": "blue", "position": 6}, {"name": "Marowak", "colour": "neutral", "position": 7}, {"name": "Muk", "colour": "neutral", "position": 8}, {"name": "Psyduck", "colour": "blue", "position": 9}, {"name": "Golem", "colour": "neutral", "position": 10}, {"name": "Golduck", "colour": "blue", "position": 11}, {"name": "Rhydon", "colour": "neutral", "position": 12}, {"name": "Drowzee", "colour": "neutral", "position": 13}, {"name": "Charmeleon", "colour": "neutral", "position": 14}, {"name": "Diglett", "colour": "neutral", "position": 15}, {"name": "Zubat", "colour": "blue", "position": 16}, {"name": "Sandshrew", "colour": "neutral", "position": 17}, {"name": "Eevee", "colour": "neutral", "position": 18}, {"name": "Wartortle", "colour": "neutral", "position": 19}, {"name": "Weepinbell", "colour": "blue", "position": 20}, {"name": "Vaporeon", "colour": "neutral", "position": 21}, {"name": "Jigglypuff", "colour": "blue", "position": 22}, {"name": "Fearow", "colour": "neutral", "position": 23}, {"name": "Weezing", "colour": "blue", "position": 24}]'::jsonb),
  ('2026-08-21', 'mixed',
   '[{"word": "PENGUIN", "number": 2, "cat": 3, "t": [1, 21]}, {"word": "PUNK-ROCKER", "number": 1, "cat": 3, "t": [23]}, {"word": "DRUMMER", "number": 1, "cat": 3, "t": [10]}, {"word": "PALINDROME", "number": 3, "cat": 5, "t": [5, 15, 18]}, {"word": "ICE-CREAM", "number": 2, "cat": 4, "t": [0, 4]}]'::jsonb,
   '[{"word": "ICE-HEAD", "number": 1, "cat": 2, "t": [1]}, {"word": "CAPE", "number": 1, "cat": 2, "t": [21]}, {"word": "HEART", "number": 1, "cat": 2, "t": [15]}, {"word": "ICE-CONE", "number": 1, "cat": 2, "t": [4]}, {"word": "MOHAWK", "number": 1, "cat": 2, "t": [23]}, {"word": "TWIN-SCOOP", "number": 1, "cat": 2, "t": [0]}, {"word": "LOG-DRUM", "number": 1, "cat": 2, "t": [10]}, {"word": "LONG-NECK", "number": 1, "cat": 2, "t": [18]}, {"word": "FLUFFY-RUFF", "number": 1, "cat": 2, "t": [5]}]'::jsonb,
   '[{"name": "Vanilluxe", "colour": "blue", "position": 0}, {"name": "Eiscue", "colour": "blue", "position": 1}, {"name": "Lumineon", "colour": "neutral", "position": 2}, {"name": "Magikarp", "colour": "neutral", "position": 3}, {"name": "Vanillite", "colour": "blue", "position": 4}, {"name": "Eevee", "colour": "blue", "position": 5}, {"name": "Hippowdon", "colour": "neutral", "position": 6}, {"name": "Drifloon", "colour": "neutral", "position": 7}, {"name": "Mudsdale", "colour": "neutral", "position": 8}, {"name": "Mienshao", "colour": "neutral", "position": 9}, {"name": "Rillaboom", "colour": "blue", "position": 10}, {"name": "Pikachu", "colour": "neutral", "position": 11}, {"name": "Dewott", "colour": "neutral", "position": 12}, {"name": "Caterpie", "colour": "neutral", "position": 13}, {"name": "Sizzlipede", "colour": "neutral", "position": 14}, {"name": "Alomomola", "colour": "blue", "position": 15}, {"name": "Grovyle", "colour": "neutral", "position": 16}, {"name": "Flab\u00e9b\u00e9", "colour": "neutral", "position": 17}, {"name": "Girafarig", "colour": "blue", "position": 18}, {"name": "Excadrill", "colour": "neutral", "position": 19}, {"name": "Baltoy", "colour": "neutral", "position": 20}, {"name": "Piplup", "colour": "blue", "position": 21}, {"name": "Bergmite", "colour": "neutral", "position": 22}, {"name": "Toxtricity", "colour": "blue", "position": 23}, {"name": "Tapu Lele", "colour": "neutral", "position": 24}]'::jsonb)
on conflict (puzzle_date, pool) do update
  set clues = excluded.clues, hints = excluded.hints, tiles = excluded.tiles;
