-- test_today.sql : fresh 2026-08-21 daily puzzles (fact-bank creativity test)

insert into public.daily_puzzles (puzzle_date, pool, clues, hints, tiles) values
  ('2026-08-21', 'gen1',
   '[{"word": "TEAM-ROCKET", "number": 2, "cat": 3, "t": [1, 3]}, {"word": "VAMPIRE", "number": 2, "cat": 4, "t": [5, 20]}, {"word": "MONOTREME", "number": 2, "cat": 4, "t": [11, 22]}, {"word": "DOODLER", "number": 1, "cat": 3, "t": [19]}, {"word": "PITCHER", "number": 2, "cat": 3, "t": [13, 14]}]'::jsonb,
   '[{"word": "STALK", "number": 1, "cat": 2, "t": [14]}, {"word": "HOOD", "number": 1, "cat": 2, "t": [1]}, {"word": "HEADACHE", "number": 1, "cat": 3, "t": [22]}, {"word": "SPHERE", "number": 1, "cat": 2, "t": [19]}, {"word": "SMOG", "number": 1, "cat": 2, "t": [3]}, {"word": "BIG-FANGS", "number": 1, "cat": 2, "t": [5]}, {"word": "RED-GEM", "number": 1, "cat": 2, "t": [11]}, {"word": "NO-EYES", "number": 1, "cat": 2, "t": [20]}, {"word": "HOOK-NOSE", "number": 1, "cat": 2, "t": [13]}]'::jsonb,
   '[{"name": "Mew", "colour": "neutral", "position": 0}, {"name": "Arbok", "colour": "blue", "position": 1}, {"name": "Onix", "colour": "neutral", "position": 2}, {"name": "Weezing", "colour": "blue", "position": 3}, {"name": "Drowzee", "colour": "neutral", "position": 4}, {"name": "Golbat", "colour": "blue", "position": 5}, {"name": "Parasect", "colour": "neutral", "position": 6}, {"name": "Charmeleon", "colour": "neutral", "position": 7}, {"name": "Golem", "colour": "neutral", "position": 8}, {"name": "Sandshrew", "colour": "neutral", "position": 9}, {"name": "Metapod", "colour": "neutral", "position": 10}, {"name": "Golduck", "colour": "blue", "position": 11}, {"name": "Spearow", "colour": "neutral", "position": 12}, {"name": "Weepinbell", "colour": "blue", "position": 13}, {"name": "Bellsprout", "colour": "blue", "position": 14}, {"name": "Nidorina", "colour": "neutral", "position": 15}, {"name": "Gloom", "colour": "neutral", "position": 16}, {"name": "Kabuto", "colour": "neutral", "position": 17}, {"name": "Marowak", "colour": "neutral", "position": 18}, {"name": "Jigglypuff", "colour": "blue", "position": 19}, {"name": "Zubat", "colour": "blue", "position": 20}, {"name": "Mankey", "colour": "neutral", "position": 21}, {"name": "Psyduck", "colour": "blue", "position": 22}, {"name": "Poliwrath", "colour": "neutral", "position": 23}, {"name": "Beedrill", "colour": "neutral", "position": 24}]'::jsonb),
  ('2026-08-21', 'mixed',
   '[{"word": "PALINDROME", "number": 3, "cat": 5, "t": [11, 15, 24]}, {"word": "PENGUIN", "number": 2, "cat": 3, "t": [2, 4]}, {"word": "DRUMMER", "number": 1, "cat": 3, "t": [14]}, {"word": "PUNK-ROCKER", "number": 1, "cat": 3, "t": [20]}, {"word": "ICE-CREAM", "number": 2, "cat": 4, "t": [13, 22]}]'::jsonb,
   '[{"word": "ICE-CONE", "number": 1, "cat": 2, "t": [13]}, {"word": "HEART", "number": 1, "cat": 2, "t": [11]}, {"word": "FLUFFY-RUFF", "number": 1, "cat": 2, "t": [15]}, {"word": "LONG-NECK", "number": 1, "cat": 2, "t": [24]}, {"word": "TWIN-SCOOP", "number": 1, "cat": 2, "t": [22]}, {"word": "LOG-DRUM", "number": 1, "cat": 2, "t": [14]}, {"word": "CAPE", "number": 1, "cat": 2, "t": [2]}, {"word": "MOHAWK", "number": 1, "cat": 2, "t": [20]}, {"word": "ICE-HEAD", "number": 1, "cat": 2, "t": [4]}]'::jsonb,
   '[{"name": "Drilbur", "colour": "neutral", "position": 0}, {"name": "Cacnea", "colour": "neutral", "position": 1}, {"name": "Piplup", "colour": "blue", "position": 2}, {"name": "Calyrex", "colour": "neutral", "position": 3}, {"name": "Eiscue", "colour": "blue", "position": 4}, {"name": "Torchic", "colour": "neutral", "position": 5}, {"name": "Mienfoo", "colour": "neutral", "position": 6}, {"name": "Klawf", "colour": "neutral", "position": 7}, {"name": "Roaring Moon", "colour": "neutral", "position": 8}, {"name": "Ceruledge", "colour": "neutral", "position": 9}, {"name": "Dragonite", "colour": "neutral", "position": 10}, {"name": "Alomomola", "colour": "blue", "position": 11}, {"name": "Weedle", "colour": "neutral", "position": 12}, {"name": "Vanillite", "colour": "blue", "position": 13}, {"name": "Rillaboom", "colour": "blue", "position": 14}, {"name": "Eevee", "colour": "blue", "position": 15}, {"name": "Ursaluna", "colour": "neutral", "position": 16}, {"name": "Bastiodon", "colour": "neutral", "position": 17}, {"name": "Pyukumuku", "colour": "neutral", "position": 18}, {"name": "Delphox", "colour": "neutral", "position": 19}, {"name": "Toxtricity", "colour": "blue", "position": 20}, {"name": "Nidorina", "colour": "neutral", "position": 21}, {"name": "Vanilluxe", "colour": "blue", "position": 22}, {"name": "Corphish", "colour": "neutral", "position": 23}, {"name": "Girafarig", "colour": "blue", "position": 24}]'::jsonb)
on conflict (puzzle_date, pool) do update
  set clues = excluded.clues, hints = excluded.hints, tiles = excluded.tiles;
