#!/usr/bin/env python3
"""
Hand-curated overlay for the daily fact bank — the SUBJECTIVE columns that can't
be pulled from data: real-world inspiration (based_on), distinctive sprite
features (sprite), signature move, Pokedex flavour / puns (lore), folklore origin
(mythology), distinctive location, popular trainer/character (trainer), fandom
nickname/meme (nickname), secondary colour, animal archetype (arch), and role.

Authored generation by generation. Fields are left EMPTY where a mon genuinely
has no famous trainer / meme / mythology — blank is correct, not fabricated.
Run this to (re)write curated_overlay.json, then run build_facts.py.
"""
import json, os
HERE=os.path.dirname(os.path.abspath(__file__))
DATA={}
def E(name, arch=None, based=None, sprite=None, sig="", lore=None, myth=None,
      loc=None, trn=None, nick=None, c2="", role=None, wk=1):
    DATA[name]=dict(arch=arch or [], based_on=based or [], sprite=sprite or [],
        signature_move=sig, lore=lore or [], mythology=myth or [], location=loc or [],
        trainer=trn or [], nickname=nick or [], color_secondary=c2, role=role or [], wk=wk)

# ============================== GEN 1 (Kanto) ==============================
E("Bulbasaur", arch=["toad","dinosaur"], based=["frog","plant bulb","seed"], sprite=["back-bulb","fangs"], lore=["starter"], trn=["Ash"], role=["starter"], c2="teal")
E("Ivysaur", arch=["toad","dinosaur"], based=["frog","flower bud"], sprite=["back-bud","fangs"], c2="pink")
E("Venusaur", arch=["toad","dinosaur"], based=["frog","toad","rafflesia flower"], sprite=["back-flower","fangs"], sig="Frenzy Plant", role=["starter","mega","gmax"], c2="pink")
E("Charmander", arch=["lizard","salamander"], based=["salamander","fire lizard"], sprite=["flame-tail","claws"], lore=["starter","tail flame = life"], trn=["Ash"], role=["starter"], c2="cream")
E("Charmeleon", arch=["lizard","salamander"], based=["salamander"], sprite=["flame-tail","head-horn","claws"], c2="cream")
E("Charizard", arch=["dragon","lizard"], based=["dragon","winged fire lizard"], sprite=["wings","flame-tail","fangs"], sig="Blast Burn", lore=["not a Dragon type despite looks"], trn=["Ash"], role=["starter","mega","gmax"], nick=["fan favourite"], c2="cream")
E("Squirtle", arch=["turtle"], based=["turtle"], sprite=["shell","curl-tail"], lore=["starter"], trn=["Ash","Squirtle Squad"], role=["starter"], c2="brown")
E("Wartortle", arch=["turtle"], based=["turtle"], sprite=["shell","furry-ears","fluffy-tail"], c2="white")
E("Blastoise", arch=["turtle"], based=["tortoise","water cannons"], sprite=["shell","back-cannons"], sig="Hydro Cannon", role=["starter","mega","gmax"], c2="brown")
E("Caterpie", arch=["insect","caterpillar"], based=["caterpillar","swallowtail larva"], sprite=["antenna","osmeterium"], trn=["Ash"], c2="yellow")
E("Metapod", arch=["insect","pupa"], based=["chrysalis"], sprite=["hard-shell"], lore=["only knows Harden"])
E("Butterfree", arch=["insect","butterfly"], based=["butterfly","moth"], sprite=["wings","big-eyes"], trn=["Ash (released it)"], role=["gmax"], nick=["Ash's goodbye episode"], c2="blue")
E("Weedle", arch=["insect","caterpillar"], based=["hairy caterpillar","larva"], sprite=["nose-horn","tail-stinger"], c2="brown")
E("Kakuna", arch=["insect","pupa"], based=["cocoon"], sprite=["hard-shell"])
E("Beedrill", arch=["insect","wasp"], based=["wasp","hornet"], sprite=["arm-stingers","wings","tail-stinger"], role=["mega"], c2="black")
E("Pidgey", arch=["bird"], based=["pigeon","sparrow"], sprite=["beak","crest"], trn=["Ash"], c2="cream")
E("Pidgeotto", arch=["bird","raptor"], based=["hawk","falcon"], sprite=["crest","talons"], c2="cream")
E("Pidgeot", arch=["bird","raptor"], based=["eagle","hawk"], sprite=["long-crest","wings"], role=["mega"], c2="cream")
E("Rattata", arch=["rodent","rat"], based=["rat"], sprite=["buck-teeth","whiskers"], nick=["FEAR strategy"], c2="cream")
E("Raticate", arch=["rodent","rat"], based=["rat"], sprite=["buck-teeth","whiskers"], nick=["Ash's Raticate (trade myth)"], c2="cream")
E("Spearow", arch=["bird"], based=["sparrow"], sprite=["beak","short-wings"], trn=["attacked Ash ep.1"], c2="pink")
E("Fearow", arch=["bird","raptor"], based=["eagle"], sprite=["long-beak","long-neck"], c2="pink")
E("Ekans", arch=["serpent","snake"], based=["cobra","snake"], sprite=["rattle-tail","fangs"], lore=["name = snake backwards"], trn=["Jessie (Team Rocket)"], c2="yellow")
E("Arbok", arch=["serpent","snake","cobra"], based=["cobra"], sprite=["hood-pattern","fangs"], lore=["name = kobra backwards"], trn=["Jessie (Team Rocket)"], c2="yellow")
E("Pikachu", arch=["rodent","mouse"], based=["mouse","pika"], sprite=["cheek-pouches","lightning-tail"], sig="Volt Tackle", loc=["Viridian Forest"], trn=["Ash","Pikachu"], role=["mascot","gmax"], nick=["franchise mascot"], c2="brown")
E("Raichu", arch=["rodent","mouse"], based=["mouse"], sprite=["cheeks","thin-tail"], c2="brown")
E("Sandshrew", arch=["pangolin","armadillo"], based=["pangolin","armadillo"], sprite=["curl","claws"], loc=["desert routes"], c2="cream")
E("Sandslash", arch=["pangolin","armadillo"], based=["pangolin","echidna"], sprite=["back-spikes","claws"], c2="brown")
E("Nidoran♀", arch=["rodent","rabbit"], based=["rabbit","poison rodent"], sprite=["small-spines","whiskers"], lore=["one of few gendered species"], c2="red")
E("Nidorina", arch=["rodent","rabbit"], based=["rabbit"], sprite=["spines","ears"], c2="cream")
E("Nidoqueen", arch=["pachyderm"], based=["rhino/armoured beast (queen)"], sprite=["scales","spikes","tail"], lore=["royalty (queen)"], role=[], c2="cream")
E("Nidoran♂", arch=["rodent","rabbit"], based=["rabbit","poison rodent"], sprite=["large-ears","forehead-horn"], c2="red")
E("Nidorino", arch=["rodent","rabbit"], based=["rabbit"], sprite=["horn","spines"], c2="red")
E("Nidoking", arch=["pachyderm"], based=["rhino/armoured beast (king)"], sprite=["head-horn","tail","scales"], sig="", lore=["royalty (king)"], c2="cream")
E("Clefairy", arch=["fairy"], based=["fairy","moon sprite"], sprite=["curl-forehead","small-wings"], myth=["arrived from space / moon"], loc=["Mt. Moon"], c2="pink")
E("Clefable", arch=["fairy"], based=["fairy","moon sprite"], sprite=["wings","pointed-ears"], myth=["moonlight folklore"], loc=["Mt. Moon"], c2="pink")
E("Vulpix", arch=["fox","canine"], based=["fox"], sprite=["curled-tails","curls"], myth=["kitsune (six-tailed fox)"], c2="orange")
E("Ninetales", arch=["fox","canine"], based=["nine-tailed fox"], sprite=["nine-tails","mane"], myth=["kitsune / kyubi (1000-year fox)"], nick=["curse lore"], c2="cream")
E("Jigglypuff", arch=["fairy"], based=["balloon","fairy"], sprite=["round-body","big-eyes","curl"], sig="Sing", lore=["draws on faces when you sleep"], trn=["anime singer"], role=["mascot"], c2="")
E("Wigglytuff", arch=["fairy"], based=["balloon","rabbit"], sprite=["round-body","rabbit-ears"], c2="")
E("Zubat", arch=["chiropteran","bat"], based=["bat"], sprite=["no-eyes","wings","fangs"], loc=["caves (everywhere)"], nick=["cave nuisance / Supersonic"], c2="purple")
E("Golbat", arch=["chiropteran","bat"], based=["bat"], sprite=["huge-mouth","fangs","wings"], c2="purple")
E("Oddish", arch=["plant"], based=["mandrake","nazuna weed"], sprite=["leaf-head","blue-body"], loc=["grass at night"], c2="green")
E("Gloom", arch=["plant"], based=["mandrake","corpse flower"], sprite=["drool","flower-head"], c2="orange")
E("Vileplume", arch=["plant"], based=["rafflesia (corpse flower)"], sprite=["giant-petals"], c2="red")
E("Paras", arch=["insect","crab"], based=["cicada nymph","cordyceps fungus"], sprite=["mushrooms","claws"], myth=["zombie fungus lore"], c2="orange")
E("Parasect", arch=["insect","crab"], based=["cicada + cordyceps"], sprite=["big-mushroom","dead-eyes"], lore=["the fungus controls the host"], myth=["cordyceps zombie"], c2="orange")
E("Venonat", arch=["insect"], based=["moth larva","fly"], sprite=["big-red-eyes","fur"], c2="red")
E("Venomoth", arch=["insect","moth"], based=["moth"], sprite=["wings","dust-scales"], c2="blue")
E("Diglett", arch=["mole"], based=["mole"], sprite=["nose","underground-body"], loc=["Diglett's Cave"], nick=["what's under Diglett?"], c2="brown")
E("Dugtrio", arch=["mole"], based=["moles (triplet)"], sprite=["three-heads"], loc=["Diglett's Cave"], c2="brown")
E("Meowth", arch=["feline","cat"], based=["cat","maneki-neko lucky cat"], sprite=["coin-charm","whiskers"], sig="Pay Day", myth=["maneki-neko (beckoning cat)"], trn=["Team Rocket (talking Meowth)"], role=["gmax"], nick=["Team Rocket's Meowth"], c2="")
E("Persian", arch=["feline","cat"], based=["cat","siamese"], sprite=["forehead-gem","whiskers"], trn=["Giovanni"], c2="")
E("Psyduck", arch=["duck","platypus"], based=["duck","platypus"], sprite=["blank-stare","headache-hands"], lore=["psychic when headache peaks"], trn=["Misty"], nick=["perpetual headache"], c2="cream")
E("Golduck", arch=["platypus"], based=["kappa","platypus"], sprite=["forehead-gem","webbed"], myth=["kappa (water sprite)"], c2="")
E("Mankey", arch=["primate","monkey"], based=["monkey","macaque"], sprite=["angry-face","fists"], lore=["always furious"], trn=["Ash (Primeape)"], c2="brown")
E("Primeape", arch=["primate","monkey"], based=["monkey"], sprite=["angry","fists","bound-hands"], sig="Rage Fist (via Annihilape)", c2="brown")
E("Growlithe", arch=["canine","dog"], based=["dog","shisa lion-dog"], sprite=["stripes","fluffy-mane"], trn=["Officer Jenny (Growlithe/Arcanine)"], c2="cream")
E("Arcanine", arch=["canine","dog"], based=["Chinese guardian lion (shisa)","kirin"], sprite=["stripes","mane"], lore=["'Legendary Pokemon' in the Pokedex"], myth=["shisa / komainu"], c2="cream")
E("Poliwag", arch=["frog","tadpole"], based=["tadpole"], sprite=["belly-swirl","tail"], lore=["swirl = visible guts"], c2="white")
E("Poliwhirl", arch=["frog"], based=["tadpole"], sprite=["belly-swirl","gloved-hands"], c2="white")
E("Poliwrath", arch=["frog"], based=["frog","boxer"], sprite=["muscles","belly-swirl"], c2="white")
E("Abra", arch=["psychic"], based=["psychic / yogi","fennec fox"], sprite=["sleeps-18h","fox-ears"], sig="Teleport", lore=["always asleep"], c2="brown")
E("Kadabra", arch=["psychic"], based=["Uri Geller (spoon-bender)","fox"], sprite=["spoon","forehead-star","whiskers"], lore=["Uri Geller lawsuit → absent for 20 years"], nick=["Uri Geller"], c2="yellow")
E("Alakazam", arch=["psychic"], based=["Uri Geller","psychic sage"], sprite=["twin-spoons","mustache","armour"], sig="", lore=["IQ 5000; huge brain"], role=["mega"], c2="yellow")
E("Machop", arch=["primate","humanoid"], based=["bodybuilder","superpower human"], sprite=["muscles","tail"], c2="")
E("Machoke", arch=["primate","humanoid"], based=["wrestler"], sprite=["muscles","power-save-belt"], c2="")
E("Machamp", arch=["primate","humanoid"], based=["four-armed wrestler","Asura"], sprite=["four-arms","belt"], sig="Dynamic Punch", role=["gmax"], c2="")
E("Bellsprout", arch=["plant"], based=["pitcher plant","bellflower"], sprite=["bell-head","stem-body"], c2="brown")
E("Weepinbell", arch=["plant"], based=["pitcher plant"], sprite=["pitcher-body","hook"], c2="")
E("Victreebel", arch=["plant"], based=["pitcher plant","venus flytrap"], sprite=["pitcher-mouth","vine"], trn=["James (Team Rocket)"], c2="yellow")
E("Tentacool", arch=["cnidarian","jellyfish"], based=["jellyfish"], sprite=["red-orbs","tentacles"], loc=["surfing on the sea"], c2="red")
E("Tentacruel", arch=["cnidarian","jellyfish"], based=["portuguese man o' war"], sprite=["red-jewels","tentacles"], c2="red")
E("Geodude", arch=["golem"], based=["rock","boulder"], sprite=["muscled-arms","rocky-body"], loc=["caves / Rock Tunnel"], nick=["Rock-throwing meme"], c2="")
E("Graveler", arch=["golem"], based=["boulder"], sprite=["four-arms","rocky-body"], c2="")
E("Golem", arch=["golem"], based=["boulder","golem"], sprite=["shell-plates","stubby-limbs"], sig="", myth=["golem"], c2="green")
E("Ponyta", arch=["equine","horse"], based=["horse"], sprite=["fire-mane","hooves"], c2="cream")
E("Rapidash", arch=["equine","horse","unicorn"], based=["unicorn","horse"], sprite=["fire-mane","horn"], c2="cream")
E("Slowpoke", arch=["hippo","salamander"], based=["axolotl","hippo"], sprite=["dopey-face","pink-tail"], lore=["takes 5s to feel pain"], nick=["derpy / slow"], c2="")
E("Slowbro", arch=["hippo"], based=["hermit + shellfish symbiosis"], sprite=["shell-on-tail"], lore=["Shellder bites its tail"], role=["mega"], c2="")
E("Magnemite", arch=["mineral"], based=["magnet","UFO"], sprite=["magnets","screws","single-eye"], c2="gray")
E("Magneton", arch=["mineral"], based=["magnets (three fused)","UFO"], sprite=["three-fused"], c2="gray")
E("Farfetch'd", arch=["bird","duck"], based=["wild duck with leek (kamo negi idiom)"], sprite=["leek-stalk","beak"], lore=["Japanese idiom 'duck comes with spring onions'"], c2="")
E("Doduo", arch=["bird","ratite"], based=["ostrich","emu"], sprite=["two-heads","long-legs"], c2="cream")
E("Dodrio", arch=["bird","ratite"], based=["ostrich (three heads)"], sprite=["three-heads","long-legs"], c2="cream")
E("Seel", arch=["pinniped","seal"], based=["sea lion","seal"], sprite=["horn","tusk"], c2="")
E("Dewgong", arch=["pinniped"], based=["dugong","sea lion"], sprite=["sleek-body","horn"], c2="")
E("Grimer", arch=["amorphous"], based=["sludge","pollution"], sprite=["ooze-body","grin"], myth=["born from polluted sludge"], c2="")
E("Muk", arch=["amorphous"], based=["toxic sludge","pollution"], sprite=["oozing-body"], role=["gmax"], c2="")
E("Shellder", arch=["mollusc","clam"], based=["clam","bivalve"], sprite=["tongue","clam-shell"], lore=["bites Slowpoke's tail"], c2="")
E("Cloyster", arch=["mollusc","bivalve"], based=["oyster (pearl)"], sprite=["spiked-shell","face-inside"], sig="", c2="purple")
E("Gastly", arch=["ghost"], based=["will-o'-wisp","poison gas","onibi"], sprite=["gas-cloud","eyes"], myth=["onibi / ghost gas"], loc=["Pokemon Tower"], c2="black")
E("Haunter", arch=["ghost"], based=["ghost","boogeyman"], sprite=["floating-hands","tongue"], loc=["Pokemon Tower"], c2="black")
E("Gengar", arch=["ghost"], based=["shadow / doppelganger (gengar = 'doppelganger')"], sprite=["wide-grin","spikes"], sig="", myth=["your shadow come alive"], trn=["Agatha"], role=["mega","gmax"], nick=["Clefable's shadow theory"], c2="")
E("Onix", arch=["serpent"], based=["rock snake","tunnelling serpent"], sprite=["boulder-body","head-horn"], loc=["Rock Tunnel"], trn=["Brock"], c2="")
E("Drowzee", arch=["tapir"], based=["tapir (baku dream-eater)"], sprite=["pendulum-hands","trunk"], myth=["baku (eats dreams)"], c2="yellow")
E("Hypno", arch=["tapir"], based=["hypnotist","baku"], sprite=["pendulum","collar-ruff"], sig="", myth=["baku dream-eater"], nick=["creepy dex entries"], c2="")
E("Krabby", arch=["crustacean","crab"], based=["crab"], sprite=["pincers","claws"], c2="white")
E("Kingler", arch=["crustacean","crab"], based=["crab (giant claw)"], sprite=["huge-claw"], trn=["Ash"], role=["gmax"], c2="")
E("Voltorb", arch=["mineral"], based=["Poke Ball"], sprite=["ball-shape","face"], lore=["disguised as a Poke Ball"], nick=["Self-Destruct troll"], c2="white")
E("Electrode", arch=["mineral"], based=["Poke Ball (upside down)"], sprite=["ball-shape","grin"], nick=["Explosion / suicide bomber"], c2="white")
E("Exeggcute", arch=["plant"], based=["eggs / seeds (coconut)"], sprite=["six-eggs","cracks"], lore=["actually seeds, not eggs"], c2="pink")
E("Exeggutor", arch=["plant"], based=["coconut palm tree"], sprite=["three-heads","palm-trunk"], nick=["Alolan long-neck meme"], c2="brown")
E("Cubone", arch=["mammal"], based=["orphaned dinosaur wearing a skull"], sprite=["skull-helmet","bone-club"], lore=["wears its dead mother's skull; cries"], myth=["Marowak ghost (Lavender Town)"], nick=["saddest backstory"], c2="brown")
E("Marowak", arch=["mammal"], based=["skull-wearing beast"], sprite=["skull-helmet","bone-club"], loc=["Pokemon Tower ghost"], myth=["vengeful ghost of its mother"], c2="brown")
E("Hitmonlee", arch=["humanoid"], based=["Bruce Lee (kickboxer)"], sprite=["spring-legs","no-head-neck"], sig="High Jump Kick", lore=["name from Bruce Lee"], nick=["Bruce Lee"], c2="")
E("Hitmonchan", arch=["humanoid"], based=["Jackie Chan (boxer)"], sprite=["boxing-gloves"], sig="", lore=["name from Jackie Chan"], nick=["Jackie Chan"], c2="")
E("Lickitung", arch=["mammal"], based=["licking beast","namekuji"], sprite=["long-tongue"], c2="cream")
E("Koffing", arch=["amorphous"], based=["poison gas balloon","sea mine"], sprite=["skull-and-crossbones","gas"], trn=["James (Team Rocket)"], c2="purple")
E("Weezing", arch=["amorphous"], based=["twin gas balloons","smog"], sprite=["twin-heads","gas"], trn=["James (Team Rocket)"], role=[], c2="purple")
E("Rhyhorn", arch=["pachyderm","rhino"], based=["rhinoceros","dinosaur"], sprite=["nose-horn","armour-hide"], trn=["Ash's mum races them"], c2="gray")
E("Rhydon", arch=["pachyderm","rhino"], based=["rhino","Godzilla-style kaiju"], sprite=["drill-horn","tail"], lore=["first Pokemon ever designed"], c2="gray")
E("Chansey", arch=["mammal"], based=["egg-bearing fairy","luck"], sprite=["belly-egg-pouch"], lore=["hard to catch; gives lots of XP"], trn=["Nurse Joy"], nick=["EXP grind / low catch rate"], c2="white")
E("Tangela", arch=["plant"], based=["mass of vines","seaweed"], sprite=["blue-vines","red-boots"], c2="blue")
E("Kangaskhan", arch=["marsupial","kangaroo"], based=["kangaroo (with joey)"], sprite=["belly-pouch","baby"], lore=["Genghis Khan pun"], role=["mega"], c2="")
E("Horsea", arch=["fish","seahorse"], based=["seahorse"], sprite=["snout","dorsal-fin"], c2="")
E("Seadra", arch=["fish","seahorse"], based=["seahorse","dragon"], sprite=["spines","fins"], c2="")
E("Goldeen", arch=["fish"], based=["goldfish"], sprite=["head-horn","flowing-fins"], nick=["only knows Splash/Peck meme"], c2="white")
E("Seaking", arch=["fish"], based=["goldfish","koi"], sprite=["head-horn","koi-fins"], c2="white")
E("Staryu", arch=["echinoderm","starfish"], based=["starfish"], sprite=["core-gem","star-shape"], trn=["Misty"], c2="brown")
E("Starmie", arch=["echinoderm","starfish"], based=["starfish (two stars)"], sprite=["core-gem","spinning"], trn=["Misty"], nick=["'it's a UFO'"], c2="purple")
E("Mr. Mime", arch=["humanoid"], based=["mime / clown"], sprite=["mime-gloves","invisible-walls"], sig="", lore=["makes invisible barriers"], trn=["Ash's mum's Mr. Mime (Mimey)"], c2="red")
E("Scyther", arch=["insect","mantis"], based=["praying mantis"], sprite=["scythe-arms","wings"], c2="cream")
E("Jynx", arch=["humanoid"], based=["opera singer","Yuki-onna / ganguro"], sprite=["gown","lips"], myth=["Yuki-onna (snow woman)"], nick=["design controversy"], c2="red")
E("Electabuzz", arch=["humanoid"], based=["oni (demon)"], sprite=["stripes","horns"], lore=["rival to Magmar"], c2="black")
E("Magmar", arch=["humanoid"], based=["oni","duck-billed fire beast"], sprite=["duck-bill","flame-body"], lore=["rival to Electabuzz"], c2="yellow")
E("Pinsir", arch=["insect","beetle"], based=["stag beetle"], sprite=["horn-pincers"], role=["mega"], c2="")
E("Tauros", arch=["bovine","bull"], based=["bull"], sprite=["three-tails","head-horns"], loc=["Safari Zone"], c2="cream")
E("Magikarp", arch=["fish","carp"], based=["carp (Chinese dragon-gate legend)"], sprite=["whiskers","floppy"], sig="Splash", myth=["carp leaping the dragon gate → becomes dragon"], nick=["most useless Pokemon"], c2="white")
E("Gyarados", arch=["serpent","dragon"], based=["Chinese dragon (carp that became a dragon)"], sprite=["serpent-body","fangs","barbels"], sig="", myth=["carp → dragon transformation"], role=["mega"], nick=["red Gyarados (Lake of Rage)"], c2="")
E("Lapras", arch=["plesiosaur"], based=["plesiosaur / Loch Ness Monster"], sprite=["shell-back","long-neck"], myth=["Nessie"], role=["gmax"], nick=["gentle ferry; near-extinct lore"], c2="gray")
E("Ditto", arch=["amorphous"], based=["amoeba / blob"], sprite=["pink-blob","dot-eyes"], sig="Transform", lore=["copies anything; breeding partner"], nick=["failed transformations (keeps its face)"], c2="")
E("Eevee", arch=["mammal","fox"], based=["fox / dog (evolution: 'eevee'='evolution')"], sprite=["fluffy-collar","bushy-tail"], lore=["unstable DNA; many evolutions"], role=["gmax","starter (Let's Go)"], nick=["Eeveelutions"], c2="cream")
E("Vaporeon", arch=["mermaid"], based=["mermaid / fish-cat"], sprite=["fins","frilled-collar"], lore=["Water Stone eeveelution"], nick=["copypasta"], role=["eeveelution"], c2="")
E("Jolteon", arch=["mammal"], based=["spiky electric fox"], sprite=["spiky-fur"], role=["eeveelution"], c2="white")
E("Flareon", arch=["mammal"], based=["fire fox/dog"], sprite=["fluffy-mane","fluffy-tail"], role=["eeveelution"], nick=["bad movepool discourse"], c2="yellow")
E("Porygon", arch=["mineral"], based=["polygon / 3D CGI / digital"], sprite=["blocky-body"], lore=["first man-made Pokemon"], nick=["banned seizure episode (blamed on Pikachu)"], c2="blue")
E("Omanyte", arch=["mollusc","ammonite"], based=["ammonite"], sprite=["spiral-shell","tentacles"], role=["fossil"], c2="blue")
E("Omastar", arch=["mollusc","ammonite"], based=["ammonite (giant)"], sprite=["spiral-shell","beak","spikes"], role=["fossil"], c2="blue")
E("Kabuto", arch=["arthropod","trilobite"], based=["horseshoe crab / trilobite"], sprite=["dome-shell","red-eyes"], role=["fossil"], c2="brown")
E("Kabutops", arch=["arthropod","trilobite"], based=["horseshoe crab (raptor form)"], sprite=["scythe-arms","shell"], role=["fossil"], c2="brown")
E("Aerodactyl", arch=["pterosaur","raptor"], based=["pterodactyl","dragon"], sprite=["wings","fangs"], role=["fossil","mega"], c2="gray")
E("Snorlax", arch=["bear"], based=["sleeping glutton (designer's friend)"], sprite=["big-belly","sleepy"], sig="", lore=["blocks roads; always sleeping/eating"], role=["gmax"], nick=["road blocker"], c2="cream")
E("Articuno", arch=["bird"], based=["ice bird / phoenix (freeze)"], sprite=["ice-wings","crest","tail"], loc=["Seafoam Islands"], role=["legendary"], nick=["legendary bird trio"], c2="")
E("Zapdos", arch=["bird"], based=["thunderbird (Native American myth)"], sprite=["spiky-wings","spiky-crest"], myth=["thunderbird"], loc=["Power Plant"], role=["legendary"], nick=["legendary bird trio"], c2="")
E("Moltres", arch=["bird","phoenix"], based=["phoenix / firebird"], sprite=["flame-wings","flame-crest"], myth=["phoenix"], loc=["Victory Road / Mt. Ember"], role=["legendary"], nick=["legendary bird trio"], c2="")
E("Dratini", arch=["serpent","dragon"], based=["Chinese dragon / mizuchi serpent"], sprite=["serpent-body","forehead-orb"], loc=["Safari Zone / Dragon's Den"], nick=["fishing rarity"], c2="white")
E("Dragonair", arch=["serpent","dragon"], based=["Chinese dragon / mystical serpent"], sprite=["neck-orbs","wing-crest"], myth=["dragon that controls weather"], c2="white")
E("Dragonite", arch=["dragon"], based=["Western dragon (but friendly/kind)"], sprite=["antennae","small-wings"], sig="", lore=["rescues sailors; gentle"], role=["pseudo"], nick=["fat dragon; carries mail"], c2="cream")
E("Mewtwo", arch=["humanoid"], based=["genetically-engineered clone of Mew"], sprite=["tube-neck","tail"], sig="Psystrike", lore=["cloned in Cinnabar Mansion; movie antagonist"], loc=["Cerulean Cave"], role=["legendary","mega"], nick=["first movie villain"], c2="purple")
E("Mew", arch=["mammal"], based=["cat / fetus (ancestor of all Pokemon)"], sprite=["small","long-tail"], sig="", lore=["contains all Pokemon DNA; ancestor of all"], role=["mythical"], nick=["truck myth (Mew under the truck)"], c2="")

if __name__=="__main__":
    out=os.path.join(HERE,"curated_overlay.json")
    # Merge: keep any existing (not-yet-re-authored) entries, overwrite with the
    # freshly curated ones here. Lets us curate gen-by-gen without losing prior work.
    merged={}
    if os.path.exists(out): merged.update(json.load(open(out)))
    merged.update(DATA)
    json.dump(merged, open(out,"w"), ensure_ascii=False, indent=0)
    print(f"wrote {out}: {len(DATA)} re-authored, {len(merged)} total curated entries")
